### ISSUE TITLE
Not working for some Cupertino Widgets

### ISSUE THREAD

**Issue by rubberbird** [aissat/easy_localization#105]
> I/flutter ( 1053): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> I/flutter ( 1053): The following NoSuchMethodError was thrown building LayoutBuilder:
> I/flutter ( 1053): The getter 'alertDialogLabel' was called on null.
> I/flutter ( 1053): Receiver: null
> I/flutter ( 1053): Tried calling: alertDialogLabel

Apparently it's related to the `localizationsDelegates` below.

```
localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        EasyLocalization.of(context).delegate,
      ],

```
This issue https://github.com/flutter/flutter/issues/23047 says that it needs to add the following. However this doesn't seem to be exist anymore.

```
  localizationsDelegates: const [
    S.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate, //<--- Add this to your localizationsDelegates in your Material App
    GlobalWidgetsLocalizations.delegate,
  ],
```

**Comment by Overman775** [comment]
@rubberbird Yep, need and GlobalCupertinoLocalizations.delegate, did this solve your issue?
