### ISSUE TITLE
Flickering black screen

### ISSUE THREAD

**Issue by Overman775** [aissat/easy_localization#106]
Hi @aissat.
I found the reason for the flickering black screen, this is due to the asset loader.

You can check by replacing the loader in `asset_loader.dart`

```
  @override
  Future<Map<String, dynamic>> load(String localePath) async {
      await Future.delayed(Duration(seconds: 5));
      return json.decode(await rootBundle.loadString(localePath));
  }
```
**Solutions:** 
1. code generation from json.
2. use isolate

How do you like the idea?

**Comment by aissat** [comment]
@Overman775  thinking use Bloc architect

**Comment by Overman775** [comment]
> @Overman775 thinking use Bloc architect

Dart single threaded language, It will not make a difference.

Black screen is only in develop version, i test on 6 years old android phone, all fine ;)
I was mistaken, it was necessary to check on a real device 😄

**Comment by aissat** [comment]
> @Overman775 thinking use Bloc architect
> 
> Dart single threaded language, It will not make a difference.
> 
> Black screen is only in develop version, i test on 6 years old android phone, all fine ;)
> I was mistaken, it was necessary to check on a real device 😄
lol
yup , i agree with u 💯

**Comment by aissat** [comment]
@Overman775 plz check 
https://github.com/aissat/easy_localization/tree/dev-bloc

**Comment by Overman775** [comment]
> @Overman775 plz check
> https://github.com/aissat/easy_localization/tree/dev-bloc

@aissat Ok, I'll check tomorrow
