### ISSUE TITLE
title and bottom navigation bar item not translate after setting local success.

### ISSUE THREAD

**Issue by liudonghua123** [aissat/easy_localization#108]
I have a page which contains some bottom navigationbar  item and in one page, I set the locale and the strings of current page changed except the appbar title and bottom navigationbar items. I have to click any of the navigationbar  item, then it changed.
I simplify the code and make a demo on https://github.com/liudonghua123/redux_thunk_example/tree/locale, and you can reproduce the issue on https://liudonghua123.github.io/redux_thunk_example/

I checked the console log and find after changing the locale, the translation is not change.
```
localePath: assets/langs/en-US.json
load true
home build, locale: en_US, title: App
select locale: zh_CN
[INFO] LoggingMiddleware: {Action: LocaleAction{locale: zh_CN}, State: AppState{locale: zh_CN}, ts: 2020-03-28 21:57:25.121}
localePath: assets/langs/zh-CN.json
home build, locale: zh_CN, title: App
load true
home build, locale: zh_CN, title: 应用
```

The initial page is

![image](https://user-images.githubusercontent.com/2276718/77824527-5b2fed00-713e-11ea-92b0-9d8f2a07d589.png)

When I change the language to the Chinese, the current page translated except the title and bottom bar items. I have to click any of the bottom item to make the whole page translate.

I have spent a few days on this strange issue. 
I tested on android/web/windows platform, all of them have this problem.

**Comment by liudonghua123** [comment]
@aissat Hi, I add some debug info on the following location.

![image](https://user-images.githubusercontent.com/2276718/77824819-510eee00-7140-11ea-9654-045d22119dbe.png)

And I find that when I change the locale back and forth, this method is always invoked, it seems lack of cache the language assets. Maybe I am wrong about this.

**Comment by liudonghua123** [comment]
If I and a debug print in the builder of MaterialApp, I got the following error. It seems have something in common with https://github.com/aissat/easy_localization/issues/103.
![image](https://user-images.githubusercontent.com/2276718/77824979-5f113e80-7141-11ea-9b85-fb8ab8893e5f.png)

**Comment by liudonghua123** [comment]
I tried to rewrite and test it with another package (https://pub.dev/packages/flutter_translate), it seems has  the same issue.

**Comment by aissat** [comment]
> If I add a debug print in the builder of MaterialApp, I got the following error. It seems have something in common with #103.
> ![image](https://user-images.githubusercontent.com/2276718/77824979-5f113e80-7141-11ea-9b85-fb8ab8893e5f.png)
same issue #103

**Comment by aissat** [comment]
> If I add a debug print in the builder of MaterialApp, I got the following error. It seems have something in common with #103.
> ![image](https://user-images.githubusercontent.com/2276718/77824979-5f113e80-7141-11ea-9b85-fb8ab8893e5f.png)
same issue #103

**Comment by aissat** [comment]
> If I add a debug print in the builder of MaterialApp, I got the following error. It seems have something in common with #103.
> ![image](https://user-images.githubusercontent.com/2276718/77824979-5f113e80-7141-11ea-9b85-fb8ab8893e5f.png)
same issue #103

**Comment by liudonghua123** [comment]
@aissat Hi, I think it's not the same as #103, the bottom navigation bar item is not translate, that's not the same as appbar.

**Comment by liudonghua123** [comment]
There is a similar issue on https://github.com/bratan/flutter_translate/issues/38, after some debug, I found it's async/await issue (https://github.com/bratan/flutter_translate/pull/39), However I haven't find the reason of this issue in easy_localization.
The internal implementation of `EasyLocalization.of(context).locale = locale;` is not same as `changeLocale(context, locale);` which flutter_translate does.

**Comment by aissat** [comment]
Check #116
