### ISSUE TITLE
Add loadPath to load translations from backend

### ISSUE THREAD

**Issue by Taym95** [aissat/easy_localization#11]
Hey, thank you for this awesome package, It will be nice if we can load translations files from backend, the same approach but we use `http.get` instead of `rootBundle.loadString`

example: 
`EasylocaLizationDelegate(locale: data.locale , path: 'resources/langs', loadPath: "https://jsonplaceholder.com/resources/langs")`

`{`loadPath`/{languageCode}-{countryCode}.json}`

What do you think? I can send PR to add this feature!

**Comment by gedw99** [comment]
Also need this

**Comment by aissat** [comment]
@Taym95  thanks bro 🙏⭐⭐⭐ #16
