### ISSUE TITLE
Support App Name Localization

### ISSUE THREAD

**Issue by deadsoul44** [aissat/easy_localization#118]
Is it possible to add app name localization feature?

**Comment by aissat** [comment]
@deadsoul44  plz more details

**Comment by Overman775** [comment]
> I mean this library can support app name localization in AndroidManifest.xml which is seen by user after installing on phone.
> 
> ```
>     <application
>         android:name="io.flutter.app.FlutterApplication"
>         android:label="App Name"
>         android:icon="@mipmap/ic_launcher"
>         android:usesCleartextTraffic="true">
> ```
> 
> For example, we can define a special key in json files such as "android_label" and corresponding name for each language.

Nope, only one way AndroidManifest and strings.

1. edit Android manfist, change `android:label="@string/app-name"`
2. create localization(values, values-en, values-fr) folder
3. create localized strings.xml

```
<resources>
    <string name="app-name">App Name</string>
</resources>
```
Learn this https://developer.android.com/guide/topics/resources/localization.html

**Comment by aissat** [comment]
@deadsoul44 think this wat u need
