### ISSUE TITLE
Pluralization 2.0

### ISSUE THREAD

**Issue by Overman775** [aissat/easy_localization#121]
I have a good idea for new Pluralization, but these are breaking changes
https://kazupon.github.io/vue-i18n/guide/pluralization.html#accessing-the-number-via-the-pre-defined-argument

1. All variables in one line with ` | ` splitter
2. Count add with {n} regexp
3. Pluralized strings match numbers and not words(zero, one, others)
4. Custom pluralization

**Comment by aissat** [comment]
> I have a good idea for new Pluralization, but these are breaking changes
> https://kazupon.github.io/vue-i18n/guide/pluralization.html#accessing-the-number-via-the-pre-defined-argument
> 
>     All variables in one line with | splitter
>     Count add with {n} regexp
>     Pluralized strings match numbers and not words(zero, one, others)
>     Custom pluralization

@Overman775 I like it
