### ISSUE TITLE
Package does not work correctly if there is a symbol at the end of the path /

### ISSUE THREAD

**Issue by Laim0n** [aissat/easy_localization#129]
I spent a month searching for a bug in my project that caused multilanguage to work incorrectly. In short: the release version did not run at all, and in debug mode there was a situation
![image](https://user-images.githubusercontent.com/25152332/78507237-960dd280-7787-11ea-8aa7-8cdd0725ea91.png)
that was treated with a hot reboot. I found a solution: the error was that in the path to translates, at the end was a character /.
`path: 'resources/lang/'`.

Make an explicit exception, or allow a character to be specified. I have been looking for a solution to this error for a very long time! And sorry for the possibly bad English, I use a translator.

**Comment by aissat** [comment]
@Laim0n  correct ur path ` resources/lang/` to` resources/lang`
