### ISSUE TITLE
Save selected localization 

### ISSUE THREAD

**Issue by KsAmJ** [aissat/easy_localization#13]
If user have the ability to save his localization on a shared preference how to load it on application strart up?

As it always goes back to the default app unless it is overridden again on app

**Comment by jkarelbroer** [comment]
@aissat Looking forward for a solution for this question too. I've try to use this code in the initState(), but that gives me an Unhandled Exception error...

`  Future setLocale() async {
    final data = EasyLocalizationProvider.of(context).data;
    final String savedLanguage = await Localizer.getLanguageCode();
    data.changeLocale(Locale(savedLanguage));
    languageLabel = kLanguageLabels['$savedLanguage'];
  }`

**Comment by KsAmJ** [comment]
Why this issue closed without resolving it ?????
LOL

**Comment by KsAmJ** [comment]
My bad .. didn't see the oast commit ...will give it a try and let you know thanks alot

**Comment by jkarelbroer** [comment]
@aissat Got this fatal error while loading main.dart using 1.2.1:

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'dart:ui/window.dart': Failed assertion: line 277: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      new Locale (dart:ui/window.dart:277:15)
#3      EasylocaLizationDelegate.load (package:easy_localization/easy_localization_delegate.dart:100:14)
<asynchronous suspension>
#4      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
#5      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:508:62)
#6      _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:473:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
#10     Element.updateChild (package<…>`

Looks like something goes wrong in the EasylocaLizationDelegate class.
Can you please take a look at it? Thanks in advance!
