### ISSUE TITLE
iOS device language

### ISSUE THREAD

**Issue by MajidAlNuumani** [aissat/easy_localization#130]
I am testing this package to choose device default language. here is what happen. In android it took the default device language but in iOS (iphone 11) is not take device language.

My device language is Arabic.

Waiting you help. 

Thank you

**Comment by Overman775** [comment]
learn this: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#appendix-updating-the-ios-app-bundle

example: https://github.com/aissat/easy_localization/issues/98#issuecomment-602197070

**Comment by HugoHeneault** [comment]
This should be in the README, so we can set it up on plugin install :)
