### ISSUE TITLE
flutter_localizations dependency is not found 

### ISSUE THREAD

**Issue by TesfahunK** [aissat/easy_localization#131]
i recently upgraded this package and im getting this error:
**flutter_localizations any which doesn't exist (could not find package flutter_localizations at https://pub.dartlang.org), version solving failed**
the old versions used to automatically add flutter_localizations package but the newer one doesn't and throws an error when i try to add it. Any solution will be helpful , Thanks

**Comment by Overman775** [comment]
@TesfahunK pubspec.yaml should contain

```
dependencies:
  flutter_localizations:
    sdk: flutter
```

read this https://github.com/aissat/easy_localization#configuration
