### ISSUE TITLE
v2.1.0+0 and v.2.1.0+1 causes blank white screen for initial render

### ISSUE THREAD

**Issue by fyredave** [aissat/easy_localization#133]
When upgrading from v2.0.1+2 to any 2.1.0 build, initial renders of a widget tree start with a white screen instead of black. My theme is dark so this causes quite a few issues. My own app theme data seems to be ignored. Sticking with v2.0.1+2 until you guys can address this.

**Comment by aissat** [comment]
@fyredave u need use
`preloaderColor: Colors.black,`

**Comment by fyredave** [comment]
Ok thank you, that's good news. Might be a good idea to update the readme with the new example code.
