### ISSUE TITLE
Feature Request : Handle widget parameter for the loading process

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [aissat/easy_localization#142]
It would be great if this widget is replaced with ```widget.preloaderWidget ?? EmptyPreloaderWidget()```

![image](https://user-images.githubusercontent.com/52201392/79428848-0954e700-7fc7-11ea-9667-e7c730d0d2e7.png)

**Comment by AlaaEldeenYsr** [comment]
When this will be available on pup ? 😃
@aissat

**Comment by Overman775** [comment]
@AlaaEldeenYsr released, 2.2.2-dev.0
