### ISSUE TITLE
Can't get new state in BlocListener due to easy_localization 

### ISSUE THREAD

**Issue by don-prog** [aissat/easy_localization#144]
Hello.
I have an application with [bloc](https://github.com/felangel/bloc) and `easy_localization`. My app loads `SplashPage` until everything is ready, and after that it changes the page. All fine and obvious without localizations, but when it is turned on, a new state will not be received and the `SplashPage` will not change to the `FirstPage`.
Please check [minimal working example here.](https://github.com/don-prog/easy_localization_bloc_bug)
How can I fix it?

**Comment by aissat** [comment]
@don-prog plz log msg and why create [app_localizations.dart](https://github.com/don-prog/easy_localization_bloc_bug/blob/master/lib/app_localizations.dart) :(

**Comment by don-prog** [comment]
@aissat thanks for your reply!
1. app_localizations.dart - was a legacy from a previous localization try and and did absolutely nothing in this repo. I got rid of it in the last commit, you can check.
2. easy_localization logs:

> [log] EasyLocalization
> [log] initState
> [log] easy localization: Build
> [log] easy localization: Device locale en_US
> [log] easy localization: Load asset from resources/langs
> [log] easy localization: Build
> [log] easy localization: Init Localization Delegate
> [log] easy localization: Init provider
> [log] easy localization: Load Localization Delegate

**Comment by aissat** [comment]
@don-prog  easy_localization working well, about app_localizations.dart u do not need it

**Comment by don-prog** [comment]
@aissat yes, I understand that, so, as I said, I deleted it :)
But of course it didn’t change anything and there is still a problem.

**Comment by aissat** [comment]
@don-prog  I'll check ur code

**Comment by Overman775** [comment]
@don-prog @aissat try like this #125

**Comment by don-prog** [comment]
@Overman775 thanks for suggestion, but I use the `bloc` in many places, I can't just use `Provider` in one place as Ad hoc due to the consistency. Maybe you can provide a solution for the `bloc`?

**Comment by Overman775** [comment]
@don-prog problem in your code, you send event to block but listener not created at this moment, use BlockBuilder

```
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        EasyLocalization.of(context).delegate,
      ],
      supportedLocales: EasyLocalization.of(context).supportedLocales,
      locale: EasyLocalization.of(context).locale,
      home: Scaffold(
        body: BlocBuilder<MainBloc, MainState>(
          builder: (context, state) {
            print(state);
            if (state is ReadyState) {
              print('first_page');
              return Navigator(
                key: rootNavigatorKey,
                initialRoute: 'first_page',
                onGenerateRoute: RouteGenerator.generateRoute,
              );
              //return FirstPage();
            } else {
              print('splash_page');
              return SplashPage();
              /*
              ///your variant
              return Navigator(
                key: rootNavigatorKey,
                initialRoute: 'splash_page',
                onGenerateRoute: RouteGenerator.generateRoute,
              );*/
            }
          },
        ),
      ),
    );
  }
```
