### ISSUE TITLE
Changing App start language

### ISSUE THREAD

**Issue by dan15h** [aissat/easy_localization#145]
I can't figure any way to change the default language of the app when the app starts.
For example: I want korean as active language when user install the App.
Already tried this in Material App: 
`locale:  Easy_Localization.of(context).getSupportedLangs[1]`

Assuming that korean is placed at index 1.

**Comment by aissat** [comment]
@dan15h try version` 2.2.1 `now u can use `startLocale` 
```dart
EasyLocalization(
            child: MyApp(),
            path: 'i18n',
            startLocale: Locale('ar', 'DZ'),
            supportedLocales: [Locale('en', 'US'), Locale('ar', 'DZ')], 
          )
```
