### ISSUE TITLE
Images Localization

### ISSUE THREAD

**Issue by cabustos** [aissat/easy_localization#147]
Kind regards, your library is a great help, I am getting to know it and I have found it fabulous, how could you personalize some images based on the language and location of the json

**Comment by Overman775** [comment]
@cabustos 
Easy, get locale and add to patch

```dart
var loacaleString = EasyLocalization.of(context).locale.toString();
var localizedImage = 'assets/images/image_$loacaleString.jpg'; /// assets/images/image_en_US.jpg
```
