### ISSUE TITLE
Localization failed for CSV loader

### ISSUE THREAD

**Issue by Wilson13** [aissat/easy_localization#153]
**Version**:
- easy_localization: ^2.2.1
- easy_localization_loader: ^0.0.2

**Description**:
I encountered this error when using a CSV file to provide for localization.

**Error**:
[easy_localization] Missing message : Not found this Key ["clickMe"] 

**Details**
This is my main.dart:
```
void main() => runApp(
  EasyLocalization(
    child: MyApp(),
    supportedLocales: [
      // English
      Locale('en', 'SG'),
      // Mandarin
      const Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans', countryCode: 'SG'),
      // Malay
      Locale('ms', 'SG'),
      // Tamil
      Locale('ta', 'SG'),
    ],
    path: 'assets/langs/langs.csv',
    assetLoader: CsvAssetLoader()
  ));

```
This is how I log them:
```
Widget build(BuildContext context) {
    log(EasyLocalization.of(context).locale.toString(),
        name: '${this} # locale');
    log(tr('clickMe').toString(), name: this.toString());
```

This is my CSV content:
```
str,en_SG,zh_Hans_SG_,ms_SG,tm_SG
clickMe,Test,السلام,Hallo,Привет!
title,what,السلام,Hallo,Привет!
```

Or am I using this library wrongly? Do I need to generate string keys in order to use them? After reading the README and checking the code, I assume it can load a CSV file and use it directly though.

**Comment by Overman775** [comment]
@Wilson13 show debug log

**Comment by Overman775** [comment]
@Wilson13 you wrong write lang tag in csv file, delete last `_` in `zh_Hans_SG_`

**Comment by Wilson13** [comment]
@Overman775 Thanks for noticing that, so now I removed the zh_Hans_SG_ entirely, and to simplify things, I kept only two locales, but the error persisted.

langs.csv
```
str,en_SG,ms_SG
clickMe,Test,Hallo
title,what,Hallo
```

Usage
`print('title'.tr());`

Logs
[Easy Localization] Start locale loaded ms_SG
[log] easy localization loader: load csv file assets/langs/langs.csv
[Easy Localization] Init Localization Delegate
[Easy Localization] Init provider
[MyApp # locale] ms_SG
[Easy Localization] Load Localization Delegate
I/flutter ( 4456): [WARNING] Easy Localization: Localization key [title] not found
I/flutter ( 4456): title

**Comment by Wilson13** [comment]
Also, I've tried using just JSON files and they work, but CSV is really a better way to manage the translations though.

@aissat

**Comment by aissat** [comment]
@Wilson13  plz need complete example

**Comment by Wilson13** [comment]
@aissat Hmm, it's the same as before my initial post but I'll just copy and paste here again, the only difference is I removed the one with typo and keep only 2 locales in the CSV.

Setup
```
runApp(
    EasyLocalization(
    child: MyApp(),
    supportedLocales: [
      // English
      Locale('en', 'SG'),
      // Malay
      Locale('ms', 'SG'),
    ],
    path: 'assets/langs/langs.csv',
    assetLoader: CsvAssetLoader(),
    startLocale: Locale('ms', 'SG'),
    fallbackLocale: Locale('ms', 'SG'),
  ));
```

Usage:
```
import 'package:easy_localization/easy_localization.dart';

print(context.supportedLocales);
print('title'.tr());
```

Logs
```
[Easy Localization] Start
[Easy Localization] Init state
[Easy Localization] Build
[Easy Localization] Start locale loaded ms_SG
[log] easy localization loader: load csv file assets/langs/langs.csv
[Easy Localization] Init Localization Delegate
[Easy Localization] Init provider
[Easy Localization] Load Localization Delegate
I/flutter (10426): [en_SG, ms_SG]
I/flutter (10426): [WARNING] Easy Localization: Localization key [title] not found
I/flutter (10426): title
```

CSV content
```
str,en_SG,ms_SG
clickMe,Test,Hallo
title,what,Hallo
```

CSV Preview
<img width="328" alt="Screenshot 2020-05-18 at 6 43 08 PM" src="https://user-images.githubusercontent.com/5605451/82204420-6d0c6000-9937-11ea-9f35-de211d9b5b68.png">
*ignore the auto-capitalised case of header, it's auto formatted by the VS Code plugin.

Thanks.

**Comment by frencojobs** [comment]
This happened to me today. Had to change the EOL of csv file to `CRLF` from `LF` to make it work.
