### ISSUE TITLE
Showing key name when key is missing in the json file

### ISSUE THREAD

**Issue by palkesh-jain** [aissat/easy_localization#154]
I have multiple JSON files for different language mappings. There are keys which might not be available in other files. Is there any way to create a `default` Locale? So whenever a key is missing it will pick from the default one.

The `strings.xml` in Android is implemented that way. So, even if you miss the key, the user won't see the `key` name.

**Comment by WingCH** [comment]
Same problem!

**Comment by Aqua-Ye** [comment]
Need the same thing!

**Comment by 2shrestha22** [comment]
Any update on this? Can we show strings from default locale if key is not available in current locale?

**Comment by fior-di-latte** [comment]
I wrote a small python script to check which keys are missing:

**check_missing_translations.py**

```
import argparse
import json
import re

def find_missing_keys(reference_file, files):
    with open(reference_file, 'r') as ref_file:
        reference_data = json.load(ref_file)

    missing_keys = set(reference_data.keys())

    for file in files:
        with open(file, 'r') as json_file:
            json_data = json.load(json_file)

        json_keys = set(json_data.keys())
        missing_keys -= json_keys

    return missing_keys

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Find missing keys in JSON files.')
    parser.add_argument('reference', help='Reference JSON file')
    parser.add_argument('files', nargs='+', help='JSON files to compare')
    args = parser.parse_args()

    missing_keys = find_missing_keys(args.reference, args.files)

    print("Missing keys:")
    for key in missing_keys:
        print(key)
```

Use:
`python3 check_missing_translations.py reference_language.json some_other_language.json`
