### ISSUE TITLE
Don't import implementation files from another package.

### ISSUE THREAD

**Issue by palkesh-jain** [aissat/easy_localization#159]
I am getting `Don't import implementation files from another package.` warning in the **codegen_loader.g.dart** file.

 [Flutter documentation](https://dart-lang.github.io/linter/lints/implementation_imports.html)

**Comment by Overman775** [comment]
1. You must generate your codegen_loader.g.dart, run in terminal `flutter pub run easy_localization:generate`
2. import from **your lib**  `import 'generated/codegen_loader.g.dart';`

**Comment by palkesh-jain** [comment]
I have generated my own **codegen_loader.g.dart**. The warning is coming inside that. 

> File Location
![Screenshot 2020-05-02 at 6 21 44 PM](https://user-images.githubusercontent.com/10001899/80864769-56f97100-8ca2-11ea-8e4a-48d6844ddcd2.png)

> Warning on line 4 of codegen_loader.g.dart
![Screenshot 2020-05-02 at 6 24 29 PM](https://user-images.githubusercontent.com/10001899/80864771-59f46180-8ca2-11ea-9a40-2a381fada15e.png)

**Comment by Overman775** [comment]
@palkesh-jain change 4 line on this import 'package:easy_localization/easy_localization.dart' show  AssetLoader;

**Comment by Overman775** [comment]
@palkesh-jain warning gone?

**Comment by palkesh-jain** [comment]
Thanks @Overman775, it worked.

**Comment by kamleshwebtech** [comment]
> @palkesh-jain change 4 line on this `import 'package:easy_localization/easy_localization.dart' show AssetLoader;`

Dear this did not help me /solved my problem. I am using file_picker package and importing it as you suggested:

import 'package:file_picker/file_picker.dart' show FilePicker, FilePickerResult, FileType;

but still getting "Don't import implementation files from another package." error in "generated_plugin_registrant.dart" file.

Kindly suggest what is the issue and how can we fix it. Thanks a lot.
