### ISSUE TITLE
Source path does not exist

### ISSUE THREAD

**Issue by yeahia2508** [aissat/easy_localization#162]
I followed all steps to initialize. But getting this error. Any solution?

**Used this command to generate :**
`flutter pub run easy_localization:generate  -f keys -o locale_keys.g.dart`

**current version** : `2.2.1 `

**Flutter Doctor:**

[✓] Flutter (Channel beta, v1.17.0-3.3.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0-3.3.pre at /Volumes/Workspace/Sdk/flutter
    • Framework revision 0da1ab0922 (6 days ago), 2020-04-28 11:02:34 -0700
    • Engine revision 376ad6a64b
    • Dart version 2.8.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/telenorhealth/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/telenorhealth/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

**Comment by Overman775** [comment]
@yeahia2508 change source patch `flutter pub run easy_localization:generate -f keys -o locale_keys.g.dar -s <patch_to_locales>`

**Comment by yeahia2508** [comment]
solved. thanks
