### ISSUE TITLE
_osLocale is null when saveLocale flag is true (default)

### ISSUE THREAD

**Issue by kightsonsanom** [aissat/easy_localization#163]
In the newest release if the saveLocale flag is set to true, which is default then the _osLocale variable will never be set. 

![image](https://user-images.githubusercontent.com/24854180/81077081-c9f62800-8eec-11ea-9e7a-ff9b74424073.png)

Later on _osLocale is used in _checkInitLocale method which results with following exception

`Unhandled Exception: NoSuchMethodError: The getter 'languageCode' was called on null.`

**Comment by aissat** [comment]
Check #152 
Please try versions `2.2.2-dev` or `2.3.0-dev`
