### ISSUE TITLE
App locale is not changed when system locale changes

### ISSUE THREAD

**Issue by kightsonsanom** [aissat/easy_localization#164]
Hello, I am using the latest version of the library at the time of writing this issue which is 2.3.0. Here is my setup:

Language files are kept in assets/lang path, they are also listed  in pubspec.yaml
![image](https://user-images.githubusercontent.com/24854180/81167781-1c3f5380-8f96-11ea-9a28-824aabd43383.png)
![image](https://user-images.githubusercontent.com/24854180/81167836-3711c800-8f96-11ea-9e4b-f28140d3051e.png)

Json file looks like this

![image](https://user-images.githubusercontent.com/24854180/81167882-498c0180-8f96-11ea-8b3d-2c8de54b2991.png)
 And I have also generated LocaleKeys file:
![image](https://user-images.githubusercontent.com/24854180/81167920-5872b400-8f96-11ea-8d25-dcba189d1a0e.png)

Here is the application - simplified easy_localization example 

```
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:revote/generated/locale_keys.g.dart';

void main() {
  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: [
      Locale('en', 'US'),
      Locale('ar', 'EG'),
    ],
    path: 'assets/lang',
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(LocaleKeys.language).tr(context: context),
      ),
      body: Center(
            child: Text(
              tr(LocaleKeys.language),
              style: TextStyle(
                color: Colors.grey.shade600,
                fontSize: 15,
                fontWeight: FontWeight.bold,
              ),
            ),
      ),
    );
  }
}
```

The text does not update when the language of the device changes. It does change when the application is killed and opened again though. I was able to reproduce this on Pixel 2 API 29 and API24 and OnePlus 6 API 29

Am I missing something in my setup?

**Comment by Overman775** [comment]
@kightsonsanom locale not changet because it's saved, try set `saveLocale: false`

**Comment by kightsonsanom** [comment]
Unfortunately this is not the case, the locale is still not changed
![image](https://user-images.githubusercontent.com/24854180/81200236-fa5cc580-8fc3-11ea-8180-da6d947c17bc.png)

**Comment by Overman775** [comment]
@kightsonsanom send debug log. iOS?

**Comment by kightsonsanom** [comment]
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Debug service listening on ws://127.0.0.1:49856/UVhMy-J5mS0=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(32365): eglMakeCurrent: 0xea1f7020: ver 3 0 (tinfo 0xdec8db30)
D/eglCodecCommon(32365): setVertexArrayObject: set vao to 0 (0) 1 0
[log] easy localization: Init Localization Delegate
[log] easy localization: Init provider
[log] easy localization: Load Localization Delegate
D/EGL_emulation(32365): eglMakeCurrent: 0xea1ba340: ver 3 0 (tinfo 0xdec8d900)
D/eglCodecCommon(32365): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(32365): eglCreateContext: 0xea1f7140: maj 3 min 0 rcv 3
D/EGL_emulation(32365): eglMakeCurrent: 0xea1f7140: ver 3 0 (tinfo 0xdec8db30)
D/EGL_emulation(32365): eglMakeCurrent: 0xea1ba340: ver 3 0 (tinfo 0xdec8d900)
D/EGL_emulation(32365): eglMakeCurrent: 0xea1f7140: ver 3 0 (tinfo 0xdec8db30)
D/eglCodecCommon(32365): setVertexArrayObject: set vao to 0 (0) 10 0
```

after `easy localization: Load Localization Delegate` the language was changed in the device settings and I returned into the app

**Comment by Overman775** [comment]
@kightsonsanom need full log

**Comment by Overman775** [comment]
@kightsonsanom easy localization only once get device locale when app loaded

**Comment by kightsonsanom** [comment]
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Debug service listening on ws://127.0.0.1:50990/PONA7QtI834=/ws
Syncing files to device Android SDK built for x86...
[log] EasyLocalization
D/EGL_emulation( 2532): eglMakeCurrent: 0xea1a92a0: ver 3 0 (tinfo 0xea211bd0)
D/eglCodecCommon( 2532): setVertexArrayObject: set vao to 0 (0) 1 0
[log] initState
[log] easy localization: Build
[log] easy localization: Device locale en_US
[log] easy localization: Load asset from assets/lang
[log] easy localization: Init Localization Delegate
[log] easy localization: Init provider
[log] easy localization: Load Localization Delegate
D/EGL_emulation( 2532): eglMakeCurrent: 0xe211a300: ver 3 0 (tinfo 0xc5d78ed0)
D/eglCodecCommon( 2532): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation( 2532): eglCreateContext: 0xea1a93c0: maj 3 min 0 rcv 3
D/EGL_emulation( 2532): eglMakeCurrent: 0xea1a93c0: ver 3 0 (tinfo 0xea211bd0)
D/EGL_emulation( 2532): eglMakeCurrent: 0xe211a300: ver 3 0 (tinfo 0xc5d78ed0)
D/EGL_emulation( 2532): eglMakeCurrent: 0xea1a93c0: ver 3 0 (tinfo 0xea211bd0)
D/eglCodecCommon( 2532): setVertexArrayObject: set vao to 0 (0) 10 0
```

Yes, I also noticed that it does not take device locale after the initial loading of the app. I guess it might be something with delegates because that's where the locale is loaded, isn't it?

**Comment by Overman775** [comment]
@kightsonsanom Nope, this is the logic of this package, the device locale receives only once, and does not listen to changes in the device. What are you trying to change the language when the application was running is a non-standard situation

**Comment by kightsonsanom** [comment]
@Overman775 I see. I assumed this to be expected because it works this way in the minimal example from flutter docs: https://github.com/flutter/website/blob/master/examples/internationalization/minimal/lib/main.dart

When the device language is changed to spain, the text in the app changes without needing to kill/rebuild the app.

**Comment by Overman775** [comment]
> When the device language is changed to spain, the text in the app changes without needing to kill/rebuild the app.

Do not need rebuild/reinstall app, just set `saveLocale: false` and relaunch app, locale will change

**Comment by kightsonsanom** [comment]
I have also checked your sample application attached to the library repository and it also requires app to be rebuild in order to change the language. This would be nice feature to have but for the moment I have all the answers. Thank you for your time :) Good work on the library though
