### ISSUE TITLE
Cleanup README.md by linking to changelog and example

### ISSUE THREAD

**Issue by erf** [aissat/easy_localization#168]
Se PR: https://github.com/aissat/easy_localization/pull/167

I found README.md a bit large, including both the CHANGELOG.md and example.

I suggest instead linking to separate files for this.

BTW: Great library! :-)

**Comment by aissat** [comment]
Thanks @erf please make All update in one PR into doc branch
And please check [doc branch](https://github.com/aissat/easy_localization/tree/doc)
Thanks again

**Comment by erf** [comment]
@aissat is it ok i do some other cleanup as well? I think i can reword and simplify some of the sentences there as well.

**Comment by erf** [comment]
@aissat also i think instead of the `attributes` parts, we could generate docs from code using `dartdoc`, put that in a folder and link to it.

**Comment by erf** [comment]
@aissat also, maybe simplify to only use a couple of images, and make them smaller.

**Comment by erf** [comment]
I can make some other changes in a separate commit.

**Comment by erf** [comment]
I think you have too much information in the list of features, sometimes without telling what it actually does, which might confuses people and turn them off from the project. I'll try and simplify this. Also i dont see the point of the [x]. Will also do a few design tweaks.

**Comment by aissat** [comment]
> I can make some other changes in a separate commit on the `doc` branch.

Yeah, y can do :)

**Comment by aissat** [comment]
> @aissat also i think instead of the `attributes` parts, we could generate docs from code using `dartdoc`, put that in a folder and link to it.

About this we need working on source code

**Comment by erf** [comment]
There is also the difference between *localization* and *internationalization*, should use that wording correct. Although, there seem to be various definitions of those and not quite sure of it myself.

**Comment by erf** [comment]
btw: https://medium.com/dartlang/announcing-dart-2-8-7750918db0a

**Comment by aissat** [comment]
@erf  plz check #171

**Comment by erf** [comment]
@aissat i made a new PR with 3 commits at #170 

Not sure you want to use the last commit, it is kind of a big change, and i made a very simple example, but it is what i would like to see myself ;-)

**Comment by aissat** [comment]
> 
> 
> @aissat i made a new PR with 3 commits at #170
> 
> Not sure you want to use the last commit, it is kind of a big change, and i made a very simple example, but it is what i would like to see myself ;-)

@erf I like it, but need some changes

**Comment by erf** [comment]
off-topic, but i made my own minimal [csv_localizations](https://github.com/erf/csv_localizations) lib now, maybe you'll find it interesting.

**Comment by aissat** [comment]
> i'll close this now, as i have contributed as much as i wanted-to, and the rest you guys can add after merging the PR as per comment.
> 
> off-topic, but i made my own minimal [csv_localizations](https://github.com/erf/csv_localizations) lib now, maybe you'll find it interesting.

@erf thanks, and congratulations 
Easy localization already supported CSV, xml, yaml file by  [easy localization laoder](https://github.com/aissat/easy_localization_loader)

**Comment by erf** [comment]
thanks. yes i know, i just wanted something simple and to learn more :)
