### ISSUE TITLE
null is not a String error

### ISSUE THREAD

**Issue by jkarelbroer** [aissat/easy_localization#17]
Hi @aissat,
It looks like this function in the AppLocalizations class tries to replace a null value without checking:
`String tr(String key, {List<String> args}) {
    String res = this._resolve(key, this._sentences);
    if (args != null) {
      args.forEach((String str) {
        res = res.replaceFirst(RegExp(r'{}'), str);
      });
    }
    return res;
  }`

Hope you can create a fix for this.

**Comment by jkarelbroer** [comment]
Hi @aissat If you need any additional info on this issue, please let me know.

**Comment by jkarelbroer** [comment]
@aissat This should solve it:

`String tr(String key, {List<String> args}) {
    String res = this._resolve(key, this._sentences);
    if (args != null) {
      args.forEach((String str) {
        if(str != null) {
          res = res.replaceFirst(RegExp(r'{}'), str);
        }
      });
    }
    return res;
  }`

**Comment by aissat** [comment]
Hi @jkarelbroer 
Really I'm busy, will trying to fixed in the shortest possible time

**Comment by mohabmm** [comment]
hi @aissat if you can please fix it ..... our app depemds on it and it caused black screen issue in our app
