### ISSUE TITLE
Please make the prints optional, they clog the console every time you make hot reload.

### ISSUE THREAD

**Issue by nodermann** [aissat/easy_localization#173]

**Comment by Overman775** [comment]
You can disable developer.log in settings IDE

read this https://code.visualstudio.com/docs/getstarted/settings
search `dart.showDartDeveloperLogs` and disable

**Comment by pulstar** [comment]
I don't use Visual Studio... Is such setting available in Intellij Idea? By the way, will not it disable all log messages entirely? If it does, this is not an optimal solution.

**Comment by SaurabhSM** [comment]
Disabling developer logging is not solution for this. I will need developer logs on other issues, that is not solution at all.

**Comment by WingCH** [comment]
Same request

**Comment by EmmanuelMess** [comment]
I ask you to reopen this issue.

**Comment by furaiev** [comment]
@Overman775 could you please reopen this issue?

**Comment by krisztianodor** [comment]
Please make the logging optional! Until that i can't use your plugin because these prints are very annoying. I have never seen something like this in other plugins. By default, no public package should work this way.

**Comment by pulstar** [comment]
> Please make the logging optional! Until that i can't use your plugin because these prints are very annoying. I have never seen something like this in other plugins. By default, no public package should work this way.

I am experiencing the same problem in the official camera plugin. A lot of messages appear in the log, that runs crazy... I agree to you that public packages must be clean.

**Comment by Overman775** [comment]
#315

**Comment by Overman775** [comment]
PR #315 merget
