### ISSUE TITLE
adding EasyLocalization as first in a build method fails

### ISSUE THREAD

**Issue by erf** [aissat/easy_localization#174]
Instead of adding `EasyLocalization` in `main`, i tried to return it first in the `MyApp` build method, with a `MaterialApp` as a child. 

This fail with: `The getter 'delegate' was called on null.`

Should this not be allowed?

**Comment by Overman775** [comment]
@erf Nope
EasyLocalization must be upper in widget tree then MaterialApp because EasyLocalization chnage locale in MaterialApp, attach delegates and rebuild widgets when locale changed

**Comment by erf** [comment]
Is it not upper if MaterialApp is a child?

**Comment by Overman775** [comment]
@erf Upper, need see code example
