### ISSUE TITLE
What differences between langs files ?

### ISSUE THREAD

**Issue by AdelMahmoudHussein** [aissat/easy_localization#175]
what is the differences between using (en-US.json, en.json)?
and when use  langs.csv ?

can I only make all translation in langs.csv like above and use it to create LocalKeys ? and How that?

**Comment by aissat** [comment]
@AdelMahmoudHussein 
easy_localization  give u more choice coz supports JSON by default, CSV, Yaml, XML Files ... need use [Easy Localization Loader](https://github.com/aissat/easy_localization_loader)
 about `LocalKeys` generated by easy_localization tool currently supported JSON file 
```
$ flutter pub run easy_localization:generate -h
-s, --source-dir     Source folder contains all string json files
                    (defaults to "resources/langs")
-O, --output-dir     Output folder stores generated file
                    (defaults to "lib/generated")
-o, --output-file    Output file name
                    (defaults to "codegen_loader.g.dart")
-f, --format         Support json, dart formats
                    [json (default), keys]
```
`flutter pub run easy_localization:generate  -f keys -o locale_keys.g.dart`

**Comment by AdelMahmoudHussein** [comment]
Thank you very much, but How can I get the device default language, and how to use it as the first localization of my app ?

**Comment by Overman775** [comment]
@AdelMahmoudHussein Easy localization default get locale from device, but if you change locale will be save. For disable save use `saveLocale: false`. If you need override device locale use 'startLocale'

**Comment by AdelMahmoudHussein** [comment]
Thanks,
What is the scenario if device is for example ar_EG and there is no ar_EG in my locales but have ar_DZ ?

Do I need to add all languages with its country code in my locales ?

**Comment by aissat** [comment]
> Thanks,
> What is the scenario if device is for example ar_EG and there is no ar_EG in my locales but have ar_DZ ?
> 
> Do I need to add all languages with its country code in my locales ?

no not requird added country code for ur locales, u can use `useOnlyLangCode: true`

**Comment by AdelMahmoudHussein** [comment]
@aissat @Overman775 
Thank you all very much, now I can do it.

**Comment by aissat** [comment]
You're welcome
