### ISSUE TITLE
Refresh remote translations

### ISSUE THREAD

**Issue by lcaprini** [aissat/easy_localization#181]
I'm using EasyLocalization with a REST JSON API to fetch translations in a requested language; after that I save them inside SharedPreferences and I use the a custom loader to fetch them from there.

I would like to refresh that translations on some situations, like autologin, or inside the settings page, etc, but when I try to set the same language already set, the loader doesn't run again, and the freshed translations does not picked up by EasyLocalization.

There is a way to force the EasyLocalization to programmatically run the `load` method in custom loader?

Thanks,
--Luca

**Comment by enricoquarantini** [comment]
I'm trying to do something similar but I run into an error: [https://github.com/aissat/easy_localization/issues/180](https://github.com/aissat/easy_localization/issues/180)

**Comment by lcaprini** [comment]
I don't think my issue is related to yours: I'm trying to refresh a language translation map, while you are trying to refresh the supportedLocales. (BTW I also interested in your issue, because it could be a really nice feature)

**Comment by Overman775** [comment]
@lcaprini For optimization, only once a translation is loaded, you need to recreate the widget. Perhaps in the future we will realize such a function or you can help progect by doing PR  :wink:

**Comment by lcaprini** [comment]
And how can I recreate the widget? Maybe I have to use the same "trick" of @enricoquarantini 's issue, using the key in EasyLocalization widget? I also saw your proposal for `preloaderWidget`, but I don't find any docs about that. Could you help me?

For the PR, I'm a newbie on Flutter :(  ... Maybe in the future :)

**Comment by Overman775** [comment]
@lcaprini maybe the solution of @enricoquarantini will help, you need to try.
Documentation in process.
`preloaderWidget` parapmetr show your custom widget until the translation loads, just pass the class with the widget, look at an example
