### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by Nailik** [aissat/easy_localization#189]
Hello,
since you use the shared prefs package it's not working on windows desktop anymore, because this package has no windows desktop  implementation.
I know the SharedPrefs.getInstance() is only called when `saveLocale:true` is set but it still didn't work for me (so i created a sloppy fork and removed all the shared orefs things).
I did not 100% test why it's not working but i would be happy if you could make a small decision in code if it is running on windows or not to fix this.

Greetings

**Comment by Overman775** [comment]
@Nalik In the future `shared_preference`s will have support on windows, look this [PR](https://github.com/flutter/plugins/pull/2631)

**Comment by Nailik** [comment]
@Overman775 Thank you, i had this in mind but was not sure how the status was currently.
