### ISSUE TITLE
Intl Package Version Issue

### ISSUE THREAD

**Issue by sathya4code** [aissat/easy_localization#191]
Hi,

I am using Easy localization in my app. I got the following error when i try to generate the build.

ERR : Because slc depends on flutter_localizations any from sdk which depends on intl 0.16.0, intl 0.16.0 is required.

    | So, because slc depends on intl ^0.16.1, version solving failed.

I have intl 0.16.1 which is used by another package.. I cant downgrade it. How to fix this conflict.

i am using Flutter 1.17.0 stable.

Thank you.

**Comment by Overman775** [comment]
add in pubspec 
```
dependency_overrides:
  intl: ^0.16.1
```
