### ISSUE TITLE
Continuous splash screen

### ISSUE THREAD

**Issue by zakiroof** [aissat/easy_localization#194]
Hello.
I'm trying to make a continuous splash screen at all stages of the application loading. But i see flicker while translation is loading. How can i fix it?

![ezgif-4-cb568f79355c](https://user-images.githubusercontent.com/23415277/83028688-31fee080-a04b-11ea-9433-3b3ee458fa92.gif)

```
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: [Locale('en')],
    path: 'assets/translations',
    fallbackLocale: Locale('en'),
    preloaderWidget: SplashScreen(),
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: SplashScreen()
    );
  }
}

class SplashScreen extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Image.asset("assets/bg.png", fit: BoxFit.fill,);
  }
}
```

**Comment by Overman775** [comment]
@zakiroof try add transprent color in preloaderColor
```
void main() {
  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: [Locale('en')],
    path: 'assets/translations',
    fallbackLocale: Locale('en'),
    preloaderColor: Colors.transparent,
    preloaderWidget: SplashScreen(),
  ));
}
```

**Comment by zakiroof** [comment]
@Overman775 now the black background is flickering

**Comment by Overman775** [comment]
@zakiroof write me in telegram https://t.me/Overman775

**Comment by fatimahossny** [comment]
I have the same issue , any help in that please

**Comment by Overman775** [comment]
@fatimahossny you chech this 'bug' in release mode?

**Comment by fatimahossny** [comment]
No , just in debug  mode, i will check it in release now

**Comment by Overman775** [comment]
@fatimahossny tested in release mode, same bug... Problem in loading from asset, need load image before you run `runApp` in `main()`

Same issue + how resolve bug
https://github.com/flutter/flutter/issues/26127

**Comment by fatimahossny** [comment]
@Overman775  some times in release works fine , in my case the image loads fine and the preloaderWidget works fine too , the issue is that i got the preloaded color for a seconds after preloaderWidget has gone . with a message in console of  `setup localization lazily!`   , `Build`  , `Init Localization Delegate` and `Init provider`
