### ISSUE TITLE
accessing current local without context

### ISSUE THREAD

**Issue by mohammadne** [aissat/easy_localization#196]
in my case for every api calls , I have to pass the current local as a parameter in http header and to access it , I should pass the current local from ```Presentation Layer``` to other layers to  access it from my ```Api Service```.

so passing local into multiple constructors is cumbersome , What do you suggest to access the local in easiest form ?
Thanks

**Comment by Overman775** [comment]
@mohammadne EasyLocalization uses an `InheretedWidget` to store state, so only passing the `context` or the widget itself is possible to acces locale, but you can read saved locale from `SharedPreferences`

```
    final _preferences = await SharedPreferences.getInstance();
    final _strLocale = _preferences.getString('locale');
```
