### ISSUE TITLE
Usage in background/isolate

### ISSUE THREAD

**Issue by kuhnroyal** [aissat/easy_localization#198]
I didn't find a way to access the translations without a Widget tree, for example in a background isolate. All the initialization is happening in the `EasyLocalization` class and everything is private.

Is there a way to achieve something like this or is such support planned?

**Comment by Overman775** [comment]
@kuhnroyal What is the problem of transferring ready-made translated data to isolate?

**Comment by kuhnroyal** [comment]
I am generating a PDF in a background isolate. The app might not be running so I can no access the `EasyLocalization`/`Translations`.

**Comment by Overman775** [comment]
@kuhnroyal you can pass context to isolate and work with translations

**Comment by kuhnroyal** [comment]
That is my problem, I don't have a context.

**Comment by Overman775** [comment]
@kuhnroyal you try past context in constructor? This is just an assumption, I did not work with isolates..

**Comment by kuhnroyal** [comment]
The BuildContext is only available when the app is actually running. In a background service there is no BuildContext. I need to get the `Localization.instance` and it needs to be set beforehand but this only happens in the `EasyLocalization` widget.

**Comment by kuhnroyal** [comment]
If the `src/localization.dart` and `src/translation.dart` files are to be exported. Then I can manually use an `AssetLoader` to set the instance.

**Comment by ncuillery** [comment]
@kuhnroyal you can import them. Since they aren't public, they don't show up in Autocomplete/Quick Fix from the IDE, but you can type the import by hand:

```
import 'package:easy_localization/src/localization.dart';
import 'package:easy_localization/src/translations.dart';
```

and use classes from those files.

**Comment by AhmetMelihSerter** [comment]
> I didn't find a way to access the translations without a Widget tree, for example in a background isolate. All the initialization is happening in the `EasyLocalization` class and everything is private.
> 
> Is there a way to achieve something like this or is such support planned?

If you wrote, can you share it on your github account?

**Comment by jonasN5** [comment]
> If the `src/localization.dart` and `src/translation.dart` files are to be exported. Then I can manually use an `AssetLoader` to set the instance.

Did you manage to do that? I have the exact same problem, typically happens for background notifications, where `BuildContext` is not available.

**Comment by AhmetMelihSerter** [comment]
> > If the `src/localization.dart` and `src/translation.dart` files are to be exported. Then I can manually use an `AssetLoader` to set the instance.
> 
> Did you manage to do that? I have the exact same problem, typically happens for background notifications, where `BuildContext` is not available.

I tried it works. Thanks. 

https://github.com/aissat/easy_localization/issues/210#issuecomment-806089855
