### ISSUE TITLE
Loading localization in unit tests

### ISSUE THREAD

**Issue by necipk** [aissat/easy_localization#199]
What is the easy way of loading LocaleKeys in unit tests.

**Comment by Overman775** [comment]
@necipk you need LocaleKeys or localized keys?

**Comment by necipk** [comment]
In one of my unit test it throws exception with a text from LocaleKeys.mykey and as localization is not loaded in the unit test it gives an error.

**Comment by Overman775** [comment]
@necipk look https://github.com/aissat/easy_localization/blob/develop/test/easy_localization_test.dart

**Comment by FLEURYPiotr** [comment]
I've got a simplest solution

`
...
import 'package:easy_localization/src/translations.dart';
import 'package:easy_localization/src/localization.dart';
...
class TranslationsMock extends Mock implements Translations {}
...
setUpAll(() async {
    final translations = TranslationsMock();
    when(translations.get("my_awesome_key")).thenReturn("Test");
    Localization.load(Locale('en'), translations: translations);
  });
...
test(...)
...
`

@Overman775 it should be great to get this snippet in the plugin documentation in a test part ;-)

**Comment by p0wl90** [comment]
> I've got a simplest solution
> 
> ```
> ...
> 
> import 'package:easy_localization/src/translations.dart';
> 
> import 'package:easy_localization/src/localization.dart';
> 
> ...
> 
> class TranslationsMock extends Mock implements Translations {}
> 
> ...
> 
> setUpAll(() async {
> 
>     final translations = TranslationsMock();
> 
>     when(translations.get("my_awesome_key")).thenReturn("Test");
> 
>     Localization.load(Locale('en'), translations: translations);
> 
>   });
> 
> ...
> 
> test(...)
> 
> ...
> ```
> 
> @Overman775 it should be great to get this snippet in the plugin documentation in a test part ;-)

You should really think about adding this to the README.md since I almost dropped your lib because I could not find a solution at first!

**Comment by Dararii** [comment]
How we can use it without providing any keys?

when(translations.get(any key).thenReturn("Test");

Because adding one by one is insane.

**Comment by sandruschka** [comment]
> How we can use it without providing any keys?
> 
> when(translations.get(any key).thenReturn("Test");
> 
> Because adding one by one is insane.

For my unit tests I needed only a simple solution as to not get errors at compilation time. So I did the following to load my translation file: 

```
 File('assets/translations/en.json').readAsString().then((String contents) {
      Map<String, dynamic> data = jsonDecode(contents);
      Localization.load(Locale('en'), translations: Translations(data));
    });
```

I hope it helps

**Comment by esraa-lotfy5** [comment]
i add file `test/flutter_test_config.dart`

and added this code inside it:
```
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:easy_localization/src/localization.dart';
import 'package:easy_localization/src/translations.dart';
import 'package:flutter/widgets.dart';

Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  final content = await File('assets/lang/sv.json').readAsString(); // <- Or `ru.json`
  final data = jsonDecode(content) as Map<String, dynamic>;

  // easy_localization works with a singleton instance internally. We abuse
  // this fact in tests and just let it load the English translations.
  // Therefore we don't need to deal with any wrapper widgets and
  // waiting/pumping in our widget tests.
  Localization.load(
    const Locale('en'),
    translations: Translations(data),
  );


  await testMain();
}
```
