### ISSUE TITLE
I can't add easy_localization package

### ISSUE THREAD

**Issue by yethael** [aissat/easy_localization#2]
When add "easy_localization: ^1.0.3" or "easy_localization: "1.0.3"" to pubspec.yaml file this is the error I get:

```
[app] flutter packages get
Running "flutter packages get" in logiztik...                   
The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because logiztik depends on easy_localization >=1.0.2+4 which requires SDK version >=2.1.0 <3.0.0, version solving failed.

pub get failed (1)
exit code 1
```

**Comment by Skyost** [comment]
Same problem for me ! Here's my config :

![Config](https://i.imgur.com/53gjVrV.png)

I'm currently using easy_localization v1.0.2 (just to wait).

**Comment by aissat** [comment]
hi @Skyost 
print this `flutter --version `

**Comment by Skyost** [comment]
![Version](https://i.imgur.com/PP3Zaxp.png)

**Comment by wunmansho** [comment]
After making sure that these were correct in pubspec I was able to clean it up with flutter upgrade.  This reinstalled Dart for my project, with the Dart portion technically being a downgrade  in my case.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

**Comment by amrmsccs** [comment]
Facing Same issue here.  Is this package is no longer maintained ?
