### ISSUE TITLE
Can't load json file when build apk

### ISSUE THREAD

**Issue by AmirAhmedDarrag** [aissat/easy_localization#201]
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:lorealegyptshop/services/api_services.dart';
import 'package:lorealegyptshop/wrabber.dart';

void setupLocator() {
  GetIt.I.registerLazySingleton(() => APIServices());
}

void main() {
  setupLocator();
  runApp(
    EasyLocalization(
        supportedLocales: [Locale('en'), Locale('ar')],
        path: 'assets/languages/',
        fallbackLocale: Locale('en'),
        child: MyApp()),
  );
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Wrabber(),
    );
  }
}

**Comment by Overman775** [comment]
@AmirAhmedDarrag please send logs

**Comment by Overman775** [comment]
Closing this since there's no answer
