### ISSUE TITLE
Generate json translation files automatically based on usage of tr in code

### ISSUE THREAD

**Issue by omidraha** [aissat/easy_localization#204]
Hi,

It's possible to generate json translation files automatically based on usage of tr in code?

For example, in `Django` we have this [command](https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-makemessages):

` $ django-admin makemessages -a `

> Runs over the entire source tree of the current directory and pulls out all strings marked for translation. It creates (or updates) a message file in the conf/locale (in the Django tree) or locale (for project and application) directory. After making changes to the messages files you need to compile them with compilemessages for use with the builtin gettext support.

**Comment by Overman775** [comment]
@omidraha No, is not implemented

**Comment by SanjiKir** [comment]
@Overman775 Hey man! Was wondering why is this issue closed? many popular translations libraries support this out of the box like https://github.com/i18next/i18next-parser or http://i18next.github.io/i18next-scanner/

**Comment by spiritinlife** [comment]
@SanjiKir @Overman775 @aissat @omidraha 

I also needed this and created a rough script that can do it with some limitations.
You could check it out here https://gist.github.com/spiritinlife/49a9397768b508ecab929e7d6bbee038.

**Comment by tapionx** [comment]
This is not good. The tool should generate the JSON (or CSV / XML) files automatically, and update them accordingly if i add or delete some strings.
