### ISSUE TITLE
Hot reload doesn't load new translations

### ISSUE THREAD

**Issue by EmmanuelMess** [aissat/easy_localization#208]
If you add translations to json then you have to do a full reload, hot reloads don't seem to add them.

**Comment by Overman775** [comment]
Yep, because Flutter update assets after reboot app

**Comment by EmmanuelMess** [comment]
Why doesn't the system reload the app on hot reload then?

**Comment by konradmietelski** [comment]
@EmmanuelMess Because hot reload is different then hot restart by design. Hot reload suppose to reload widget tree without changing state of anything, like data already provided by user or view user is currently in.
