### ISSUE TITLE
Use default locale string

### ISSUE THREAD

**Issue by VadimZhuk0v** [aissat/easy_localization#211]
Hello.
How can i get string from default locale if i don't have string with asked key in current locale?

**Comment by Overman775** [comment]
@VadimZhuk0v I do not understand you, please detail the question.

You need localized string key from different locale file?

**Comment by VadimZhuk0v** [comment]
For example.
The default app locale is "en".
Also app has "ru" locale, but this locale doesn't have all translations.
If a user runs app in "ru" and faced with untranslated string i must provide string from default locale ("en" on this case)

**Comment by Overman775** [comment]
@VadimZhuk0v not released yet, it's task for future #154

**Comment by 2shrestha22** [comment]
Any update on this? Can we show strings from default locale if key is not available in current locale?

**Comment by heinzan** [comment]
Any update?
