### ISSUE TITLE
On iOS, context.locale is always en, despite devices set to other language?

### ISSUE THREAD

**Issue by herrmayr** [aissat/easy_localization#213]
I'm having an issue whereas I'm not sure where the root of the problem is:
I have localized the app in English and German according to the documentation and examples. The localization does work perfectly on Android devices, but on iOS, on every single device I test, the locale is always "en".
I have added the localizations "English" and "German" in info.plist, but I must be missing something else which I just can't figure out.

Is there some additional step missing in the documentation, or might this be an iOS-related bug?

**Comment by Overman775** [comment]
dublicate #193 #141 
Flutter issue: https://github.com/flutter/flutter/issues/55642

**Comment by Overman775** [comment]
I am closing this issue because there is no response
