### ISSUE TITLE
Unsupported operation: Cannot set value in unmodifiable Map

### ISSUE THREAD

**Issue by pposca** [aissat/easy_localization#215]
Hello, I am getting this weird error when trying to run the app:

[Easy Localization] Start
[Easy Localization] Init state
[Easy Localization] Build
[Easy Localization] Device locale en_US
[Easy Localization] Load asset from assets/translations
[Easy Localization] Init Localization Delegate
[Easy Localization] Init provider
[Easy Localization] Load Localization Delegate
I/flutter ( 5817): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5817): The following UnsupportedError was thrown building MediaQuery(MediaQueryData(size: Size(360.0,
I/flutter ( 5817): 592.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding:
I/flutter ( 5817): EdgeInsets(0.0, 24.0, 0.0, 0.0), viewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets:
I/flutter ( 5817): EdgeInsets.zero, physicalDepth: 1.7976931348623157e+308, alwaysUse24HourFormat: false,
I/flutter ( 5817): accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false,
I/flutter ( 5817): boldText: false)):
I/flutter ( 5817): Unsupported operation: Cannot set value in unmodifiable Map
I/flutter ( 5817): 
I/flutter ( 5817): The relevant error-causing widget was:
I/flutter ( 5817):   MaterialApp
I/flutter ( 5817):   file:///Users/pposca/AndroidStudioProjects/flutter/show_tracker/lib/show_tracker_app.dart:20:16
I/flutter ( 5817): 
I/flutter ( 5817): When the exception was thrown, this was the stack:
I/flutter ( 5817): #0      _ImmutableMap.[]= (dart:core-patch/immutable_map.dart:76:5)
I/flutter ( 5817): #1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
I/flutter ( 5817): #2      loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/utils/date_localizations.dart:43:9)
I/flutter ( 5817): #3      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
I/flutter ( 5817): #4      _ImmutableMap.forEach (dart:core-patch/immutable_map.dart:45:8)
I/flutter ( 5817): #5      CastMap.forEach (dart:_internal/cast.dart:287:13)
I/flutter ( 5817): #6      loadDateIntlDataIfNotLoaded (package:flutter_localizations/src/utils/date_localizations.dart:26:8)
I/flutter ( 5817): #7      _MaterialLocalizationsDelegate.load.<anonymous closure> (package:flutter_localizations/src/material_localizations.dart:607:7)
I/flutter ( 5817): #8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
I/flutter ( 5817): #9      _MaterialLocalizationsDelegate.load (package:flutter_localizations/src/material_localizations.dart:606:32)
I/flutter ( 5817): #10     _loadAll (package:flutter/src/widgets/localizations.dart:58:49)
I/flutter ( 5817): #11     _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:509:62)
I/flutter ( 5817): #12     _LocalizationsState.initState (package:flutter/src/widgets/localizations.dart:474:5)
I/flutter ( 5817): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
I/flutter ( 5817): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter ( 5817): ...     Normal element mounting (108 frames)
I/flutter ( 5817): #122    ObserverElementMixin.mount (package:flutter_mobx/src/observer_widget_mixin.dart:67:11)
I/flutter ( 5817): ...     Normal element mounting (13 frames)
I/flutter ( 5817): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter ( 5817): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
I/flutter ( 5817): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter ( 5817): #138    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter ( 5817): #139    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter ( 5817): #140    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter ( 5817): #141    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter ( 5817): #142    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter ( 5817): #143    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter ( 5817): #144    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter ( 5817): #145    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter ( 5817): #149    _invoke (dart:ui/hooks.dart:261:10)
I/flutter ( 5817): #150    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter ( 5817): (elided 3 frames from dart:async)
I/flutter ( 5817): 
I/flutter ( 5817): ════════════════════════════════════════════════════════════════════════════════════════════════════

The unmodificable Map seems to be dateTimePatterns.

**Comment by pposca** [comment]
It seems the issue was because I had called initializeDateFormatting() before runApp().

Thank you and sorry for the noise.

**Comment by david-macharia** [comment]
@pposca  you help me

**Comment by alanlanglois** [comment]
Same, but this was called by: 
`await Jiffy.locale("fr");`
