### ISSUE TITLE
Issue with using plural

### ISSUE THREAD

**Issue by SimonFM** [aissat/easy_localization#216]
Hi,

We're having an issue with using the plural syntax. I've noticed it doesn't compile it in to the desired `something.one` or `something.other`keys from the example below. We only get errors saying those keys do not exist.

**What does not work:**
`{
    "something" : {
        "one": "This is one of something",
        "other": "There are {} of something"
    }
}`

**What does work:**

`
{
    "something.one" : "This is one of something",
    "something.other" : "There are {} of something" 
}
`

Is this a known issue?

**Comment by Overman775** [comment]
@SimonFM The locale keys has an nested structure, this is not a bug/issue. Check out the JSON examples.

**Comment by SimonFM** [comment]
Hi @Overman775 , 

Thank you for looking at this bug, however, I have an example of the issue code base I am dealing with [here](https://github.com/SimonFM/flutter_sandbox).

Would you be able to take a 5 minute look at it? No matter what I do, I cannot get the .plural method to pick up the correct key/locale. Is the project set up incorrectly or did I miss something based off the docs? 

Example of the crash below:

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyHomePage(dirty, dependencies: [_LocalizationsScope-[GlobalKey#faa1b], _InheritedTheme], state: _MyHomePageState#01d16):
The getter 'languageCode' was called on null.
Receiver: null
Tried calling: languageCode

The relevant error-causing widget was: 
  MyHomePage file://workspaces/flutter_sandbox/lib/main.dart:35:13
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Localization.plural (package:easy_localization/src/localization.dart:66:25)
#2      plural (package:easy_localization/src/public.dart:81:31)
#3      TextTranslateExtension.plural (package:easy_localization/src/public_ext.dart:41:12)
#4      _MyHomePageState.build (package:flutter_sandbox/main.dart:108:15)

```

**Comment by Overman775** [comment]
@SimonFM your language codes wrong, please read readme.

```
void main() {
  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: 
     [Locale('en', 'us'), //<- wrong, need Locale('en', 'US')
     Locale('de', 'de'), //<- wrong, need Locale('de', 'DE')
     Locale('de')],  //<- wrong, noo need because you have Locale('en', 'DE')
    fallbackLocale: Locale('en'), //<- wrong, because you youse 'long' locale name, need Locale('en', 'US')
    path: 'assets/lang/',  //<- wrong, need 'assets/lang' witout latest '/', and rename files like en-US.json, or de-DE.json
  ));
}
```

**Comment by SimonFM** [comment]
Hi @Overman775 ,

I've tried out the suggested code changes, but still no luck, I still get the same error as before with the null language code. I think it is something wrong sometimes after the load of the assets.

`#1      Localization.plural (package:easy_localization/src/localization.dart:66:25)`

Seems to indicate that the localisation isn't initialised, there's no other warning or error logs from the app from start up.

It only fails when I try to use the plural methods, not when i use 'tr()'.

**Comment by Overman775** [comment]
@SimonFM because you missed next step, need add ```localizationsDelegates, supportedLocales, locale``` in MaterialApp widget.

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      home: MyHomePage()
    );
  }
}
```

**Comment by SimonFM** [comment]
@Overman775 thanks so much for your help! 👍 

Silly thing to miss!
