### ISSUE TITLE
Locale Keys Generator Ignores Deeper Level JSON Keys

### ISSUE THREAD

**Issue by nicodumdum** [aissat/easy_localization#217]
Using the sample sample translation file for english.
```json
{
   "msg":"{} are written in the {} language",
   "msg_named":"Easy localization are written in the {lang} language",
   "msg_mixed":"{} are written in the {lang} language",
   "gender":{
      "male":"Hi man ;) {}",
      "female":"Hello girl :) {}",
      "other":"Hello {}"
   }
}
```

Whenever I try to generate locale keys using this terminal command:
`flutter pub run easy_localization:generate -s "assets/translations" -f keys -o locale_keys.g.dart`

The resulting generated locale keys file has some keys missing for deeper level JSON keys in the file.
Specifically, keys for "male", "female", and "other".
```dart
// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

abstract class  LocaleKeys {
  static const msg = 'msg';
  static const msg_named = 'msg_named';
  static const msg_mixed = 'msg_mixed';
  static const gender = 'gender';

}
```

I just thought this might be a bug or is this normal behavior?
I hope you could help me.
Thanks!

**Comment by Overman775** [comment]
@nicodumdum  its all fine, generator don't parse reserved keys for gender, plural, etc.

**Comment by nicodumdum** [comment]
@Overman775 Thanks for the clarification! :)
