### ISSUE TITLE
Migrating from version 2.0.1 to any later version grows Hot Reload time from 500ms to 8s

### ISSUE THREAD

**Issue by craigomac** [aissat/easy_localization#219]
Thanks for the great work on the package.

I'm encountering a very bizarre issue. Recently I noticed that my app hot reload times have felt very sluggish. After some investigation I narrowed it down to the commit where I bumped up the `easy_localization` dependency from 2.0.1 to the latest version.

After some more investigation, I've found that migrating from 2.0.1 to 2.0.2 or any later version causes this massive spike in hot reload times. I presume the cause must be something in this commit: https://github.com/aissat/easy_localization/commit/4e3911d458ee1173b8881c5e0e4d664644aca1c4.

Here's my `flutter doctor` output:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.47.2)
[✓] Connected device (1 available)
```

**Comment by craigomac** [comment]
Hi, has there been any investigation on this? Thanks!

**Comment by Overman775** [comment]
I am closing old issue. If you haven't fixed the problem, feel free to create a new one 😃
