### ISSUE TITLE
Interpolate parameters in CSV file with commas in text content

### ISSUE THREAD

**Issue by ducquynhnguyeninfo** [aissat/easy_localization#221]
I've got a problem trying to inject parameters to the translated text when it having commas inside.

<pre> 
str,en_US,vi_VI 
greet,"Hello, {}","Xin chào, {}"
</pre>

I got only `Hello,` or `Xin chào, ` for the result, as the arg omitted.

**Comment by Overman775** [comment]
@ducquynhnguyeninfo add `\` before commas `"Hello, {}\",\"Xin chào, {}"` or `'Hello, {}","Xin chào, {}'`
