### ISSUE TITLE
Rethrow error caught by the easy_localization plugin

### ISSUE THREAD

**Issue by HugoHeneault** [aissat/easy_localization#223]
We're using firebase to catch flutter errors/crashs. 

But one of our error got caught by your error screen and didn't appear on our screens. 
![image](https://user-images.githubusercontent.com/4112256/88676532-74e14100-d0ec-11ea-9cb2-26f28207ad69.png)

Is it possible that you rethrow the error even after it got caught?

Thanks!

**Comment by Overman775** [comment]
@HugoHeneault  theoretically possible, but not tested )) Write if it helped you
```
            } else if (snapshot.hasError) {
              returnWidget = FutureErrorWidget(msg: snapshot.error);
              throw snapshot.error; <---
            }
```

**Comment by Overman775** [comment]
not actual
