### ISSUE TITLE
The getter 'data' was called on null.

### ISSUE THREAD

**Issue by santiagoalmeidabolannos** [aissat/easy_localization#23]
I do my initial config when I try to run the app I get this problem

`flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building MyApp(dirty):
flutter: The getter 'data' was called on null.
flutter: Receiver: null
flutter: Tried calling: data`

I create a langs folder in the poject root and this is my assets config

`assets:
    - images/
    - langs/es-ES.json
    - langs/en-US.json`

**Comment by woody-worakorn** [comment]
Please check this in main.dart is the same json file path.
..
EasylocaLizationDelegate(locale: data.locale, path: 'resources/langs'),
..

**Comment by amrahmed242** [comment]
@woody-worakorn 
still getting the null exception.
its strange actually !
