### ISSUE TITLE
not supported for web

### ISSUE THREAD

**Issue by ValeriusGC** [aissat/easy_localization#230]
When i do it for mobile devices it works.
When I make `flutter build web` and try to see in russian locale Chrome it does not show `ru` or `ru_RU` locale, just default one.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.142, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.0)
[✓] Connected device (4 available)

```

**Comment by Overman775** [comment]
Hi @ValeriusGC , i rechecked package, all work fine, please check example package in web mode.

![Безымянный](https://user-images.githubusercontent.com/47769319/89707363-a7115f00-d986-11ea-9420-65f729b354d6.png)

**Comment by Overman775** [comment]
@ValeriusGC I am closing issue for lack of response. If you haven't fixed the problem, feel free to create a new one.

**Comment by pulstar** [comment]
this.context.setLocale() is not working for web. No error message appear too.

UPDATE: This way it worked:

```
this.context.resetLocale();
Future.delayed(Duration(milliseconds: 250), () {
    this.context.setLocale(newLocale);
});
```
