### ISSUE TITLE
what is the use of generate command?

### ISSUE THREAD

**Issue by maheshkumar2150** [aissat/easy_localization#233]
First of all

Thank you so much for this wonderful plugin

1. flutter pub run easy_localization:generate --source-dir ./assets/translations
By running this codegen.loader.g.dart file is created. What is the use of this file?

2. If I have en.json file in translations folder, in future if I add few languages is it possible to just copy the json with key and without values for the new languages?

**Comment by Overman775** [comment]
@maheshkumar2150 Its crated locale keys, its very helpfull function for IDE autofill. Nope, you need add all keys
