### ISSUE TITLE
transfer missing translation-keys to all translate-json files

### ISSUE THREAD

**Issue by fehernyul** [aissat/easy_localization#236]
Hi,
How can I do that, I have a big project, and I have already 10+ languages json in my assets/translations directory.
These contains more hundred os translation keys.
When I develop a new feature, which need to be translated about 10-20 new keys, I put the new keys to my default (for example "en.json") translation json file.

How can I do that, the new keys to be transferred to the other json files?
There is a command line key or how?

Thanks, 
Gabor

**Comment by aissat** [comment]
#212
