### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by Xgamefactory** [aissat/easy_localization#24]
getting this error

`AppLocalizations.of(context).tr("offers.total", args: ["$response"])`

```
lang json content
"offers": {
        "total": {
            "zero": "No offers",
            "one": "Total {} offer",
            "other": "Total {} offers"
        }
    }
```

**Comment by pal** [comment]
How was this resolved? I get the same with the following:

`tr('chart_legend_current_period', namedArgs: {'period': 'Period.DAY'}`

```
"chart_legend_previous_period": {
    "Period.DAY": "Last week",
    "Period.WEEK": "Week before",
    "Period.MONTH": "Month before"
  },
```

**Comment by AhmedAbouelkher** [comment]
Same problem, even when not using any translation args at all.

**Comment by DarkMikey** [comment]
~~Please reopen: I'm getting this error inside a `SearchDelegate`. It does work everywhere else. Surprisingly it still works when passed to the parent constructor.~~

I'm so sorry. It was of course a plural which i wanted to translate with `.tr()`. Although the error message makes sense now, I think it could do a better job of leading the developer to the solution. What do you think?
