### ISSUE TITLE
Add easy_localization in a package

### ISSUE THREAD

**Issue by gilthonweapps** [aissat/easy_localization#240]
Hi,

I am using easy_localization in my app and all is working fine.
However, one of the packages my app depends on (internal package) has also translations and I would like to use easy_translation in this package.
How can I configure my main app and package so they both have their own translations?

Here is the configuration of my main app:
```
      EasyLocalization(
        supportedLocales: AppConfig.SUPPORTED_LANG.split(',').map((e) => Locale.fromSubtags(languageCode: e)).toList(),
        path: 'lib/resources/assets/translations',
        useOnlyLangCode: true,
        assetLoader: CodegenLoader(),
        startLocale: Locale(Intl.getCurrentLocale()),
        fallbackLocale: Locale.fromSubtags(languageCode: AppConfig.DEFAULT_LANG),
        child: MyApp(),
      ),
```

All the translations of my main app are inside the `CodegenLoader` class. I would like to do the same for my package.

Regards

**Comment by mmasdivins** [comment]
I have the same situtation did you get a solution?
