### ISSUE TITLE
Release Build Error

### ISSUE THREAD

**Issue by f-hoedl** [aissat/easy_localization#242]
The package works fine on Android on an Emulator with Debug mode.
But if I push it in release mode it just shows the ids.

Versions:
```
  easy_localization: ^2.3.3
  easy_localization_loader: ^0.0.2
```

main.dart
![image](https://user-images.githubusercontent.com/27991923/91641812-35797d80-ea27-11ea-93b7-4217a01d75e6.png)
![image](https://user-images.githubusercontent.com/27991923/91641931-b3d61f80-ea27-11ea-941f-952c950478a6.png)

Usage example:
![image](https://user-images.githubusercontent.com/27991923/91641840-49bd7a80-ea27-11ea-82ae-e411849ec397.png)

Am I missing a configuration or something?

**Comment by Overman775** [comment]
@f-hoedl please show logs

**Comment by f-hoedl** [comment]
> @f-hoedl please show logs

@Overman775 which one and how?

**Comment by Overman775** [comment]
@f-hoedl run in release mode `flutter run --release` and copy log

**Comment by f-hoedl** [comment]
@Overman775 I have tried it and it works fine there. If i release it for internal testing to the play store i am getting the error. Maybe it has smth todo with the appbundle i am creating?

**Comment by Overman775** [comment]
@f-hoedl what error?

**Comment by f-hoedl** [comment]
@Overman775 Not an error exactly,but if i run the downloaded app via playstore it just shows the IDs and not the translatet Value. Is there a way to show you the logs? 


![Screenshot_20200910-064017.jpg](https://user-images.githubusercontent.com/27991923/92682489-c5c19780-f330-11ea-838c-fabfc13791e0.jpg)

**Comment by bw-flagship** [comment]
@f-hoedl Sorry that you did not receive further help here - I assume this issue is not up to date anymore, therefore I close it. If you can still reproduce, please leave a comment.
