### ISSUE TITLE
Use native splashscreen while preloading phase like default MaterialApp

### ISSUE THREAD

**Issue by Nico04** [aissat/easy_localization#243]
Since I use this plugin, I've got a white screen between my native splash screen and my first Flutter page.

Using this code, I can even see the 'blue' and the 'green' flickering (no more white) :

```
runApp(
   EasyLocalization(
      path: 'assets/strings',
      preloaderWidget: Container(color: Colors.blue,),
      preloaderColor: Colors.greenAccent,
      supportedLocales: _supportedLocales,
      fallbackLocale: _supportedLocales.first,
      child: App(),
   ),
);
```

How can I remove theses flickering completly ?

I do some of my initialisations in the main() function, before calling runApp(), which keeps the native splashscreen displayed meanwhile. Why can't easy_localization do the same ? (Without this plugin, the first Flutter page load immadiatly after the native splashscreen.)

(I first posted this issue in[ another issue](https://github.com/aissat/easy_localization/issues/194#issuecomment-678271087), but I've got no response)

**Comment by Overman775** [comment]
@Nico04 try `preloaderWidget: Container(color: Colors.transparent),`

**Comment by Nico04** [comment]
> preloaderWidget: Container(color: Colors.transparent)

This has unfortunately the same effect as not setting `preloaderWidget` : full white screen.

**Comment by Overman775** [comment]
@Nico04 EasyLocalization work asynchronosly, need time to load localization files. Use same color/image from native splash screen

**Comment by Nico04** [comment]
> 
> 
> @Nico04 EasyLocalization work asynchronosly, need time to load localization files. Use same color/image from native splash screen

I understand that it has tasks to do at app opening.
This issue doesn't exist when using MaterialApp default localition system.
We should be able to do this task in the main() function, so that we have a continuous splash screen experience. 
Why can't we separate the loading task from the Widget creation ?

**Comment by Overman775** [comment]
> > @Nico04 EasyLocalization work asynchronosly, need time to load localization files. Use same color/image from native splash screen
> 
> I understand that it has tasks to do at app opening.
> This issue doesn't exist when using MaterialApp default localition system.
> We should be able to do this task in the main() function, so that we have a continuous splash screen experience.
> Why can't we separate the loading task from the Widget creation ?

Because this package is designed that way. In the future, I will probably do or you will help the project by doing PR 😃

**Comment by Aman-Malhotra** [comment]
I am having the same issues and this should be resolved somehow to prevent that split sec gap b/w splash screen and first app screen.
