### ISSUE TITLE
Test localization without EasyLocalization Widget

### ISSUE THREAD

**Issue by Supercaly** [aissat/easy_localization#244]
Hi, in my project I'm writing unit tests for a method that returns a localized string depending on a switch statement.
The method is something like this:
```dart
String enumToString(Enum e) {
 switch(e) {
  case: e.one:
   return 'one'.tr();
  case: e.two:
   return 'two'.tr();
  default:
   return '-';
 }
}
```

How can I unit test this without creating a `testWidget` and pump `EasyLocalization`?

My ideal unit test would be something in the line of:

```dart
test("enum to string test", () {
 String s;
 s = enumToString(Enum.one);
 expect(s, equals("one"));

 s = enumToString(Enum.two);
 expect(s, equals("two"));

 s = enumToString(null);
 expect(s, equals("-"));
});
```

**Comment by Overman775** [comment]
@Supercaly a localization instance is created only in the EasyLocalization widget, there are no other variants for testing, only `testWidget` and pump `EasyLocalization`

**Comment by Lykeosovandara** [comment]
When I pump EastLocalization it may be can't load assets
```dart
The following NoSuchMethodError was thrown building Builder(dirty):
The getter 'supportedLocales' was called on null.
Receiver: null
Tried calling: supportedLocales
```

**Comment by Overman775** [comment]
> When I pump EastLocalization widget it may be can't load assets
> 
> ```dart
> The following NoSuchMethodError was thrown building Builder(dirty):
> The getter 'supportedLocales' was called on null.
> Receiver: null
> Tried calling: supportedLocales
> ```

Use fake loader like in package tests

**Comment by bw-flagship** [comment]
I see this as resolved, as @Overman775 mentioned, you can check out
https://github.com/aissat/easy_localization/blob/develop/test/easy_localization_test.dart
to see how to make unittests
