### ISSUE TITLE
Error "The getter 'languageCode' was called on null" when using plural

### ISSUE THREAD

**Issue by andrew9994** [aissat/easy_localization#245]
Hi, first of all thanks for the great lib!
I just started using it, but unfortunately every time i try to use `.plural()` i get an error, `.tr()` is working fine though.
Error message:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building TestWidget(dirty, dependencies:
flutter: [_EffectiveTickerMode], state: _TestWidgetState#4bc09(tickers: tracking 1 ticker)):
flutter: The getter 'languageCode' was called on null.
flutter: Receiver: null
flutter: Tried calling: languageCode
```

The error happens on the iOS simulator with the latest flutter compiled (`1.20.3`).
Does someone know a fix for this?

**Comment by andrew9994** [comment]
Found solution, forgot to add to `MaterialApp`:
```
localizationsDelegates: context.localizationDelegates,
supportedLocales: context.supportedLocales,
locale: context.locale,
```

**Comment by nytoan** [comment]
Still an error for me when testing a widget using `.plural()`. No error with `.tr()`.
