### ISSUE TITLE
No such method...BuildContextEasyLocalizationExtension.locale

### ISSUE THREAD

**Issue by darrinps** [aissat/easy_localization#247]
When I run the small test program I built using easy_localization I get the following:

The following NoSuchMethodError was thrown building App(dirty):
The getter 'locale' was called on null.
Receiver: null
Tried calling: locale

The relevant error-causing widget was:
  App file:///C:/GitProjects/my-test-app/lib/main.dart:66:14

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      BuildContextEasyLocalizationExtension.locale (package:easy_localization/src/public_ext.dart:88:50)
#2      App.build (package:myapp/main.dart:78:17)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4620:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
...     Normal element mounting (555 frames)

In the pubspec.yaml file I have:
  easy_localization: 2.3.3
  easy_localization_loader: 0.0.2

My relevant code is:

   `  

   import 'package:easy_localization_loader/easy_localization_loader.dart';
   import 'package:easy_localization/easy_localization.dart';

    void run(Environment env, bool enableDebug) {
      runApp(Bootstrap(
        child: Reboot(
          supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
          path: 'assets/translations/langs.csv',
          assetLoader: CsvAssetLoader(),
        child: App(),
      ),
      env: env,
      enableDebug: enableDebug,
    ));
    }

    class App extends StatelessWidget {
     const App({Key key}) : super(key: key);
    @override
     Widget build(BuildContext context) {
    log(context.locale.toString(), name: '${this} # locale Context'); // <---CRASHES HERE
    log('title'.tr().toString(), name: '${this} # locale');
 
    log('Current locale: ${context.locale.toString()}');

    context.locale = Locale('de', 'DE');

    log('New locale: ${context.locale.toString()}');

    var config = context.use<Config>();`

**Comment by Overman775** [comment]
@darrinps show `Reboot` widget

**Comment by darrinps** [comment]
`class Reboot extends StatefulWidget {
  final Widget child;

  Reboot({this.child, List<Locale> supportedLocales, String path, CsvAssetLoader assetLoader});

  @override
  _RebootState createState() => _RebootState();

  static void reboot(BuildContext context) {
    context.findAncestorStateOfType<_RebootState>().restartApp();
  }
}`

**Comment by darrinps** [comment]
Any thoughts?

**Comment by bw-flagship** [comment]
Not enough code to reproduce, I suppose we need to see the Reboot-Widget to investigate. Please comment if the issue persists.
