### ISSUE TITLE
Flickering in dark mode (EASY FIX)

### ISSUE THREAD

**Issue by KirillArtemenko** [aissat/easy_localization#257]
### By default used white color, why?
Container works fine without the color value.
In this case, the scaffold background from the theme will be displayed.

`this.preloaderColor = Colors.white,`

Just remove default color value
`this.preloaderColor,`

**Two problems are solved at once:**
1) no need to manually set the background color to get into the theme
2) no flickering by the default

_Everyone who needs it will still be able to set the color, but it is not entirely clear for what, since there is a Scaffold._

**Comment by aissat** [comment]
check  #267
