### ISSUE TITLE
Emoji is not showing up in pub.dev

### ISSUE THREAD

**Issue by guyluz11** [aissat/easy_localization#258]
All this sentense is not writen well 
`ℹ️ No breaking changes, you can use old the static method EasyLocalization.of(context)`

And the emoji of the ℹ️ isn't showing up in the pub.dev.

It looked to me as if someone forgot to remove the I and it is not capital.
 
![image](https://user-images.githubusercontent.com/9304740/95028186-241b3500-06a7-11eb-97aa-b2f894fb5678.png)

Is this sentence better ?
`If there are no breaking changes you can use the old static method EasyLocalization.of(context)`

**Comment by Overman775** [comment]
Yep, looking beter. Emoji look different on windows and mac platforms. If you have time, please make PR with ℹ️ emoji and text 😉

**Comment by guyluz11** [comment]
You can assign this issue to me, and I have created pull request that you can check.

**Comment by guyluz11** [comment]
Closing this issue as it was fixed 
![image](https://user-images.githubusercontent.com/9304740/103889725-8ee96b80-50ef-11eb-8d75-66b0268f1f7f.png)
