### ISSUE TITLE
How to access to nested data in json

### ISSUE THREAD

**Issue by JaveedIshaq** [aissat/easy_localization#259]
```
{  
  "Information" : {
      "about": "About"
  }

}
```
kindly guide how to access a JSON object value like above

**Comment by JaveedIshaq** [comment]
thanks dear all, i got the solution :) 

`"Information.about".tr()`

**Comment by thorizer** [comment]
@JaveedIshaq this solution works sometimes but sometimes it doesn't 

![gdm_bloc_kmgH1PWGcI](https://user-images.githubusercontent.com/13587810/192772922-af1847f4-0d77-4eab-99a4-3adf4b17542d.png)

it works for sensor_name object but not alerts_msg object, I tried lowercase and it's the same issue
