### ISSUE TITLE
Issue in loading Translation Assets

### ISSUE THREAD

**Issue by AmanStreak** [aissat/easy_localization#260]
When I defined the translation files as en.json then it says Unable to load assets en-US.json... & when I rename the file to en-US.json it says Unable to load en.json... Now I've kept both en.json & en-US.json & it is working fine.

I've done the temporary solution by adding both en.json & en-US.json.

**Comment by Overman775** [comment]
@AmanStreak please show your code

**Comment by stha-ums** [comment]
I had a similar problem, I don't have the solution but the workaround is to create an empty JSON en-US.json then set the localization to another language let's say 'en' using context.locale = Locale('en'); Now you can delete the empty en-US.json.

**Comment by rajeshkumaradam666** [comment]
EasyLocalization(
          supportedLocales: [Locale('en'), Locale('ta')],
          path: 'assets/Transulations/', // <-- remove the last slash  (path: 'assets/Transulations')
          fallbackLocale: Locale('en'),
          child: App()),
    );
to remove the last slash in the path it will worked for me.....

**Comment by danielnordh** [comment]
My problem was the specified 'sub locales'. 
Changing this:
```
supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
fallbackLocale: Locale('en', 'US'),
```

to:
```
supportedLocales: [Locale('en'), Locale('de')],
fallbackLocale: Locale('en'),
```

fixed the problem for me.
