### ISSUE TITLE
How to change locale

### ISSUE THREAD

**Issue by yoseptara** [aissat/easy_localization#264]
Im very confused.

How to change my app texts immediately after I tap the change locale function ("context.locale = Locale()"). 
People said I need to rebuild the app but aissat said that its not needed (https://github.com/aissat/easy_localization/issues/117#issuecomment-608073491)

Code : 
```
void showChangeLanguageBottomSheet() {
    showModalBottomSheet(
      context: context,
      builder: (BuildContext bc) {
        return Container(
          child: DropdownButtonHideUnderline(
            child: ListView.builder(
                shrinkWrap: true,
                itemBuilder: (context, index) => InkWell(
                      onTap: () {
                        EasyLocalization.of(context).locale =
                            kChachaSupportedLanguageList[index];
                        setState(() {});
                        Navigator.pop(context);
                      },
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 20, vertical: 10),
                        child: Text(
                          languageLocalList.getDisplayLanguage(
                              kChachaSupportedLanguageList[index]
                                  .languageCode)['nativeName'],
                          textAlign: TextAlign.left,
                          style: TextStyle(
                              fontFamily: kFontFamilyPoppins,
                              fontWeight: kFontWeightMedium,
                              fontSize: 12,
                              color: Colors.black),
                        ),
                      ),
                    ),
                itemCount: kChachaSupportedLanguageList.length),
          ),
        );
      },
    );
  }
```

Log :
```
Launching lib\main.dart on Edge in debug mode...
Syncing files to device Edge...
Debug service listening on ws://127.0.0.1:3426/lzKs7j7YP70=
Debug service listening on ws://127.0.0.1:3426/lzKs7j7YP70=
error : [firebase_auth/unknown] An unknown error occurred: TypeError: Cannot read property 'isNewUser' of undefined
[Easy Localization] Start
[Easy Localization] Init state
[Easy Localization] Build
[Easy Localization] Device locale en_US
[Easy Localization] Load asset from assets/translations
[Easy Localization] Init Localization Delegate
[Easy Localization] Init provider
[Easy Localization] Load Localization Delegate
Error: PlatformException(idpiframe_initialization_failed, Not a valid origin for the client: http://localhost:3337 has not been whitelisted for client ID 448698001511-5bnrs8glorpdap7huvt3igev0oqq5ijc.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID., https://developers.google.com/identity/sign-in/web/reference#error_codes)


    at Object.createErrorWithStack (http://localhost:3337/dart_sdk.js:4348:12)
    at Object._rethrow (http://localhost:3337/dart_sdk.js:37892:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:3337/dart_sdk.js:37886:13)
    at Object._microtaskLoop (http://localhost:3337/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:3337/dart_sdk.js:37724:13)
    at http://localhost:3337/dart_sdk.js:33243:9[Easy Localization] Locale set id_ID
[Easy Localization] Load asset from assets/translations
[Easy Localization] Locale saved id_ID
[Easy Localization] Init Localization Delegate
[Easy Localization] Init provider
[Easy Localization] Load Localization Delegate

```

Flutter Doctor :
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.21.0-9.2.pre, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.0)
[√] Connected device (3 available)

• No issues found!
```

`

**Comment by MahdiPishguy** [comment]
@yoseptara 

you have an another error on your application, not the library

1)` Cannot read property 'isNewUser' of undefined`

2) `Error: PlatformException(idpiframe_initialization_failed, Not a valid origin for the client: http://localhost:3337 has not been whitelisted for client ID 448698001511-5bnrs8glorpdap7huvt3igev0oqq5ijc.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID., https://developers.google.com/identity/sign-in/web/reference#error_codes)`

**Comment by yoseptara** [comment]
> @yoseptara
> 
> you have an another error on your application, not the library
> 
> 1)` Cannot read property 'isNewUser' of undefined`
> 
> 1. `Error: PlatformException(idpiframe_initialization_failed, Not a valid origin for the client: http://localhost:3337 has not been whitelisted for client ID 448698001511-5bnrs8glorpdap7huvt3igev0oqq5ijc.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID., https://developers.google.com/identity/sign-in/web/reference#error_codes)`

It's not because of that, its a firebase problem that occurs because I was just testing the app and run it with an incorrect port to connect to firebase.

**Comment by Overman775** [comment]
> People said I need to rebuild the app but aissat said that its not needed ([#117 (comment)](https://github.com/aissat/easy_localization/issues/117#issuecomment-608073491))

Yep, EasyLocalization rebuild all app automaticaly. Delete from code `setState(() {});`

**Comment by inamit** [comment]
Any news? I'm trying to let manually changing the app's language but it only changes if I do hard reload/restart the app.

**Comment by emri99** [comment]
@Overman775 

Current view is updated immediatly, but all application tree is not.

*Context:*
I've got a home view, a settings view in which I can set the locale.
On settings view, when i select another current locale, the view is refresh immediately with selected locale => OK
When I go back to my home view, the elements are displayed with previous locale. => KO
Note that if I perform an action that need to rebuild the Home view (in my case a clicking on a BottomNavigationBarItem), the locale is updated correctly immediately on click.

I can't even perform a setState on MaterialApp widget, as the set locale is asynchronous without any control of Future handling, thus the setState is performed before loading new translation is finished and refresh is done with old translations values.

I dig in the source code, but being not familiar with Streams, Sink, etc... I think I understand that this should work but it's not my case.

I may doing something wrong, but I follow exactly your guidelines without success and I'm currently unable to figure out what's going wrong. Can you please help us ;) Thanks

**Comment by emri99** [comment]
Here's a sample of code failing to refresh translations on main page

https://github.com/emri99/nested-navigation-demo-flutter/tree/easy_localization_issue

Context is same:
* an application with bottom navigation bar keeping navigator state for each tab
* a settings page in which translation can be changed

Reproduce steps:
1. Open app, initial locale is EN.
1. go to settings, change locale => the locale is immediately changed in settings view to FR
1. click previous button => the page is displayed with initial EN locale
1. click on another tab => it is refreshed in FR locale

any help/hints would be greatly appreciated
Thanks

**Comment by Overman775** [comment]
@emri99  #238

**Comment by emri99** [comment]
Thanks @Overman775. However it doesn't work.
Sorry my previous explanations wasn't clear, I edit previous post to state that going to settings is the settings inside app, not system settings.
And as I understand, the `didChangeLocales` is executed when System locales are changed, so this is never executed in my case where locale is changed inside the application

**Comment by Overman775** [comment]
@emri99 i can't run code example in https://github.com/emri99/nested-navigation-demo-flutter/tree/easy_localization_issue
if it's issue has actual, please rechech your git 😉

**Comment by yoseptara** [comment]
My issue occured because I put the translation keys and .tr functions into another file (It was created to make me easier to check whether a key is already created or not). So this file is similiar to a constant file where I assign every key and the .tr function into variable.

And my issue was solved after revert my code and put the 'key'.tr inside build method.
