### ISSUE TITLE
loading languages from sub directories fail

### ISSUE THREAD

**Issue by MahdiPishguy** [aissat/easy_localization#266]
how can i separate language by code into own directories?

for example:

```
- assets/translations/en/
- assets/translations/ar/
- assets/translations/az/
```

when i making this sub directories and define into `pubspec.yml` doing above says, the library can't found files from them and i get an error

> Load asset from assets/translations
> Unable to load asset: assets/translations/en-US.json

thats work fine when i dont put them into sub directories

**Comment by Overman775** [comment]
> how can i separate language by code into own directories?
@MahdiPishguy Nope, only in single directory
