### ISSUE TITLE
Second and further widget test fail

### ISSUE THREAD

**Issue by Surio89** [aissat/easy_localization#268]
Hi,

i reproduced this error with the default flutter app. I add the plugin as described and everything works as expected but my widget tests make some problems. My App look likes this:

``` dart
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    EasyLocalization(
        supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
        path: 'assets/translations', // <-- change patch to your
        fallbackLocale: Locale('en', 'US'),
        child: MyApp()
    ),
  );
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('translate').tr(),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

my test looks like this:
``` dart
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:easy_localization_test/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(EasyLocalization(
        startLocale: const Locale('de', 'DE'),
        supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
        path: 'assets/translations',
        fallbackLocale: Locale('en', 'US'),
        saveLocale: false,
        child: MyApp()));

    await tester.pumpAndSettle();

    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);
  });

  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(EasyLocalization(
        startLocale: const Locale('de', 'DE'),
        supportedLocales: [Locale('en', 'US'), Locale('de', 'DE')],
        path: 'assets/translations',
        fallbackLocale: Locale('en', 'US'),
        saveLocale: false,
        child: MyApp()));

    await tester.pumpAndSettle();

    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);
  });
}

```

the first test is successful but the second and any further test fails. Both are exactly the same test. What am i doing wrong here? No error message only a message that `expect(find.text('0'), findsOneWidget);` fails

If i run this test inside an emulator everything works (flutter run).

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18362.1139], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.46.0)
[√] Connected device (1 available)
    ! Device emulator-5554 is offline.

• No issues found!

**Comment by Surio89** [comment]
https://github.com/aissat/easy_localization/issues/155#issuecomment-621884864
did not help

**Comment by nytoan** [comment]
You need to encapsulate your pumpWidget & pumpAndSettle in runAsync. 

```
await tester.runAsync(() async {
    await tester.pumpWidget(...);
    await tester.idle();
    await tester.pumpAndSettle();
});
```

**Comment by Surio89** [comment]
works - thank you

**Comment by Overman775** [comment]
@nytoan thanks for help 😃

**Comment by mvarendorff** [comment]
@nytoan Out of curiosity: Why? It does work indeed but [the docs](https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html) explicitly state (emphasis mine):

> Consider restructuring your code so you do **not need runAsync. This is the optimal solution** as widget tests are designed to run in fake async environment.

If there is a good reason why this is needed, I am all for it but without an explanation, this it only looks like a workaround for (imo) clearly unexpected behaviour.

**Comment by biscottis** [comment]
> @nytoan Out of curiosity: Why? It does work indeed but [the docs](https://api.flutter.dev/flutter/flutter_test/WidgetTester/runAsync.html) explicitly state (emphasis mine):
> 
> > Consider restructuring your code so you do **not need runAsync. This is the optimal solution** as widget tests are designed to run in fake async environment.
> 
> If there is a good reason why this is needed, I am all for it but without an explanation, this it only looks like a workaround for (imo) clearly unexpected behaviour.

Agreed, are there plans to not have this workaround?

**Comment by mvarendorff** [comment]
Quick update because I was notified about this thread again. What appeared to work in the tests was specifying the generated CodegenLoader as assetLoader, at least I believe that was what solved it:
```dart
EasyLocalization(
  supportedLocales: const [Locales.de, Locales.en],
  path: 'assets/translations',
  fallbackLocale: Locales.de,
  assetLoader: const CodegenLoader(),
  child: const Text('Put your actual child here :)'),
)
```

We have switched to [fast_i18n](https://pub.dev/packages/fast_i18n) by now it has not caused any issues in testing so far (but as said, neither did the CodegenLoader).

**Comment by Abdelazeem777** [comment]
After 8 hours of tracing every line of code on the package and going through the Localization Widget as well
I figured out that the issue was with the `rootBundle` that cache need to get cleared

So, I fix it by clearing the cache after each test like this:

```dart
  tearDown(() {
    rootBundle.clear();
  });
```
