### ISSUE TITLE
App instance created after Android FlutterActivity starts

### ISSUE THREAD

**Issue by altush1983** [aissat/easy_localization#269]
In the current version of easy_localization, the app (child property of the EasyLocalization object - usually is MyApp object) is only created after the Android activity is starts. This behavior interferes with the case when the flutter module is used with a pre-warm engine. The usual flutter holding in this case is "If your Dart entrypoint invokes runApp() to run a Flutter app, then your Flutter app behaves as if it were running in a window of zero size until this FlutterEngine is attached to a FlutterActivity, FlutterFragment, or FlutterView." as described in https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen
Can I start MyApp instance without delay the same as in the runApp behavior?

**Comment by Overman775** [comment]
@altush1983 Nope, but its planet on next big release
