### ISSUE TITLE
Doesnt works with web

### ISSUE THREAD

**Issue by imerkle** [aissat/easy_localization#27]
There is no proper error in console but removing this block runs as expected

```
          home: MyHomePage(title: 'Home'),
          localizationsDelegates: [
            // removing this block i can run 
            EasylocaLizationDelegate(
              locale: data.locale ?? Locale('en', 'US'),
              path: 'lang'
            ),
            // block ends
            GlobalMaterialLocalizations.delegate,
          ],
```

**Comment by spiritinlife** [comment]
@aissat it shouldn't be hard to add web support i believe all our dependencies support web also.

**Comment by aissat** [comment]
@spiritinlife I'll dot in no time

**Comment by aissat** [comment]
@spiritinlife @imerkle it's working well
<img width="962" alt="Screen Shot 2020-02-28 at 5 17 34 PM" src="https://user-images.githubusercontent.com/4768203/75566045-5993dc00-5a4f-11ea-8d52-9742f5928f32.png">
<img width="969" alt="Screen Shot 2020-02-28 at 5 17 47 PM" src="https://user-images.githubusercontent.com/4768203/75566060-61ec1700-5a4f-11ea-9979-5884fcac07d3.png">
