### ISSUE TITLE
FormatException: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by minhduc1827** [aissat/easy_localization#270]
When i deployed flutter web on firebase, it thows the exception "FormatException: SyntaxError: Unexpected token < in JSON at position 0"

**Comment by Overman775** [comment]
@minhduc1827 problen in your json file

**Comment by Overman775** [comment]
If you haven't fixed the problem, feel free to create a new one or reopen this issue 😃
