### ISSUE TITLE
The getter 'outStreamR' isn't defined for the class '_EasyLocalizationBloc'.

### ISSUE THREAD

**Issue by CodeBot1601** [aissat/easy_localization#271]
C:/flutter/.pub-cache/hosted/pub.dartlang.org/easy_localization-2.3.3/lib/src/easy_localization_app.dart:205:24: Error: The getter 'outStreamR' isn't defined for the class '_EasyLocalizationBloc'.
 - '_EasyLocalizationBloc' is from 'package:easy_localization/src/easy_localization_app.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/easy_localization-2.3.3/lib/src/easy_localization_app.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'outStreamR'.
          stream: bloc.outStreamR,
                       ^^^^^^^^^^

i Am using EasyLocalization with Cubit and Bloc state managment and this error is not letting me build my app.

**Comment by Overman775** [comment]
@CodeBot1601 This package use BloC pattern, but not Cubit or Bloc from Felix
