### ISSUE TITLE
Can't do a widget test

### ISSUE THREAD

**Issue by nytoan** [aissat/easy_localization#274]
Hi guys, I try to make a widget test with easy_localization but i can't make it work.

**Here is a simple widget test :**

_ ✅ working test : _

```
testWidgets('test', (WidgetTester tester) async {
    Widget widget = MaterialApp(
      home: Text('text'),
    );
    await tester.pumpWidget(widget);
    await tester.pumpAndSettle();
    expect(find.text('text'), findsOneWidget);
  });
```

_ 🚫 Not working test :_

```
testWidgets('test', (WidgetTester tester) async {
    Widget widget = MaterialApp(
      home: EasyLocalization(
        supportedLocales: [Locale('en')],
        path: 'assets/i18n',
        child: Text('text'),
      ),
    );
    await tester.pumpWidget(widget);
    await tester.pumpAndSettle();
    expect(find.text('text'), findsOneWidget);
  });
```

**The logs show :**

[Easy Localization] Start
[Easy Localization] Init state
[Easy Localization] Build
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "text" (ignoring offstage widgets)>
   Which: means none were found but one was expected
...

I don't know why it stop at the "Build" log and no continue. 
I tested a lot of thing, made a custom assets loader, etc..

Anybody could make a successful test ?

Thanks for your help.

**Comment by nytoan** [comment]
I found the solution, i needed to add this line in the main() before any tests.

`SharedPreferences.setMockInitialValues({});`

**Comment by wwwdata** [comment]
I was also stumbling upon this problem. But I found an even hackier solution. While reading the source code to understand how the internals of this plugin work I discovered that the loaded translations are basically stored inside a singleton instance. We can abuse this fact to just prefill them with the english ones, then you will not need a wrapper widget in flutter widget tests. I solved this by writing the following into my `flutter_test_config.dart`

```dart
import 'dart:async';

import 'package:easy_localization/src/localization.dart';
import 'package:easy_localization/src/translations.dart';
import 'package:your_package/generated/codegen_loader.g.dart';
import 'package:flutter/widgets.dart';

Future<void> main(FutureOr<void> Function() testMain) async {
  // easy_localization works with a singleton instance internally. We abuse
  // this fact in tests and just let it load the english translations.
  // Therefore we don't need to deal with any wrapper widgets and
  // waiting/pumping in our widget tests.
  Localization.load(
    const Locale('en'),
    translations: Translations(CodegenLoader.en),
  );

  await testMain();
}
```

In my opinion, it would be worth it to maybe make a proper public method that allows us to just prefill translations for widget tests? Why not?

**Comment by ValentinVignalNovade** [comment]
In the end, I fixed it by adding a file `test/flutter_test_config.dart`. I got the inspiration from [this issue](https://github.com/aissat/easy_localization/issues/274#issuecomment-760167564).

```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:easy_localization/src/localization.dart';
import 'package:easy_localization/src/translations.dart';
import 'package:flutter/widgets.dart';

Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  final content = await File('assets/lang/sv.json').readAsString(); // <- Or `ru.json`
  final data = jsonDecode(content) as Map<String, dynamic>;

  // easy_localization works with a singleton instance internally. We abuse
  // this fact in tests and just let it load the English translations.
  // Therefore we don't need to deal with any wrapper widgets and
  // waiting/pumping in our widget tests.
  Localization.load(
    const Locale('en'),
    translations: Translations(data),
  );


  await testMain();
}
```

**Comment by Abdelazeem777** [comment]
Add this!

```dart
  tearDown(() {
    rootBundle.clear();
  });
```
