### ISSUE TITLE
Version solving failed after upgrading to Flutter 1.24.0-8.0

### ISSUE THREAD

**Issue by Jerrywyx** [aissat/easy_localization#275]
After upgrading to Flutter 1.24.0-8.0, I got below error message from ```Pub get```

```
Because no versions of easy_localization match >2.3.3 <3.0.0 and easy_localization 2.3.3 depends on intl ^0.16.0, easy_localization ^2.3.3 requires intl ^0.16.0.
And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, easy_localization ^2.3.3 is incompatible with flutter_localizations from sdk.
So, because revox_studioart depends on both flutter_localizations any from sdk and easy_localization ^2.3.3, version solving failed.
pub get failed (1; So, because revox_studioart depends on both flutter_localizations any from sdk and easy_localization ^2.3.3, version solving failed.)
```

Sounds like we need to update the dependencies of easy_localization.

PS: here's my flutter version,
```
Flutter 1.24.0-8.0.pre.230 • channel master •
https://github.com/flutter/flutter.git
Framework • revision af5eb3b987 (61 minutes ago) • 2020-11-13 19:57:15 +0800
Engine • revision dddb532b5c
Tools • Dart 2.12.0 (build 2.12.0-37.0.dev)
```

**Comment by Supercaly** [comment]
I think an easy fix would be changing `intl` dependency in `pubspec.yaml` to 0.17.0-nullsafety.2
Keep in mind that there's a breaking change in version [0.17.0-nullsafety](https://pub.dev/packages/intl/versions/0.17.0-nullsafety.2/changelog#0170-nullsafety) that can cause problems and that the [flutter's SDK constraints have been updated](https://pub.dev/packages/intl/versions/0.17.0-nullsafety.2/changelog#0170-nullsafety)

**Comment by egeysn** [comment]
i forked the project then i updated the value of intl package as "intl: ">=0.16.0 <=0.17.0-nullsafety.2" in pubspec.yaml. After the changes, i used the easy_localization package which i forked in my project. Now it's working fine
easy_localization:
    git: https://github.com/egeysn/easy_localization_
Now it's working fine

**Comment by Jerrywyx** [comment]
> i forked the project then i updated the value of intl package as "intl: ">=0.16.0 <=0.17.0-nullsafety.2" in pubspec.yaml. After the changes, i used the easy_localization package which i forked in my project. Now it's working fine
> easy_localization:
> git: https://github.com/egeysn/easy_localization
> Now it's working fine

Thanks, could you issue a PR for this.

**Comment by aissat** [comment]
@Jerrywyx  check this  #275

**Comment by Justice-Mensah** [comment]
I Think the best way to solve this  is to switch your flutter channel to a stable version, try running
' flutter channel stable '  in the command line
this will switch your channel to a stable version to be able to get rid of the errors
I hope this solves your issue

**Comment by palanurag23** [comment]
just update all your packages not compatible
