### ISSUE TITLE
Option to suppress 'Localization key not found' warning

### ISSUE THREAD

**Issue by xJon** [aissat/easy_localization#277]
Trying to use `.tr()` inside a `try-catch` block will still throw this warning. Is there any way to suppress it?
Thank you!

**Comment by Overman775** [comment]
@xJon Nope, need context for localization. You can try "prepared" strings like argument in to bloc

**Comment by xJon** [comment]
I see. Can you please provide more details regarding what you suggested I could try?

**Comment by Overman775** [comment]
`SameBloc(name: sameName.tr())`

**Comment by Overman775** [comment]
I am closing issue for lack of response. If you haven't fixed the problem, feel free to create a new one 😃
