### ISSUE TITLE
Add support for linked locale messages

### ISSUE THREAD

**Issue by HatEmU** [aissat/easy_localization#279]
My company is using vue-i18n as part of their web project for the front-end and it has a very nice way of [linking translations](https://kazupon.github.io/vue-i18n/guide/messages.html#linked-locale-messages). I looked around in the example projects here and fiddled a little with a side project and I found out that it doesn't work in easy_localization unless I do some hacky nesting... If you could add support for this feature you would save me about 90 KB and a lot of headache 😂

**Comment by HatEmU** [comment]
Alright, I decided to give it a shot! I'll make a PR when I'm done.

**Comment by aissat** [comment]
hi @HatEmU thank you,  look like a good issue
@Overman775  plz check this
