### ISSUE TITLE
setState() callback argument returned a Future

### ISSUE THREAD

**Issue by nogicoder** [aissat/easy_localization#28]
Hi when I call data.changeLocale inside setState function in a Button, this exception come up:
```
I/flutter (26143): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (26143): The following assertion was thrown while handling a gesture:
I/flutter (26143): setState() callback argument returned a Future.
I/flutter (26143): The setState() method on _BasePageState#59c46 was called with a closure or method that returned a
I/flutter (26143): Future. Maybe it is marked as "async".
I/flutter (26143): Instead of performing asynchronous work inside a call to setState(), first execute the work (without
I/flutter (26143): updating the widget state), and then synchronously update the state inside a call to setState().
I/flutter (26143):
I/flutter (26143): When the exception was thrown, this was the stack:
I/flutter (26143): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1144:9)
I/flutter (26143): #1      State.setState (package:flutter/src/widgets/framework.dart:1160:6)
I/flutter (26143): #2      _BasePageState._showLanguagesDialog.<anonymous closure>.<anonymous closure> (package:ciloapp/pages/base/base.dart:101:28)
I/flutter (26143): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
I/flutter (26143): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
I/flutter (26143): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (26143): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
I/flutter (26143): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
I/flutter (26143): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
I/flutter (26143): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
I/flutter (26143): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
I/flutter (26143): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (26143): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (26143): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (26143): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (26143): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (26143): #19     _invoke1 (dart:ui/hooks.dart:263:10)
I/flutter (26143): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
I/flutter (26143): (elided 3 frames from package dart:async)
I/flutter (26143):
I/flutter (26143): Handler: "onTap"
I/flutter (26143): Recognizer:
I/flutter (26143):   TapGestureRecognizer#3af55
I/flutter (26143): ═══════════════════════════════════════════════════════════════════
```

**Comment by spiritinlife** [comment]
@nogicoder Could you share an example reproducing this issue?

**Comment by Mayank0022** [comment]
@spiritinlife 
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'coin_data.dart';
import 'dart:io' show Platform;

class PriceScreen extends StatefulWidget {
  @override
  _PriceScreenState createState() => _PriceScreenState();
}

class _PriceScreenState extends State<PriceScreen> {
  String selectedCurrency = 'USD';

  String bitcoinValueInUSD = '?';

  //11. Create an async method here await the coin data from coin_data.dart
  Future<void> getData() async {
    try {
      double data = await CoinData().getCoinData(selectedCurrency);
      //13. We can't await in a setState(). So you have to separate it out into two steps.
      setState(() {
        bitcoinValueInUSD = data.toStringAsFixed(0);
      });
    } catch (e) {
      print(e);
    }
  }

  @override
  void initState() {
    super.initState();
    //14. Call getData() when the screen loads up. We can't call CoinData().getCoinData() directly here because we can't make initState() async.
    getData();
  }

  DropdownButton<String> androidButton() {
    List<DropdownMenuItem<String>> dropdownItems = [];
    for (String currency in currenciesList) {
      var newItem = DropdownMenuItem(
        child: Text(currency),
        value: currency,
      );
      dropdownItems.add(newItem);
    }
    return DropdownButton<String>(
      value: selectedCurrency,
      items: dropdownItems,
      onChanged: (value) {
        setState(() async {
          await getData();
          selectedCurrency = value;
        });
      },
    );
  }

  CupertinoPicker iosButton() {
    List<Text> dropdownText = [];
    for (String currency in currenciesList) {
      var textItem = Text(currency);
      dropdownText.add(textItem);
    }
    return CupertinoPicker(
      backgroundColor: Colors.lightBlue,
      itemExtent: 36.0,
      onSelectedItemChanged: (selectedIndex) {
        setState(() async {
          await getData();
          selectedCurrency = currenciesList[selectedIndex];
        });
      },
      children: dropdownText,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('🤑 Coin Ticker'),
        //centerTitle: true,
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Padding(
            padding: EdgeInsets.fromLTRB(18.0, 18.0, 18.0, 0),
            child: Card(
              color: Colors.lightBlueAccent,
              elevation: 5.0,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10.0),
              ),
              child: Padding(
                padding: EdgeInsets.symmetric(vertical: 15.0, horizontal: 28.0),
                child: Text(
                  '1 BTC = $bitcoinValueInUSD $selectedCurrency',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 20.0,
                    color: Colors.white,
                  ),
                ),
              ),
            ),
          ),
          Container(
            height: 150.0,
            alignment: Alignment.center,
            padding: EdgeInsets.only(bottom: 30.0),
            color: Colors.lightBlue,
            child: Platform.isIOS ? androidButton() : iosButton(),
          ),
        ],
      ),
    );
  }
}
  
this is also a code producing the same exception can u help me in sorting it out

**Comment by spiritinlife** [comment]
@Mayank0022 that does not seem related to this package, are you using easy_localiztion in your project?

But since you are here you should probably refactor this

```
setState(() async {
    await getData();
    selectedCurrency = currenciesList[selectedIndex];
});
```

to 

```
await getData();
setState(() {
    selectedCurrency = currenciesList[selectedIndex];
});
```

**Comment by SachinPremkumar** [comment]
I am also facing the same issue.
E/flutter (26531): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: setState() callback argument returned a Future.
E/flutter (26531): The setState() method on _PaymentScreenState#3c581 was called with a closure or method that returned a Future. Maybe it is marked as "async".
E/flutter (26531): Instead of performing asynchronous work inside a call to setState(), first execute the work (without updating the widget state), and then synchronously update the state inside a call to setState().
E/flutter (26531): #0      _PaymentScreenState.Orderfood (package:PVCBazaar/screens/payment_screen.dart:405:7)
E/flutter (26531): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (26531): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (26531): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (26531): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (26531): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (26531): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (26531): #7      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (26531): #8      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)

**Comment by HappySinha** [comment]
> @Mayank0022 that does not seem related to this package, are you using easy_localiztion in your project?
> 
> But since you are here you should probably refactor this
> 
> ```
> setState(() async {
>     await getData();
>     selectedCurrency = currenciesList[selectedIndex];
> });
> ```
> 
> to
> 
> ```
> await getData();
> setState(() {
>     selectedCurrency = currenciesList[selectedIndex];
> });
> ```
> 
> Also better post this question to StackOverflow

Thank You so much this is worked in my issue

**Comment by SmitGhori03** [comment]
setState() callback argument returned a Future.

`Text(
                            'Confirm Password',
                            style: kRegistrationFieldText,
                          ),
                          Padding(
                            padding: EdgeInsets.only(top: 4.sp, bottom: 6.sp),
                            child: Container(
                              child: TextFormField(
                                validator: (value) {

                                    if (value!.isEmpty) {
                                      return 'password doesn\'t empty';
                                    }

                                },
                                keyboardType: TextInputType.emailAddress,
                                textAlign: TextAlign.start,
                                onChanged: (value) {
                                  cPassword = value;
                                },
                                decoration: kTextFieldDecoration.copyWith(
                                    hintText: ' Confirm Password'),
                                style: TextStyle(color: Colors.black),
                              ),
                            ),
                          ),
                          
                          
                          
                          
                          answer this error

**Comment by darshan9954** [comment]
But since you are here you should probably refactor this

setState(() async {
    await getData();
    selectedCurrency = currenciesList[selectedIndex];
});
to

await getData();
setState(() {
    selectedCurrency = currenciesList[selectedIndex];
});
Also better post this question to StackOverflow

**Comment by Jay-2119** [comment]
Thank you so much..!! issue resolved

**Comment by ricky-blip** [comment]
Thanks, all of you guys.
