### ISSUE TITLE
context.locale.countryCode is always null?

### ISSUE THREAD

**Issue by xJon** [aissat/easy_localization#283]
When the package initializes it seems to print in console both language and country codes, but when I request `context.locale` it only prints the language code, and when I request `context.locale.countryCode` I get `null`.
Any idea why? I tried multiple emulators and nothing worked.
Thank you!

**Comment by Overman775** [comment]
@xJon Hi, show your code

**Comment by xJon** [comment]
```dart
void main() => runApp(MyLocalizedApp());

class MyLocalizedApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => EasyLocalization(
        child: MyApp(),
        supportedLocales: [Locale('en')],
        fallbackLocale: Locale('en'),
        path: 'assets/languages',
      );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print(context.locale.countryCode);
    
    ...
}
```
No matter where I request `context.locale.countryCode` it always seems to be null, even though when the package initializes it prints onto the console `en_US`.

**Comment by Overman775** [comment]
@xJon you dont have countryCode because you use only language code ` Locale('en')`.

**Comment by Overman775** [comment]
@xJon initiliazed 'en_US' in log show your device locale

**Comment by Overman775** [comment]
@xJon read readme file, and use `useOnlyLangCode: true`

**Comment by xJon** [comment]
@Overman775 Sorry, I didn't notice that parameter! I've set it now with `useOnlyLangCode: true,` yet unfortunately I still only receive `null` from `context.locale.countryCode`.

**Comment by Overman775** [comment]
https://github.com/aissat/easy_localization/issues/283#issuecomment-735361378

**Comment by xJon** [comment]
I see, thank you for the help!
