### ISSUE TITLE
Localization not working for some languanges

### ISSUE THREAD

**Issue by asafvaron90** [aissat/easy_localization#284]
Hi Guys!

Love your library!
I have added Spanish as the first localization and it worked great!

Now I have added a few more and they are not working.. any idea what can be causing this issue?

Locales added: hi (Hindi), ru (Russian), pt (Portuguese)

I get the following error when switching to any of them:

`W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
I/flutter (25488): Instance of 'Prefs', k_last_locale: save success: true
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
I/flutter (25488): 2020-11-27T10:49:51.714417	D	FirestoreController._initDeviceListener.<ac>:	 _aDeviceChangesStream: {date: 11/27/2020, device_name: MI 8 Pro, plan_type: PlanType.Junior, device_id: 01f025cea8d82f17, locale: Hindi, timestamp: 1606466759710}
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
I/flutter (25488): [34m[WARNING] Easy Localization: Localization key [Learn] not found[0m
I/flutter (25488): [34m[WARNING] Easy Localization: Localization key [Play] not found[0m
I/flutter (25488): [34m[WARNING] Easy Localization: Localization key [Menu] not found[0m
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
I/flutter (25488): 2020-11-27T10:49:52.123196	D	FirestoreController.updateDeviceLocale:	 updateDeviceLocale success
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
I/chatty  (25488): uid=10549(com.alefapps.learn_english_kids) FirestoreWorker identical 1 line
W/rn_english_kid(25488): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)`

Best regards,
Asaf

**Comment by Overman775** [comment]
in your log : 'Easy Localization: Localization key [Learn] not found'

**Comment by Overman775** [comment]
add missed locale keys

**Comment by asafvaron90** [comment]
You mean I needt i add it to the json file?

**Comment by asafvaron90** [comment]
BTW... all the translation JSON files are the same keys.. working for English and Spanish... but not for other languages.

**Comment by Overman775** [comment]
@asafvaron90 show file names

**Comment by asafvaron90** [comment]
<img width="135" alt="Screen Shot 2020-11-29 at 16 36 48" src="https://user-images.githubusercontent.com/7665436/100544818-15916a00-3261-11eb-8786-b6a90c14d1f3.png">

**Comment by asafvaron90** [comment]
` EasyLocalization(
        path: AppLocales.localesPath,
        supportedLocales: AppLocales.supportedLocales,
        fallbackLocale: AppLocales.fallbackLocale,
        useOnlyLangCode: true,
        child: MyApp(),
      ),
`

**Comment by Overman775** [comment]
@asafvaron90 looking normal, need se project to help

**Comment by asafvaron90** [comment]
How u wanna do it?

**Comment by Overman775** [comment]
@asafvaron90 send link to your project

**Comment by asafvaron90** [comment]
Whats the email you uae for permissions?

**Comment by Overman775** [comment]
@asafvaron90 invite by my user name `Overman775`

**Comment by asafvaron90** [comment]
I have the project on bitbucket... can this work?

**Comment by asafvaron90** [comment]
I need your email in order to give you access to the project

**Comment by asafvaron90** [comment]
Hi Alexey, I invited you to collaborate on a sample project I created which has the same error

I have created a class "AppLocales" you can enable and disable locales there.. English and Spanish are working.. I have turned on Hindi and then I get some errors.

Please let me know if you find anything.

Thanks for the help

**Comment by asafvaron90** [comment]
@Overman775 Hey Alexey any updates on this issue?

**Comment by Overman775** [comment]
@asafvaron90 Hi. sorry, i not have enouth time to help you
I think problem in files. Validate your json, add all locale keys
If bug not gone try replace file to worked locales and edit them

**Comment by asafvaron90** [comment]
there was an issue in my code.
Problem was fixed.
