### ISSUE TITLE
easy_localization ^2.3.3 and intl ^0.16.1, version solving failed

### ISSUE THREAD

**Issue by pbeccegato** [aissat/easy_localization#288]
After the last flutter upgrade, I've got this error:

_Because easy_localization >=2.1.0+1 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, easy_localization >=2.1.0+1 requires intl 0.17.0-nullsafety.2.
So, because MyProject depends on both easy_localization ^2.3.3 and intl ^0.16.1, version solving failed.
pub get failed (1; So, because MyProject depends on both easy_localization ^2.3.3 and intl ^0.16.1, version solving failed.)_

This is a part of my pubspec.yaml

_dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  provider: ^4.0.0
  shared_preferences: ^0.5.7+3
  flutter_date_pickers: ^0.1.0
  easy_localization: ^2.3.3
  easy_localization_loader: ^0.0.2
  websafe_platform: ^1.0.2
  country_icons: ^1.1.1
  font_awesome_flutter: ^8.8.1
  device_info: ^0.4.2+4
  rename: ^1.2.0
  js: ^0.6.2
  intl: ^0.16.1
  chips_choice: ^1.2.0
  dio: ^3.0.10
  syncfusion_flutter_datepicker: ^18.3.52-beta
  syncfusion_flutter_datagrid: ^18.3.52-beta_

Thanks in advance
Peter

**Comment by pbeccegato** [comment]
Solved changing flutter channel from master to stable

**Comment by aissat** [comment]
@pbeccegato  check `easy_localization: ^2.3.4-nullsafety.1`
