### ISSUE TITLE
NG.json Missing

### ISSUE THREAD

**Issue by stonekase** [aissat/easy_localization#289]
Hi there,

I am experiencing NG.json missing using my default Android emulator while setting fallback locale to en. I live in Nigeria and for some reason it doesn't fallback to Locale("en","US").
I did not explicitly set Locale to Locale("en","NG") but was pick on emulator from location automatically.

<img width="388" alt="Screenshot 2020-12-03 at 04 24 37" src="https://user-images.githubusercontent.com/5037778/100960119-efe5b880-351f-11eb-9cd2-34b3fcfc5f4d.png">

**Comment by aissat** [comment]
@stonekase check path in `pubsepc.yaml`

**Comment by stonekase** [comment]
everything is set correctly 
<img width="381" alt="Screenshot 2020-12-09 at 20 57 38" src="https://user-images.githubusercontent.com/5037778/101680647-46dc1800-3a61-11eb-929a-7c6cd4492402.png">

I had to ad a NG.json to my locale and translation folder to stop the error but I don't want to cater for NG.json.
<img width="243" alt="Screenshot 2020-12-09 at 21 00 36" src="https://user-images.githubusercontent.com/5037778/101681066-e6010f80-3a61-11eb-922b-d6f924d2468c.png">

<img width="372" alt="Screenshot 2020-12-09 at 21 00 54" src="https://user-images.githubusercontent.com/5037778/101681096-f0bba480-3a61-11eb-9463-fa537b443a62.png">

**Comment by aissat** [comment]
@stonekase here is no `en-NG.json` file
