### ISSUE TITLE
How to change locale and reload all screens?

### ISSUE THREAD

**Issue by MRSEREY** [aissat/easy_localization#292]
I use context.locale = languageCode, but it change only on active screen.

Is there any solutions to change and reload all screen?

**Comment by aissat** [comment]
@MRSEREY need example

**Comment by MRSEREY** [comment]
In my app, I have settings screen which contains change language screen. When user click to change language I set this: context.locale = languageCode (depends on user clicked). It did trigger the language delegate in my main.dart. However, It didn't change language in the whole app unless I hot restart it.

**Comment by aissat** [comment]
@MRSEREY  try use `context` with `tr()` once time each screen
