### ISSUE TITLE
How to get the value of context.localizationDelegates in lower version 2.1.0

### ISSUE THREAD

**Issue by kyounglee** [aissat/easy_localization#293]
As you know
1) context.localizationDelegates
2) context.supportedLocales
3) context.locale
are not supported in lower version of EasyLocalization (2.1.0)

Can you tell me how to get the value ( context.localizationDelegates ) for lower version.

EasyLocalization module has dependeny on intl module ( in my case  : ^0.16.1, Many firebase modules has dependency on intl 0.16.1).
So, I think there is no way to upgrade EasyLocalization, but wait.  Is it right ?

**Comment by aissat** [comment]
@kyounglee check `easy_localization: ^2.3.4-nullsafety.1`  same #288
