### ISSUE TITLE
Null check operator used on a null value on plurals

### ISSUE THREAD

**Issue by RootSoft** [aissat/easy_localization#297]
When using Sound Null Safety and not specifying all plural keys (zero, one, two, few, may, other), app crashes with the following exception:

Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      Localization._resolvePlural (package:easy_localization/src/localization.dart:133:22)
#1      Localization.plural (package:easy_localization/src/localization.dart:108:14)
#2      plural (package:easy_localization/src/public.dart:82:35)
#3      TextTranslateExtension.plural (package:easy_localization/src/public_ext.dart:41:12)

```
  "comment": {
    "zero": "no comments",
    "one": "{} comment",
    "few": "{} comments",
    "many": "{} comments",
    "other": "{} comments"
  }
```

Two is left out

```
Text(
          'comment',
          style: regularLightTextStyle.copyWith(fontSize: textSizeMicro),
        ).plural(1, context: context)
```

**Comment by Chris1234567899** [comment]
Can confirm this.

**Comment by bw-flagship** [comment]
Closing this for now, since it's a very old issue and there were many updates until now -> I suppose it is fixed. If not, please comment here.
