### ISSUE TITLE
Support {languageCode}_{countryCode}.json

### ISSUE THREAD

**Issue by hupo376787** [aissat/easy_localization#3]
Hi, I'm using this awesome package, but found some bug.
In China, we have simplified Chinese and traditional Chinese, so {languageCode}_{countryCode} will be used.
But it seems this project does not support it.

https://www.unicode.org/reports/tr35/#Unicode_language_identifier

![image](https://user-images.githubusercontent.com/14960168/51846852-62e6dc80-2355-11e9-8847-e2a754e2f738.png)

**Comment by aissat** [comment]
hi @hupo376787  
Thanks for this note, I will take them into account, and we will work on them as soon as possible

**Comment by tidharnitzan** [comment]
this is a must. any app today need to support variant of locales.

**Comment by aissat** [comment]
Modified file pattern to accomodate country codes #10
