### ISSUE TITLE
Blank screen in released Android app when R8/shrink is enabled

### ISSUE THREAD

**Issue by zhanghuanchong** [aissat/easy_localization#300]
It's strange that my app stuck with the blank screen after launching in a built release Android app. It works perfectly in debug mode and also iOS' debug/release modes.

The `preloaderColor` or `preloaderWidget` are able to show, but cannot load the `child`.

I commented out all other code, leaving only the code like this:

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return EasyLocalization(
      path: 'assets/translations',
      supportedLocales: [Locale('en')],
      child: Builder(
        builder: (BuildContext context) {
          return MaterialApp(
            localizationsDelegates: context.localizationDelegates,
            supportedLocales: context.supportedLocales,
            locale: context.locale,
            home: Scaffold(
              appBar: AppBar(
                title: Text('Test app'),
              ),
              body: Center(
                child: Text('App body'),
              ),
            ),
          );
        },
      ),
    );
  }
}

void main() {
  runApp(App());
}
```

Still the same, blank screen. Leave only the `MaterialApp` in the build method works.

I'm using version 2.3.3, while the flutter version is 1.22.5.

https://flutter.dev/docs/deployment/android#shrinking-your-code-with-r8

After checking the official doc to release an app, I notice that the R8 is enabled by default. I tried to build with the below command:

> flutter build apk --split-per-abi --no-shrink

It works! but why? Please help!

**Comment by babulpatel1309** [comment]
This is how it looks like in the release build. 
https://stackoverflow.com/questions/65438033/flutter-splash-flicker-issue

I was tracking down the bug and was removing all init libraries. Finally found the causing library. For now i've replaced logic with normal integration using this tutorial.

https://blog.codemagic.io/localising-flutter-applications-and-automating-the-localisation-process/

**Comment by aissat** [comment]
check  #267
