### ISSUE TITLE
When I change language from phone setting, the plugin is not working?

### ISSUE THREAD

**Issue by lutang123** [aissat/easy_localization#302]
Hello, I tried with the example folder:, it seems only works when having languages choices in your own app. e.g. in the example we have German, but if i switch language to German in phone setting, the screen does not change, it still shows English. Is it only work like this way? We have to have a drawer or drop down button for language choice on the app? Thank you!

**Comment by aykutonen** [comment]
I solved this problem that way, i hope to help you too.

My translations files are "en.json", "tr.json".

When changed device language, my app did not effect. 
```
child: EasyLocalization(
        supportedLocales: [Locale('en', ''), Locale('tr', '')],
        path: 'assets/translations',
        fallbackLocale: Locale('en', ''),
        child: MyApp(),
      ),
```

But this way it's worked;
```
child: EasyLocalization(
        useOnlyLangCode: true, // add this
        supportedLocales: [Locale('en'), Locale('tr')], // change this
        path: 'assets/translations',
        fallbackLocale: Locale('en'), // change this 
        child: MyApp(),
      ),
```

**Comment by lutang123** [comment]
Thank you! I figured out too, but I didn't understand their example code.  it has a generated folder and in main, it translates like this: title: Text(LocaleKeys.title).tr(context: context), I don't understand the code, where this LocaleKeys from and how to generate code? if you understand, please explain to me, thank you!

**Comment by aykutonen** [comment]
I’m using without generated files. 
like; “my_key_in_json”.tr()

for generating a local keys look this section; https://pub.dev/packages/easy_localization#-code-generation

**Comment by lutang123** [comment]
Thank you!

**Comment by UlanNurmatov** [comment]
> I solved this problem that way, i hope to help you too.
> 
> My translations files are "en.json", "tr.json".
> 
> When changed device language, my app did not effect.
> 
> ```
> child: EasyLocalization(
>         supportedLocales: [Locale('en', ''), Locale('tr', '')],
>         path: 'assets/translations',
>         fallbackLocale: Locale('en', ''),
>         child: MyApp(),
>       ),
> ```
> 
> But this way it's worked;
> 
> ```
> child: EasyLocalization(
>         useOnlyLangCode: true, // add this
>         supportedLocales: [Locale('en'), Locale('tr')], // change this
>         path: 'assets/translations',
>         fallbackLocale: Locale('en'), // change this 
>         child: MyApp(),
>       ),
> ```

Tried it, but it didn't help.

**Comment by furkancetintass** [comment]
@aykutonen  Thanks bro 🚀
