### ISSUE TITLE
Version dependency problem ( related #305)

### ISSUE THREAD

**Issue by kyounglee** [aissat/easy_localization#309]
This is related #305.
The solution given at the issue #305 ( dependency_overrides ) applied, another problem occurs (build FAILURE).

Most plugins(firebase_~/flutter_contact/date_time_picker/local_auth .., etc..) still use intl 0.16.1 ( not 0.17.0-nullsafety.2 )
I can't find a way to upgrade easy_localization easily.
Can you tell me how to do it ?

<pre>
This is the output of build ( after applying dependency_overrides )
Running Gradle task 'assembleDebug'..
/~~/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:413:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$selectedRowCount', formatDecimal(selectedRowCount));
      ^^^^^^^^^^^^
/~~/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:550:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$licenseCount', formatDecimal(licenseCount));
      ^^^^^^^^^^^^
/~~/flutter/packages/flutter_localizations/lib/src/material_localizations.dart:659:7: Error: Method 'replaceFirst' cannot be called on 'String?' because it is potentially null.
Try calling using ?. instead.
    ).replaceFirst(r'$remainingCount', formatDecimal(remainingCount));
      ^^^^^^^^^^^^

FAILURE: Build failed with an exception.
</pre>

-----
about .yaml
<pre>
   ::::: ( some omitted )
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^2.3.3+1
  intl : ^0.17.0-nullsafety.2
  ::::: ( some omitted )
dependency_overrides:
  intl: 0.16.0
</pre>
-----
$ flutter doctor -v
<pre>
[√] Flutter (Channel master, 1.25.0-5.0.pre.65, on Microsoft Windows [Version 10.0.19041.685], locale ko-KR)
    • Flutter version 1.25.0-5.0.pre.65 at ~~\flutter
    • Framework revision 8f3a12f144 (5 weeks ago), 2020-12-04 08:42:30 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at \Users\~~\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: ~~\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at ~~\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at ~~\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
</pre>

**Comment by aissat** [comment]
@kyounglee  #311
