### ISSUE TITLE
_AssertionError ('dart:ui/window.dart': Failed assertion: line 281: '<optimized out>': is not true.)

### ISSUE THREAD

**Issue by AkshayPathak-RhythmSoft** [aissat/easy_localization#31]
![ELError](https://user-images.githubusercontent.com/55743417/68368600-6cac3480-015e-11ea-8e36-d15d83396cf5.PNG)

Getting this error when phone language  is something else except the one defined by us in app. 
steps to recreate error : 
change phone language to something else than what is defined
Example : defined languages en-US,ar-DZ then set language to French in particular
install app

**Comment by pulstar** [comment]
I am experiencing the same problem, but my device language is correct.

E/flutter ( 5394): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'dart:ui/window.dart': Failed assertion: line 281: '<optimized out>': is not true.
E/flutter ( 5394): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 5394): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 5394): #2      new Locale (dart:ui/window.dart:281:15)
E/flutter ( 5394): #3      _EasyLocalizationState.saveLocale.<anonymous closure> (package:easy_localization/easy_localization_provider.dart:58:24)
E/flutter ( 5394): #4      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
E/flutter ( 5394): #5      _EasyLocalizationState.saveLocale (package:easy_localization/easy_localization_provider.dart:57:7)
E/flutter ( 5394): <asynchronous suspension>
E/flutter ( 5394): #6      _EasyLocalizationState.initState (package:easy_localization/easy_localization_provider.dart:36:5)
E/flutter ( 5394): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter ( 5394): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter ( 5394): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter ( 5394): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter ( 5394): #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
E/flutter ( 5394): #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
E/flutter ( 5394): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
E/flutter ( 5394): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
E/flutter ( 5394): #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
E/flutter ( 5394): #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
E/flutter ( 5394): #17     runApp (package:flutter/src/widgets/binding.dart:845:7)
E/flutter ( 5394): #18     main (package:bargainer_pro/main.dart:29:3)
E/flutter ( 5394): #19     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter ( 5394): #20     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 5394): #21     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5394): #22     _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 5394): #23     runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 5394): #24     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter ( 5394): #25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 5394): #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by pulstar** [comment]
This problem have something to do with SharedPreferences plug-in. I updated it to the version ^0.5.4+5 and removed the line below from my main.dart file. This solved the problem above.

SharedPreferences.setMockInitialValues({});

**Comment by Eugnis** [comment]
Same error with Flutter 1.9.1+hotfix.6. Updating SharedPreferences not fixed this.

**Comment by alectogeek** [comment]
Same error on Flutter Channel master, v1.12.3-pre.10

**Comment by alectogeek** [comment]
Looks like smth happens during creation of new Locale

![image](https://user-images.githubusercontent.com/18165303/70427774-69baa180-1a86-11ea-9d32-f296c0290041.png)
![image](https://user-images.githubusercontent.com/18165303/70427790-70491900-1a86-11ea-8e55-05f828020f47.png)

**Comment by alectogeek** [comment]
Any updates here? Guys, who faced same problem, can I send my app to prod with this error?

**Comment by damfrg** [comment]
@alectogeek I found problem was in in main.dart build method with
```
locale: data.savedLocale,
```
I commented out and it works but dont know what impact this has.

**Comment by damfrg** [comment]
Error is in saveLocale() function... in if statemente :/
Here is fix
![image](https://user-images.githubusercontent.com/50672190/72057411-aa4c4b80-32ce-11ea-9db3-6ebf57241457.png)

**Comment by damfrg** [comment]
|| allowed _codeLang to be null and _codeCoun was set to some value.. Replace || with && and i added extra measure _codeLang != '' to fullfill assert in Locale constructor...

**Comment by manhlh** [comment]
> Error is in saveLocale() function... in if statemente :/
> Here is fix
> ![image](https://user-images.githubusercontent.com/50672190/72057411-aa4c4b80-32ce-11ea-9db3-6ebf57241457.png)

Tks, it work!

**Comment by dominwong4** [comment]
![image](https://user-images.githubusercontent.com/13159792/72586134-abfbbc00-392b-11ea-9078-5a76a2e94780.png)
I Fix it like this. but it is not a best solution if you don't have default lang

**Comment by pulstar** [comment]
Glad to hear about that! Hope the package at pub.dev be updated soon.

**Comment by aissat** [comment]
@pulstar  it's ready 
enjoying

**Comment by pulstar** [comment]
I updated here, but it could not find the EasylocaLizationDelegate... I figured out the problem and is the class name, that changed from "EasylocaLizationDelegate" to "EasyLocalizationDelegate"... (notice the uppercase L).
