### ISSUE TITLE
Release Build Error

### ISSUE THREAD

**Issue by MiranKm** [aissat/easy_localization#310]
The assets don't load when building for release, it just stays on the preloaderWidget, meaning it just shows that
I can't log anything since it's a release build,

I'm using 
  easy_localization: ^2.3.2

Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (5 months ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

**Comment by aissat** [comment]
@MiranKm  check #306

**Comment by MiranKm** [comment]
I upgraded flutter latest version

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (4 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

and I'm using that version you gave me I get this error now
`
 Because every version of flutter_test from sdk depends on path 1.8.0-nullsafety.1 and easy_localization >=3.0.0-dev.0 depends 
 on path ^1.8.0-nullsafety.3, flutter_test from sdk is incompatible with easy_localization >=3.0.0-dev.0.
`

**Comment by aissat** [comment]
@MiranKm  try 
```yaml
dependency_overrides:
  intl: ^0.16.1
```

**Comment by MiranKm** [comment]
It's same

`
Because every version of flutter_test from sdk depends on path 1.8.0-nullsafety.1 and easy_localization >=3.0.0-dev.0 depends on path ^1.8.0-nullsafety.3, flutter_test from sdk is incompatible with easy_localization >=3.0.0-dev.0.

`

**Comment by aissat** [comment]
Does the same thing for path @MiranKm

**Comment by MiranKm** [comment]
gets the packages but Doesn't build

the log:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by aissat** [comment]
Okay, bro, you can return to the old version to the day I will fix this problem, thanks for reporting this issue 
I thought we have bugs with the dependency version

**Comment by aissat** [comment]
@MiranKm I fixed this bug try the `3.0.0-dev.1` test passed  on channel `stable`
