### ISSUE TITLE
intl  version solving failed

### ISSUE THREAD

**Issue by aissat** [aissat/easy_localization#313]
to solve this issue we have a tow way 

1. change to flutter `stable` channel: `flutter channel stable`
2. in case not on the stable channel override dependencies

Related issues, Duplicate of  #191 #275 #288 #305 #309 #311

**Comment by brizaldi** [comment]
Hi, just wondering is there any progress about this? currently in flutter channel stable and we cannot build our app because dependency conflicts

**Comment by aissat** [comment]
@brizaldi  any version ??

**Comment by brizaldi** [comment]
I'm currently using `easy_localization: ^2.3.3+1` and `flutter stable: 1.22.6`
the only workaround is overriding dependencies inside `pubspec.yaml`

```
dependency_overrides:
  intl: ^0.16.1
  path: ^1.7.0
```
