### ISSUE TITLE
EasyLocalization.ensureInitialized() returns void or Future<void>?

### ISSUE THREAD

**Issue by kyle-seongwoo-jun** [aissat/easy_localization#314]
I installed `3.0.0-dev.1` and added `await EasyLocalization.ensureInitialized()`.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/16515307/103966450-3d021d80-51a3-11eb-8e41-5c43afcd7731.png">

Android Studio shows warning like above.

Is it correct `EasyLocalization.ensureInitialized()` returns `void`, or `Future<void>`?

Thank you.

**Comment by kasyrm** [comment]
I added EasyLocalizaiton in version 2.3.3.
VSC shows this error when trying to call ensureInitialized on EasyLocalization:
```
The method 'ensureInitialized' isn't defined for the type 'EasyLocalization'.
Try correcting the name to the name of an existing method, or defining a method named 'ensureInitialized'.
```

I imported the package at the top of the file.

**Comment by aissat** [comment]
> I installed `3.0.0-dev.1` and added `await EasyLocalization.ensureInitialized()`.
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/16515307/103966450-3d021d80-51a3-11eb-8e41-5c43afcd7731.png">
> 
> Android Studio shows warning like above.
> 
> Is it correct `EasyLocalization.ensureInitialized()` returns `void`, or `Future<void>`?
> 
> Thank you.

@kyle-seongwoo-jun correct one `Future<void>`
