### ISSUE TITLE
How to auto-import package in vs code?

### ISSUE THREAD

**Issue by DarkMikey** [aissat/easy_localization#317]
Question

By writing `Text(LocaleKeys...` I'm usually able to auto-import `locales.g.dart` file. Sadly by continuing writing `...)tr.()` the file 
`package:easy_localization/easy_localization.dart` won't be an suggestion in vs code's auto import menu.

Has anyone found an easier method than just copying the path? 

```
flutter doctor
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.685], locale de-AT)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.52.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by Overman775** [comment]
@DarkMikey 
in dart file:
```dart
import 'path_to/loacales.g.dart';
```

**Comment by DarkMikey** [comment]
> @DarkMikey
> in dart file:
> 
> ```dart
> import 'path_to/loacales.g.dart';
> ```

Could you please re-read the question? 

Sorry if I haven't expressed the problem perfectly. I want to easily auto-import the `easy_localization.dart` file of this package to get the ability to use the `tr()`-method. I know this is not something this package can actively provide, I just wanted to ask, if anyone knows a way of doing this. Or do you just copy the package to every file that needs it?

**Comment by Overman775** [comment]
@Overman775 There was the same problem, I solved it easier, I do in my projects like this. Expression classes don't import automatically.

![1ex](https://user-images.githubusercontent.com/47769319/104800951-1d49a580-57f2-11eb-8d73-e474c3a12154.png)
![2ex](https://user-images.githubusercontent.com/47769319/104801006-20dd2c80-57f2-11eb-9865-7c2e430c5506.png)

**Comment by DarkMikey** [comment]
Thanks, excellent, this helped a lot!
