### ISSUE TITLE
English and Arabic in the same page

### ISSUE THREAD

**Issue by somaria** [aissat/easy_localization#32]
I have some pages where I have English and Arabic in the same page.  The English text would become left aligned and the exclamation mark was put at the beginning of the text.

For example, a normal sentence like Wait A Minute!! would become !!Wait A Minute with the exclamation marks put in front.  Is that a bug?

**Comment by Saifallak** [comment]
use Directionality Widget for that , or in Text widget use text direction

**Comment by panchalAlpit** [comment]
> use Directionality Widget for that , or in Text widget use text direction

But how to change the app bar icon when change the language.

**Comment by Saifallak** [comment]
> > use Directionality Widget for that , or in Text widget use text direction
> 
> But how to change the app bar icon(back icon, menu icon) when change the language.

you can use `matchTextDirection` in any `Image` and `ImageProvider`

**Comment by panchalAlpit** [comment]
> > > use Directionality Widget for that , or in Text widget use text direction
> > 
> > 
> > But how to change the app bar icon(back icon, menu icon) when change the language.
> 
> you can use `matchTextDirection` in any `Image` and `ImageProvider`

No didn't use **matchTextDirection** in appbar back icon or menu icon

**Comment by Saifallak** [comment]
> > > > use Directionality Widget for that , or in Text widget use text direction
> > > 
> > > 
> > > But how to change the app bar icon(back icon, menu icon) when change the language.
> > 
> > 
> > you can use `matchTextDirection` in any `Image` and `ImageProvider`
> 
> No didn't use **matchTextDirection** in appbar back icon or menu icon

didn't? then use it 😅
