### ISSUE TITLE
Incorrect docs or need string extension context argumants implementation

### ISSUE THREAD

**Issue by karabanovbs** [aissat/easy_localization#321]
`StringTranslateExtension` `tr` and `plural` methods not support context named argument.

https://github.com/aissat/easy_localization/blob/develop/lib/src/public_ext.dart#L63
https://github.com/aissat/easy_localization/blame/develop/README.md#L195

**Comment by Overman775** [comment]
@karabanovbs forgot to add  import  `import 'package:easy_localization/easy_localization.dart';`

**Comment by karabanovbs** [comment]
@Overman775 than not import problem. 
`context` argument not exist in `StringTranslateExtension`.

**Comment by Overman775** [comment]
@karabanovbs needs sample code to reproduce

**Comment by karabanovbs** [comment]
@Overman775 reproduce what? difference between docs and implementations?  

This code not working. But in docs says that `tr` have `context` named argument. But `StringTranslateExtension` not implement `context` named argument.
```
'someString'.tr(context: context)
```

**Comment by Overman775** [comment]
@karabanovbs  I understand you, thanks for issue.

**Comment by Overman775** [comment]
context removed from tr() and plural() in PR #343
