### ISSUE TITLE
setLocale doesn't work in production

### ISSUE THREAD

**Issue by MiranKm** [aissat/easy_localization#322]
I change the language of the app with setLocale and it works on the emulator but not when building for production,
it build the apk fine, everything works, but it doesn't persist the locale, for example If the app is "en" and change it to "ar"
when I  restart the app close it and open it, the locale goes back to en, even if I saveLocale = true

**Comment by Overman775** [comment]
@MiranKm need sample to reproduce

**Comment by MiranKm** [comment]
I'm not doing anything strange, I just setLocale and it doesn't save! even if save locale is true, it might be a bug in the emulator 
or something.

I found a work around works
I'm setting the initial locale then saving it with shared preferences then wherever I change the locale I save it again and and when opening the app I load the saved locale.
