### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by DirtyNative** [aissat/easy_localization#323]
Is there a way to have the localizations being split into multiple files? So I could have a file for each view that I have, or at least for Titles, Words, Overlays, Errors, etc. 

And if this is possible, is it also possible to have some files inside a different project? We have a modular app which gets extended by modules from time to time and those modules should handle themselfes, which means they should have the localizations by their own and not from the base project.

**Comment by Overman775** [comment]
@DirtyNative  its planned, but you can help project make this feature 😉 
You can make your own loader with support modular loading.

dublicate #294
