### ISSUE TITLE
Linked translation doesn't seems to work. Please advice

### ISSUE THREAD

**Issue by xwpony** [aissat/easy_localization#327]
https://pub.dev/packages/easy_localization#linked-translations

Other feature works fine. But the example doesn't work. The link doesn't seem to happen.

```
    "example": {
        "hello": "Hello",
        "world": "World!",
        "helloWorld": "@:example.hello @:example.world"
    }
```
<img width="293" alt="Screen Shot 2021-01-26 at 2 58 17 PM" src="https://user-images.githubusercontent.com/48699811/105917249-f146d500-5fe6-11eb-87f1-e62f7f0fe51d.png">

**Comment by Overman775** [comment]
@xwpony plese cahnge version to3.0.0-dev.1

**Comment by xwpony** [comment]
thx, it's working now!
