### ISSUE TITLE
Checking translation key exists

### ISSUE THREAD

**Issue by xJon** [aissat/easy_localization#328]
Currently if no localization key is found, an error will be printed.
Is it possible to check whether a localization key exists for a specific string? Trying to use `.tr()` inside a `try-catch` block doesn't work.
Thank you!

**Comment by xJon** [comment]
Actually, it seems that a `try-catch` block does seem to work after I changed my code a bit. Is that how it should work? Thanks!

**Comment by Overman775** [comment]
@xJon  planned add new logger package, you can customize print function or disable warnings #315
