### ISSUE TITLE
Stuck on white screen with production build 

### ISSUE THREAD

**Issue by chandanitnou** [aissat/easy_localization#329]
When I build appbundle and publish to play store to test it Stuck on preloaderColor,
Problem if i use flutter_facebook_auth + easy_localization => see only preloaderColor, 
if I use only easy_localization => worked
if user onluy flutter_facebook_auth => worked
Thanks,

**Comment by aissat** [comment]
hi @chandanitnou check #306

**Comment by chandanitnou** [comment]
The only blank white screen showed please help.
<img width="527" alt="Screen Shot 2021-02-03 at 4 02 48 PM" src="https://user-images.githubusercontent.com/8949345/106723231-778f9680-6639-11eb-8da0-a9a0ac3ab997.png">
<img width="771" alt="Screen Shot 2021-02-03 at 4 03 29 PM" src="https://user-images.githubusercontent.com/8949345/106723433-aefe4300-6639-11eb-8fdd-4ee7dc1c5724.png">
The out message:
<img width="1326" alt="Screen Shot 2021-02-03 at 4 03 46 PM" src="https://user-images.githubusercontent.com/8949345/106723506-c2a9a980-6639-11eb-8281-1b51575fdaba.png">

Thank you.
