### ISSUE TITLE
Fast switching languages throws an error

### ISSUE THREAD

**Issue by pulstar** [aissat/easy_localization#33]
When I call changeLocale() in fast sequence from my application UI, it throws the error below. The file "es-US.json" does not exists, because the language code and the country code doesn't match. I did check what I am passing to changeLocale() and it is correct. No idea what is causing this error.

E/flutter (17002): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Unable to load asset: assets/langs/es-US.json
E/flutter (17002): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
E/flutter (17002): <asynchronous suspension>
E/flutter (17002): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
E/flutter (17002): <asynchronous suspension>
E/flutter (17002): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
E/flutter (17002): #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
E/flutter (17002): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
E/flutter (17002): #5      AppLocalizations.load (package:easy_localization/easy_localization_delegate.dart:44:31)
E/flutter (17002): <asynchronous suspension>
E/flutter (17002): #6      EasylocaLizationDelegate.load (package:easy_localization/easy_localization_delegate.dart:133:25)
E/flutter (17002): <asynchronous suspension>
E/flutter (17002): #7      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
E/flutter (17002): #8      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:508:62)
E/flutter (17002): #9      _LocalizationsState.didUpdateWidget (package:flutter/src/widgets/localizations.dart:497:7)
E/flutter (17002): #10     StatefulElement.update (package:flutter/src/widgets/framework.dart:4103:58)
E/flutter (17002): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #14     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter (17002): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #18     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter (17002): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter (17002): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #26     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter (17002): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #30     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
E/flutter (17002): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #34     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
E/flutter (17002): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
E/flutter (17002): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
E/flutter (17002): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (17002): #38     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
E/flutter (17002): #39     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
E/flutter (17002): #40     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
E/flutter (17002): #41     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter (17002): #42     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
E/flutter (17002): #43     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter (17002): #44     _rootRun (dart:async/zone.

**Comment by aissat** [comment]
#31
