### ISSUE TITLE
null-safety support

### ISSUE THREAD

**Issue by muhlba91** [aissat/easy_localization#330]
Flutter's current dev channel introduces null-safety support. Are there plans to make this library null safe? Potentially with a prerelease for people using the dev channel already?

**Comment by Overman775** [comment]
@muhlba91 https://github.com/aissat/easy_localization/tree/null-safety

**Comment by Overman775** [comment]
https://pub.dev/packages/easy_localization/versions

2.3.4-nullsafety.4

**Comment by aissat** [comment]
@muhlba91 https://pub.dev/packages/easy_localization/versions/3.0.0-nullsafety
