### ISSUE TITLE
Locale not changing for all screens

### ISSUE THREAD

**Issue by Tetracyl** [aissat/easy_localization#335]
I'm having an issue where the locale is only changing for the current screen. The appbar, navbar, and other screens don't change unless the app is reloaded. Is there a way to make the locale of all screens change? Thanks

I am doing this to change the locale
```dart
onTap: () => {
  context.setLocale(Locale('es', 'ES')),
},
```

Here is my main.dart:
```dart
runApp(
  EasyLocalization(
    supportedLocales: supportedLocales,
    path: 'i18n',
    startLocale: startLocale,
    fallbackLocale: Locale('en', 'US'),
    saveLocale: true,
    assetLoader: YamlAssetLoader(),
    child: App(
      account: account,
    ),
  ),
);
```

**Comment by Overman775** [comment]
@Tetracyl your code wrong

```
onTap: () =>  context.setLocale(Locale('es', 'ES')),

or 

onTap: () {
  context.setLocale(Locale('es', 'ES')),
},
```

**Comment by Tetracyl** [comment]
II changed my code to what you told me to however I am still getting the same problem. The locale is not changing for all screens.

**Comment by Tetracyl** [comment]
I was able to fix the issue by refreshing the app.

**Comment by AlexanderFarkas** [comment]
@Overman775  Why did you, maintainers, remove context from `tr` and `plural`? That's the cause of these issues (there are many of them).
