### ISSUE TITLE
Lack of automated tests?

### ISSUE THREAD

**Issue by hicnar** [aissat/easy_localization#34]
Folks,

I was just thinking of using your lib in my little project, and out of curiosity wanted to have a look at  the automated tests but I have found none. 
Are the tests somewhere out there and I cannot find them or they're just... not there? If not, I do not want to discourage you, but lack of test coverage is literally a show stopper for potential clients as without tests there is no way for the users of your library to maintain any level of assurance that subsequent versions of your lib will continue to behave in a consistent, predictable way. 
I would also venture an opinion that  the number of issues people are reporting is directly related to the lack of automated tests in the project.

Best!

**Comment by aissat** [comment]
@hicnar thanx  for this moment the automated tests not found 
if u can contribute to it

**Comment by danilofuchs** [comment]
#56 and #66 tackle this. Thanks for bringing this issue to attention!

The library is currently being rewritten with a simpler, more testable API.
