### ISSUE TITLE
Incorrect value returned when keys are nested

### ISSUE THREAD

**Issue by frankyvij** [aissat/easy_localization#348]
```
{
"profile": {
"public_profile": {
"title": "User Profile"
},
},
"profile": "Profile"
}
```

The value for this combination: "profile.public_profile.title" is returned as "Profile". Is this expected?

easy_localization: 2.3.3+1

**Comment by frankyvij** [comment]
I understand that this is probably a wrong configuration, but in this case if the library find a match for profile.public_profile.title, it should show the proper value. If not, then the string should continue to appear as "profile.public_profile.title" in the UI. Perhaps can be taken up as an improvement.

**Comment by bw-flagship** [comment]
This is an invalid json, since the key "profile" is duplicated
