### ISSUE TITLE
Fallback locale not used for missing translations

### ISSUE THREAD

**Issue by PiotrFLEURY** [aissat/easy_localization#350]
Plugin does not source translations from fallback locale when translation is missing in the current locale.

My app manage 2 locales (en + fr).
Fallback locale is en.
My Phone is configured in French.

Missing translations are currently replaced by the translation key.
Hoped: I would like to see my missing french translation in english.

It would be great to source missing translations in the fallback locale if we are not already on it.

*EDIT*
I am on the stable Flutter channel so I can't use the 3.0.0 preview version wich provides this feature (#333) because of the dart SDK version on the stable channel (2.10.5 on stable, 2.12.0 required)

**Comment by Overman775** [comment]
@PiotrFLEURY  you need set flag `useFallbackTranslations` to true and set `fallbackLocale`

example: 
```dart
EasyLocalization(
    child: MyApp(),
    supportedLocales: [
      Locale('en', 'US'),
      Locale('ar', 'DZ'),
      Locale('de', 'DE'),
      Locale('ru', 'RU')
    ],
    path: 'resources/langs',
    fallbackLocale: Locale('en'),
    useFallbackTranslations: true,
```

**Comment by PiotrFLEURY** [comment]
Hi, I tried on two different apps targeting android but I wasn't able to test it successfully because of the #349 issue.

Waiting for the bug fix

**Comment by PiotrFLEURY** [comment]
I close this one.

Fallback translations now works at the translation key level in 3.0.0.
