### ISSUE TITLE
Flutter Driver dependency conflict

### ISSUE THREAD

**Issue by PiotrFLEURY** [aissat/easy_localization#354]
**Description**
Hi, when I try to upgrade easy_localization plugin to 3.0.0 in a project that depends on `flutter_driver` I get the following error message:

```
Because every version of flutter_driver from sdk depends on args 1.6.0 and easy_localization 3.0.0 depends on args ^2.0.0, flutter_driver from sdk is incompatible with easy_localization 3.0.0.
```

easy_localization seems to depend on `args` `2.0.0` but flutter_driver still depend on `args` `1.6.0`

[https://github.com/flutter/flutter/blob/master/packages/flutter_driver/pubspec.yaml](https://github.com/flutter/flutter/blob/master/packages/flutter_driver/pubspec.yaml)

**Impact**
I am currently unable to migrate to 3.0.0 until flutter_driver upgrades its dependecies

**Steps to reproduce**

1. create a new Flutter project or open an existing one
2. add and configure easy_localization 3.0.0 to the app
3. Just add flutter_driver to the dev_dependencies

```
dev_dependencies:
  flutter_driver:
      sdk: flutter
```

Any idea ?

**Comment by Overman775** [comment]
https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by PiotrFLEURY** [comment]
Ok, overriding dependency makes the app build but, all my test_driver are failing due to this dependency override.

I cannot imagine to turn off all my automated tests campain.

I was reading the latest Flutter documentation about test driver and even if the integration_test seems to be the newest target for testing, flutter_driver can still optionally be used so the problem will still exist.

See [https://flutter.dev/docs/testing/integration-tests](https://flutter.dev/docs/testing/integration-tests)

As the 3.0.0 is a major version, should we consider that the easy_localization package is no longer compatible with flutter_driver and require to migrate on the integration_test ?

**Comment by Overman775** [comment]
Package compatibility is always a headache... In the future, we plan migrate to `build_runner`, the `args` package will be removed from the dependencies

**Comment by bw-flagship** [comment]
Closing since flutter_driver args was updated
