### ISSUE TITLE
Issue while loading translations from backend

### ISSUE THREAD

**Issue by nvamsi214** [aissat/easy_localization#36]
Translations using asset files is working fine but im facing issue while using loadPath from backend URL [(https://task.care/langs).]()

The translations are coming wrong. Please find the attachments below for reference. 
 
Output with translations from assets : 

![assets](https://user-images.githubusercontent.com/33240181/70242823-86f62400-1797-11ea-9cdf-8fd7244b93b5.png)

Output from URL (load path) : 

![URL](https://user-images.githubusercontent.com/33240181/70243323-62e71280-1798-11ea-826e-62d7284ccbcd.png)

**Comment by spiritinlife** [comment]
@nvamsi214 This seems like an encoding issue. Could you share the links to the language files?
