### ISSUE TITLE
What's the best coding workflow?

### ISSUE THREAD

**Issue by vladaman** [aissat/easy_localization#368]
I am rather confused how to use this package properly in **productive manner**.

1. When I create dart file and I'd like to include locale_keys.g.dart the Android Studio hint doesn't offer to automatically include locale_keys.g.dart - I must enter the import manually (type it). Intention actions don't offer me to import it automatically.
2. Same thing with Text("key").tr() then I press Alt+Enter it doesn't offer to import easy_localization module. Again I must import this manually again by typing or ctrl+c (_The method 'tr' isn't defined for the type 'Text'_)
3. I generally type Text("key").tr() then I have to import those files, then I have to go to .json file and add this key to en-US.json for example, then I have to generate LocaleKeys. But because I speak other languages, I need to open cs-CZ.json, add the same key. Also to sk-SK.json add the same key and translations.
4. Hot reload doesn't work - adding new item to .json translations doesn't reflect instantly in preview. This requires app to be relaunched, again it's time consuming.

And this is all for just adding one key to translate. Is there any faster way? Like for example in Java (Android Studio) when I just do R.string.key - I hit Alt+Enter, create key and translation and I am done.

Would it be possible to generate keys automatically in all these json files when I just add it? 

Also from other projects we are used to structuring keys with dots. Such as:

```json
{
  "PROJECT.app_title":"My App",
  "USER.first_name": "First name"
}
```

Would it be possible to somehow include dots or allow json to be more structured. Our current translation files are over 2000 lines and it would get messy.

![Screenshot from 2021-03-30 20-55-37](https://user-images.githubusercontent.com/907206/113041597-70e55180-919a-11eb-8681-f6b489adf660.png)

**Comment by DarkMikey** [comment]
Does this help? #317

**Comment by bw-flagship** [comment]
I suppose this is not relevant anymore because the tools have improved, so LocaleKeys and the extensions should appear in the suggestions.
