### ISSUE TITLE
➕ Add a video that explains the package usage.

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [aissat/easy_localization#369]
I have made a video that explains how to use the package and it seems people like it.

https://www.youtube.com/watch?v=cposNqIsyAY&t=907s&ab_channel=YazeedAlKhalaf

I suggest putting it in the README.md

👍 Agree
👎 Disagree, with reason 😉

**Comment by aissat** [comment]
hi @YazeedAlKhalaf, thnx  i'll do

**Comment by YazeedAlKhalaf** [comment]
@aissat I am not sure if you still considering this but the video the first suggestion when searching for "easy localization" on Google and YouTube.

![image](https://user-images.githubusercontent.com/41989385/120300250-6c413480-c2d4-11eb-8cb5-b394e72b5d40.png)
![image](https://user-images.githubusercontent.com/41989385/120300337-81b65e80-c2d4-11eb-8789-e76721ca82e0.png)
