### ISSUE TITLE
Throw Exception [](<key>) for plural

### ISSUE THREAD

**Issue by josephchenghmlet** [aissat/easy_localization#37]
Version: `1.3.1`

Hi, I've tried to use `AppLocalizations.of(context).plural("text.day", 2)` but it fails me.
Below is the structure.

```json
{
  "text": {
    "day": {
      "zero": "day",
      "one": "day",
      "other": "days"
    }
  }
}
```

It seems that `plural()` could parse non-nested key such as `day` as compared to `tr()` which can parse `text.day` 

Could `plural()` be enhanced to parse like `tr()`?

**Comment by aissat** [comment]
hi @josephchenghmlet 
u can change ur code to 
use `AppLocalizations.of(context).plural("day", 2)` 

```json
{
    "day": {
      "zero": "day",
      "one": "day",
      "other": "days"
    }
}
```
next version i'll fixe this issues

**Comment by josephchenghmlet** [comment]
Hi @aissat , thank you!

**Comment by btd1337** [comment]
Awaiting this fix...

**Comment by aissat** [comment]
@btd1337 updated
