### ISSUE TITLE
Stuck after doing EasyLocalization.ensureInitialized();

### ISSUE THREAD

**Issue by Zirialk** [aissat/easy_localization#373]
I get stuck after doing EasyLocalization.ensureInitialized(); and I don't get any exception in console :/ 
I just updated to 3.0.0

![image](https://user-images.githubusercontent.com/9695560/114524599-a59ae380-9c45-11eb-9b7c-b7256409f4b6.png)
![image](https://user-images.githubusercontent.com/9695560/114524645-afbce200-9c45-11eb-9db7-b61df2839e2c.png)

**Comment by ahkela21** [comment]
may i know what is ur workaround ?
