### ISSUE TITLE
Error on Streambuilder 

### ISSUE THREAD

**Issue by gustavosfq** [aissat/easy_localization#39]
when I import ease_localization on my project, all StreamBuilders don't work, worst problem is that snapshot.hasData always returns false.

I try removing easy_localization from my project and all works fine.

**Comment by madara134** [comment]
same issue

**Comment by spiritinlife** [comment]
@gustavosfq @madara134 could you provide an example that can easily reproduce the issue you are facing? Thank you.

**Comment by Overman775** [comment]
@gustavosfq @madara134 

Please recheck new version 2.0.0+3
