### ISSUE TITLE
CocoaPods not installed or not in valid state.

### ISSUE THREAD

**Issue by rajesh2701** [aissat/easy_localization#391]
I am getting the following error after adding easy_localization to my sample app.

Before adding this package it's running normally but I am getting the following error whenever I try to run the app after adding this package. 

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 12 Pro Max.

**Comment by Overman775** [comment]
Easy localization don't use Pods files. I thin you need delete old Pods files and build project again

**Comment by Overman775** [comment]
I am closing issue for lack of response. If you haven't fixed the problem, feel free to create a new one 😃
