### ISSUE TITLE
Add formatting to specific parts of the translated text

### ISSUE THREAD

**Issue by bartekpacia** [aissat/easy_localization#393]
Let's say I want to display the following string in my app:

English: So far you have saved **$20**.

Mind the bold "$20".

Now, I want to add a German translation:

German: Du hast bisher **$20** eingespart.

The question is: how can I use `package:easy_localization` and add formatting certain (different for each language) parts of the strings?

**Comment by Overman775** [comment]
Easy localization work only with strings, not TextStyles or Widgets. You need spleat translation and use RichText Widget
