### ISSUE TITLE
Is there a way to translate in an other langage but just one String ?

### ISSUE THREAD

**Issue by nefus8** [aissat/easy_localization#402]
Hi, I want to know if it's possible to use this plugin but translate juste one text in an other language.

Exemple : My app is in English, so I use English translation, but there is one text in the app that I want to be in French, but when the app is in French, I want that text to be in English. So as my app is in English, I want to use something like : "hello-text".tr(language: 'fr');

**Comment by Overman775** [comment]
Nope, uses only one main language and fallback language
