### ISSUE TITLE
How to parse arrays in JSON?

### ISSUE THREAD

**Issue by kinski76** [aissat/easy_localization#405]
Hi

I am struggling to work out something that I assumed would be simple.

I am trying to work out how I can access "categories" and then use a loop to generate each item within that array.

{
    "title": "Hello!",
    "message" : "This is English",
    "categories":[
      "category 1",
      "catergory 2",
      "category 3"
    ]
  }

I have searched around and cannot find any examples of how this can be achieved. Any pointers would be really appreciated.

thanks

ade

**Comment by Overman775** [comment]
use Map instead array

"categories": {
"cat1": "category 1" ,
"cat2": "category 2" 
}
