### ISSUE TITLE
Translation of Push-Notification

### ISSUE THREAD

**Issue by Fintasys** [aissat/easy_localization#407]
I'm using Firebase Cloud-Messaging to send push notifications to my App. 
FCM does not call `main()` instead it calls a global method. Inside this global method I am initializing easy_localization and firebase. This method will then show a notification where I try to translate received body text.
```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  await NotificationManager.instance.init();
  await EasyLocalization.ensureInitialized();
  ....
  var body = LocaleKeys.chat_message_notification_body_image.tr()
}
```
body will be `chat_message_notification_body_image` and throws error message that the key couldn't be found.

Does anyone know to get translation to work here?

**Comment by Fintasys** [comment]
Solved with workaround described here: https://github.com/aissat/easy_localization/issues/210

**Comment by hasanm08** [comment]
use this code
```
  static Future<bool> isEnglish() async {
    SharedPreferences preferences = await SharedPreferences.getInstance();
    await preferences.reload();
    String? locale = preferences.getString('locale');
    return locale?.contains('en') ?? true;
  }
```

**Comment by hellohejinyu** [comment]
> use this code
> 
> ```
>   static Future<bool> isEnglish() async {
>     SharedPreferences preferences = await SharedPreferences.getInstance();
>     await preferences.reload();
>     String? locale = preferences.getString('locale');
>     return locale?.contains('en') ?? true;
>   }
> ```

This method is not safe. If the user has never set the language, there is no value stored in SharedPreferences. At this time, the library will choose the device language or some other configuration of yours. You cannot assume that the user's device language is English. The following is some logic of the library when selecting the language.

```dart
if (forceLocale != null) {
  _locale = forceLocale;
} else if (_savedLocale == null && startLocale != null) {
  _locale = _getFallbackLocale(supportedLocales, startLocale);
} else if (saveLocale && _savedLocale != null) {
  _locale = selectLocaleFrom(supportedLocales, _savedLocale!, fallbackLocale: fallbackLocale);
} else {
  _locale = selectLocaleFrom(supportedLocales, _deviceLocale, fallbackLocale: fallbackLocale);
}
```

**Comment by hellohejinyu** [comment]
```dart
  static Future<String> getCurrentLanguageWithoutContext() async {
    SharedPreferences preferences = await SharedPreferences.getInstance();
    await preferences.reload();
    String? locale = preferences.getString('locale');
    locale ??= await findSystemLocale();
    currentLanguage = locale;
    if (supportedLocales.any((e) {
      return '${e.languageCode}_${e.countryCode}' == locale;
    })) {
      return currentLanguage;
    }
    // find languageCode is same as locale
    final languageCode = locale.split('_')[0];
    currentLanguage =
        supportedLocales.firstWhereOrNull((e) {
          return e.languageCode == languageCode;
        })?.toString() ??
        // here is fallbackLocale you set
        'en_US';
    return currentLanguage;
  }
```
