### ISSUE TITLE
Use one JSON file 

### ISSUE THREAD

**Issue by amarildox** [aissat/easy_localization#408]
I have a single JSON file in this format:

```
 "select_language_en": "Select Language",
 "select_language_it": "Selezionare lingua",
 "select_language_es": "Escolliu l'idioma",
```

I want to be able to use the tr function on this. Is there a way to write "select_language".tr() and have it select the appropriate key based on current locale (like select_language_en or select_language_it) or is it impossible to do it this way?

**Comment by Overman775** [comment]
nope, the package only works with localization in different files
