### ISSUE TITLE
.tr() not resolved

### ISSUE THREAD

**Issue by MuthuSubramaniam** [aissat/easy_localization#419]
![image](https://user-images.githubusercontent.com/39517706/130345386-53bb0dca-b062-4d66-aa5d-c8024ff8af7b.png)

I implemented like below,

![image](https://user-images.githubusercontent.com/39517706/130345410-e8cf70d2-bb8c-4206-affe-515534d1155d.png)

![image](https://user-images.githubusercontent.com/39517706/130345416-64175914-9e7a-4ad0-ba5d-8988d5306fdd.png)

assets folder

![image](https://user-images.githubusercontent.com/39517706/130345422-cfbeb0b3-1ff1-4559-bc59-969279b45a9f.png)

![image](https://user-images.githubusercontent.com/39517706/130345443-d44491fa-d228-40a2-82e0-e1d557229f5c.png)

![image](https://user-images.githubusercontent.com/39517706/130345457-c5f4ecb6-b3fc-4eeb-bef0-413b948025c2.png)

[🌎 Easy Localization] [WARNING] Localization key [login_header] not found

**Comment by MuthuSubramaniam** [comment]
some how i managed to fix that error, but now am getting below error,
<img width="713" alt="Screenshot 2021-08-25 at 6 23 22 AM" src="https://user-images.githubusercontent.com/39517706/130708753-5ba50255-19a3-4508-81d2-7d2501408041.png">

**Comment by jasonjflaherty** [comment]
> some how i managed to fix that error, but now am getting below error,
> <img alt="Screenshot 2021-08-25 at 6 23 22 AM" width="713" src="https://user-images.githubusercontent.com/39517706/130708753-5ba50255-19a3-4508-81d2-7d2501408041.png">

Did you run the command $flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart ?

**Comment by MuthuSubramaniam** [comment]
i am getting below error

[ERROR] easy localization: Source path does not exist error.



@jasonjfaherty

**Comment by s00d** [comment]
hello. read here - [202](https://github.com/aissat/easy_localization/issues/202)
need add easy_localization to all dart files
```
import 'package:easy_localization/easy_localization.dart';
```

![image](https://user-images.githubusercontent.com/2684895/143037881-8924e69e-75a7-428a-9a30-67a39d519112.png)
