### ISSUE TITLE
A member named 'tr' is defined in extensions

### ISSUE THREAD

**Issue by JAICHANGPARK** [aissat/easy_localization#428]
https://dart.dev/tools/diagnostic-messages#ambiguous_extension_member_access

**Comment by JAICHANGPARK** [comment]
A member named 'tr' is defined in extensions 'StringTranslateExtension' and 'Trans', and none are more specific. (Documentation)

**Comment by JAICHANGPARK** [comment]
I think it conflict with get x package

**Comment by weichaist** [comment]
Yep, i had the same issue. Fixed with this code.
Basically, you need to hide the Trans extension in GetX

`import 'package:get/get.dart' hide Trans;`

**Comment by actumn** [comment]
@weichaist 
You saved my life. Greatly appreciate.

**Comment by umitmutluu** [comment]
it doesn't work to me :(

**Comment by taqi92** [comment]
@weichaist you just saved the day!!
@umitmutluu did you try with "your text".tr()? & import 'package:easy_localization/easy_localization.dart';?

**Comment by ataknakbulut** [comment]
> it doesn't work to me :(

if you imported 'package:get/get.dart' hide Trans; &  'package:get/get.dart'; together its not working. Try with only 

import 'package:get/get.dart' hide Trans;

**Comment by sohaibjameelkhan** [comment]
> Yep, I had the same issue. Fixed with this code. Basically, you need to hide the Trans extension in GetX
> 
> `import 'package:get/get.dart' hide Trans;`

really appreciated

**Comment by JabbarKakar** [comment]
Still not working in any sence

**Comment by asimolpiq** [comment]
use import 'package:easy_localization/easy_localization.dart' hide StringTranslateExtension;

**Comment by bw-flagship** [comment]
solved by @weichaist

**Comment by FlutterCyber** [comment]
Thank you very much bro. You saved my day!!!
