### ISSUE TITLE
[🌎 Easy Localization] [WARNING] Localization key [app_name] not found

### ISSUE THREAD

**Issue by EhabSalah** [aissat/easy_localization#444]
I set `title` to my `MaterialApp.router` as `title: tr(LocaleKeys.app_name)` but the `app_name` value always not found!

with warning `[🌎 Easy Localization] [WARNING] Localization key [app_name] not found`!

**Comment by Joldersman** [comment]
To localize app name in Android you need
1) Create file android/app/src/main/res/values/strings.xml
 add localization JSON file for example 
assets/translations/fr.json
with 
<resources>
   <string name="app_name_launcher">BMI Family</string>
</resources>  

2) create folder, for example for French localization   /android/app/src/main/res/values-fr/  
3) create a file /android/app/src/main/res/values-ru/strings.xml
<resources>
   <string name="app_name_launcher">type here app Name in French</string>
</resources>
4) in file /android/app/src/main/AndroidManifest.xml 
change your current android:label= "..."
to 
android:label="@string/app_name_launcher"

to add another localizaton just repeat steps 2 and 3 

For iOS localization you can check that tutotial https://youtu.be/6ZIYdNa2c84

**Comment by EhabSalah** [comment]
Thanks for your help. but this issue is related to the app `title` not the `launcher name`.

**Comment by jenshor** [comment]
@EhabSalah have you been able to find a solution? I'm facing the same problem.

**Comment by aea91** [comment]
problem is still continuing. Is there anyone solved the problem?

**Comment by KuzmenkoEvgenij** [comment]
You can use `onGenerateTitle: (_) => LocaleKeys.appName.tr(),` instead of `title`

**Comment by bw-flagship** [comment]
The problem is that the delegates are added to the context by the MaterialApp, so it will be only available in a context blow the MaterialApp. Therefore, the solution found by @KuzmenkoEvgenij should work.
