### ISSUE TITLE
Not reflected immediately if i change lang

### ISSUE THREAD

**Issue by MuthuHere** [aissat/easy_localization#446]
Hi i'm using easy_localization inmy application,

on tap of the change lang button the logs shows like below,

![image](https://user-images.githubusercontent.com/18752533/149284390-9584ed9c-3a49-4780-9028-2d1ab300e3cc.png)

but the text  lang remains same, no change. if restart the app then only it used to change.

![image](https://user-images.githubusercontent.com/18752533/149284577-5f18cf70-ca67-491f-a7bd-d9f3414054b8.png)

**Comment by aymaalo** [comment]
I have the same issue here

**Comment by F-anleo** [comment]
did you add delegates to your MaterialApp?

**Comment by MuthuHere** [comment]
@F-anleo  yes, i did add.

![image](https://user-images.githubusercontent.com/18752533/149889204-40c0a9bc-f22d-4453-a2ac-0f5360092c01.png)

**Comment by singhtaranjeet** [comment]
Possible duplicate of https://github.com/aissat/easy_localization/issues/370

**Comment by aissat** [comment]
Duplicate of #370
