### ISSUE TITLE
DO key name other identifiers using lowerCamelCase

### ISSUE THREAD

**Issue by ttpho** [aissat/easy_localization#456]
### Example 

With the translations content for JSON format 
```json
{
  "errorScreen": {
    "pageNotFound": "Page does not exist"
  }
}
```

After use [key generation](https://github.com/aissat/easy_localization#-localization-keys)
The name of the key will be generated 

```dart
  static const errorScreen_pageNotFound = 'errorScreen.pageNotFound';
  
 ```

### Problem 
The name of the key is `errorScreen_pageNotFound` is not using `lowerCamelCase`, 
It must be `errorScreenPageNotFound`
```dart
  static const errorScreenPageNotFound = 'errorScreen.pageNotFound';
  
 ```
### Request/Expection

Please support the key name identifiers using `lowerCamelCase` based on [Effective Dart: Style](https://dart.dev/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase
)
.

**Comment by darknight1604** [comment]
I have same problem like you describe.
Pray for author support soon

**Comment by bw-flagship** [comment]
Don't you think that it would be a valid solution to just suppress the warning in the generated file?
