### ISSUE TITLE
web

### ISSUE THREAD

**Issue by jaish702** [aissat/easy_localization#464]
Windows (UWP) (desktop) • winuwp  • windows-uwp-x64 •
Chrome (web)            • chrome  • web-javascript  • Google Chrome 99
Edge (web)              • edge    • web-javascript  • Microsoft Edge 9
[1]: Windows (windows)
[2]: Windows (UWP) (winuwp)
[3]: Chrome (chrome)
[4]: Edge (edge)
Please choose one (To quit, press "q/Q"): 3
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             41.
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui
 "R".
For a more detailed help message, press "h". To quit, press "q".      

An Observatory debugger and profiler on Chrome is available at:       
http://127.0.0.1:59211/_8ZFNDrXyFg=
--LocalizeAndTranslate : LangList[af, en] | Dir(assets/translations/) 
| Active(en.json)
The Flutter DevTools debugger and profiler on Chrome is available at: 
http://127.0.0.1:9101?uri=http://127.0.0.1:59211/_8ZFNDrXyFg=
----------------------------------------------------------------------------------------------------------------------
                                                                             this is the issue
DartUri: Unresolved uri: dart:web_sql
DartUri: Unresolved uri: dart:ui

**Comment by mdeandrea-mrmilu** [comment]
Please update this issue with more details to can help

**Comment by bw-flagship** [comment]
Closing due to lack of details
