### ISSUE TITLE
Catched bugs updating package from 1.3.1 to 1.3.3 or later versions

### ISSUE THREAD

**Issue by alectogeek** [aissat/easy_localization#47]
I use `EasyLocalizationProvider.of(context).data.changeLocale()` to change locale of my app and on 1.3.1 everything worked well, but as soon as I updated my package, I can't change my locale anymory. `changeLocale()` doesn't affect anything.

```
 Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-RU)
    • Flutter version 1.12.13+hotfix.8 at /Users/alectogeek/Documents/Programs/flutter
    • Framework revision 0b8abb4724 (8 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

```

**Comment by alectogeek** [comment]
@aissat Does closing the issue mean that it's fixed now? :)

**Comment by aissat** [comment]
@alectogeek yup try updating package 1.4.0+2
