### ISSUE TITLE
iOS locales still required?

### ISSUE THREAD

**Issue by fleeser** [aissat/easy_localization#475]
I just found out that iOS automatically translates my app with the translations I gave it through your package without even adding the key CFBundleLocalizations to the Info.plist. Is it still needed to add them? And if so, how would I add values for country specific languages like en-US or de-DE?

**Comment by pranavo72bex** [comment]
please follow this article https://freelance-flutter.medium.com/translate-info-plist-file-ios-macos-in-flutter-ea14be4427f9

**Comment by bw-flagship** [comment]
As far as I know, you at least need to add them so the language is displayed in the app store
