### ISSUE TITLE
How to load online http url json file (eg http://ip_address/en.json)

### ISSUE THREAD

**Issue by tj3333** [aissat/easy_localization#480]

**Comment by moazelsawaf** [comment]
Check out this part in the documentation [Loading translations from other resources](https://pub.dev/packages/easy_localization#-loading-translations-from-other-resources)

You will find a loader called `HttpAssetLoader`, it will do the job.

https://github.com/aissat/easy_localization_loader

**Comment by pranav-asthi** [comment]
Passed HttpAssetLoader as assetLoader and path is set to url. But showing localization for key not found warning message

**Comment by bw-flagship** [comment]
Closing it since the question is answered. If there are any further problems/questions, please open a new issue including code to reproduce
