### ISSUE TITLE
Translations aren't shown properly on app bar title and tab text.

### ISSUE THREAD

**Issue by hdpolover** [aissat/easy_localization#490]
Hello, 
Sorry if this question has been asked before. I just can't find the right keyword to look for it.

So I'm developing an app that supports a few languages including Ukrainian. The translations for this language are okay for the most part, but they won't show correctly on the app's app bar title and tab text. Text widgets work fine. Am I missing something?

![image](https://user-images.githubusercontent.com/45361999/171822242-25f25475-6657-4a04-ae61-8703c1f851ba.png)

![image](https://user-images.githubusercontent.com/45361999/171822300-ee015b3b-b628-45c6-9226-f6de906ed06e.png)

Thank you in advance.

**Comment by mahdibagjani** [comment]
I have same problem. Any answer?

**Comment by bw-flagship** [comment]
Does this issue only exists for Ukrainian?
Very strange. Please provide a small sample to reproduce and fix, thanks!

**Comment by hdpolover** [comment]
This only happens on app bars and tab texts because I use a custom font. I am still not sure why this happens. The easy way to fix it is just change the font family for these and the translations will be displayed correctly.

**Comment by bw-flagship** [comment]
And does the appBar / tab works with the custom font and without easy_localization?

**Comment by hdpolover** [comment]
yes it does

**Comment by bw-flagship** [comment]
I have no spontaneous idea what could cause that issue. Can you post code so I can reproduce?

**Comment by burakkurtarir** [comment]
I fixed that issue by adding a TextStyle to the AppBar. For example:
`
appBar: AppBar(
        title: Text(
          LocaleKeys.settings.tr(),
          style: Theme.of(context).appBarTheme.titleTextStyle,
        ),
      ),
`

**Comment by bw-flagship** [comment]
Got it. The problem is that before, you did not include the context. Without the theme, this would work:

`appBar: AppBar( title: Text( context.tr(LocaleKeys.settings) ), ),`
