### ISSUE TITLE
Command line problem?

### ISSUE THREAD

**Issue by ericf-br** [aissat/easy_localization#492]
I have a strange command-line issue.  I have the package in the pubspec, and I have code using it, so that's all good.  When I go to the command line to do anything I get... nothing.

% flutter pub run easy_localization:generate -h
%

This is supposed to display the help, but it simply returns to the prompt. 

Is my environment screwed up somehow perhaps?  

Thanks!

**Comment by GeorgeChackungal** [comment]
Same issue for me!

**Comment by cadeo111** [comment]
same for me as well

**Comment by vodemn** [comment]
+1

**Comment by ericf-br** [comment]
Just a note though, it's ONLY the -h part that is broken.  The actual generator still works properly.

**Comment by isrishu** [comment]
> Just a note though, it's ONLY the -h part that is broken. The actual generator still works properly.

no. everything is broken now. it has been broken for about 3 weeks now

**Comment by jawadincode** [comment]
Anybody with a solution of this problem ?

**Comment by IMWaqasFarooq** [comment]
same problem

**Comment by FabiKel** [comment]
+1

**Comment by madatr** [comment]
Same here +1

**Comment by adiman-dev** [comment]
when is this gonna get fixed?

**Comment by Filiponesco** [comment]
If you use default assetLoader try to add source dir argument with path. For example:
`flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart --source-dir ./assets/translations`
