### ISSUE TITLE
terminal commands exit silently on Flutter 3 and keys not generated

### ISSUE THREAD

**Issue by isrishu** [aissat/easy_localization#496]
Hi,
Thanks for the plugin. Found it very helpful.
I recently upgraded to Flutter 3 and easy_localization 3.0.1
after that, I added a translation key and executed the command in my terminal. It just exists silently and keys are not generated.
my flutter doctor output is as below

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.68.0)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!

Thanks
Srishu

**Comment by isrishu** [comment]
Hi
is there a resolution for this? I am unable to add new translations to the project.

**Comment by ChiPhanTlm** [comment]
still not fix yet !! any solution?

**Comment by isrishu** [comment]
hi
there is seriously no response to this issue? you guys do realize that the plugin is practically useless now?
if there is a fix, please let us know. we are looking forward to it eagerly

**Comment by jawadincode** [comment]
Solution :
Codeine File : flutter pub run easy_localization:generate --source-dir ./assets/translations --output-dir ./lib/presentation/resources 

Local Keys : flutter pub run easy_localization:generate -O lib/presentation/resources -f keys -o locale_keys.g.dart --source-dir ./assets/translations

**Comment by isrishu** [comment]
> Solution : Codeine File : flutter pub run easy_localization:generate --source-dir ./assets/translations --output-dir ./lib/presentation/resources
> 
> Local Keys : flutter pub run easy_localization:generate -O lib/presentation/resources -f keys -o locale_keys.g.dart --source-dir ./assets/translations

this solution does not work. both commands exit silently
is the directory "./lib/presentation/resources" supposed to be generated?
can you give steps to make the commands work properly?
again thank you very much for the plugin

**Comment by jawadincode** [comment]
> 

"./lib/presentation/resources" This is my project path where I want to generate codegen and locale keys files.

**Comment by LinMaris** [comment]
// Codegen Loader (custom path)
flutter pub run easy_localization:generate -S ./lib/resources/langs -O ./lib/generated

// Locale Keys ((custom path))
flutter pub run easy_localization:generate -S ./lib/resources/langs -f keys -o locale_keys.g.dart -O ./lib/generated


<h3 class="hash-header" id="command-line-arguments" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; font-family: &quot;Google Sans&quot;, Roboto, sans-serif; font-weight: 400; font-size: 18px; margin-top: 24px; margin-bottom: 16px; line-height: 1.25; caret-color: rgb(74, 74, 74); color: rgb(74, 74, 74);">Command line arguments<span class="Apple-converted-space"> </span><a href="https://pub.flutter-io.cn/packages/easy_localization#command-line-arguments" class="hash-link" style="box-sizing: border-box; text-decoration: none; color: rgb(204, 204, 204); cursor: pointer; opacity: 0; visibility: hidden; transition: opacity 0.5s ease-in-out 0.1s;"></a></h3>

Arguments | Short | Default | Description
-- | -- | -- | --
--help | -h |   | Help info
--source-dir | -S | resources/langs | Folder containing localization files
--source-file | -s | First file | File to use for localization
--output-dir | -O | lib/generated | Output folder stores for the generated file
--output-file | -o | codegen_loader.g.dart | Output file name
--format | -f | json | Support json or keys formats
--[no-]skip-unnecessary-keys | -u | false | Ignores keys defining nested object except for pluarl(), gender() keywords.

**Comment by isrishu** [comment]
thank you @LinMaris 
although the commands still exit silently without logging or messages, looks like the "keys" are being generated now
