### ISSUE TITLE
set locale behavior not working properly

### ISSUE THREAD

**Issue by Ahmed-Fathy-dev** [aissat/easy_localization#502]
I had a problem when I changed the language using context.setLocale(). 
Some words are translated and others only change the direction and the words are only translated when I do Hot Reload or Hot Restart

![tr_issue](https://user-images.githubusercontent.com/46655611/176160862-9b609c41-f556-4593-9e4a-ed770d89adf6.PNG)

![tr_issue2](https://user-images.githubusercontent.com/46655611/176164952-7224753b-13a7-4c21-ad1a-ca4c321b37f2.PNG)

**Comment by EhabSalah** [comment]
Same is happening with me as well, `setLocale` randomly sometimes only changes layout direction with the same translations.

**Comment by AliHoseinpoor** [comment]
i have the same problem

**Comment by ChangJoo-Park** [comment]
+1

**Comment by Jasco07122021** [comment]
+1

**Comment by aissat** [comment]
Duplicate of #552
