### ISSUE TITLE
[ERROR] easy localization: Source path does not exist

### ISSUE THREAD

**Issue by shashi007-hub** [aissat/easy_localization#503]
I have been trying to get this command line utility for code generation to run since a very long time approx. 4 hours and i had no luck but made some progress as i downgraded to flutter 2.10.5 and changed to easy-localization:3.1.0-dev 
this error keeps popping up not allowing me to generate files 

![image](https://user-images.githubusercontent.com/37980605/177953194-fb51edfb-6bfb-4dfc-85dc-a2c303d455ec.png)
here is my flutter doctor output

```
PS C:\Users\dasoj\Desktop\SIH2022\SIH Source Code\citizensapp> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 2.10.5, on Microsoft Windows [Version 10.0.19044.1766], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.3)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.0)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```
I tried using 3.02 + flutter 3 but that would just show no response and the command quietly exits out like described (here)#496

Do help me out as this virtually renders the package useless

**Comment by isrishu** [comment]
same here. i have had this issue for 3 weeks + now
the command line is broken and new keys are not generated

**Comment by isrishu** [comment]
this suggestion worked for me
https://github.com/aissat/easy_localization/issues/496#issuecomment-1201935561
