### ISSUE TITLE
upgrade intl package

### ISSUE THREAD

**Issue by mohammadne** [aissat/easy_localization#53]
```flutter_localizations from sdk depends on intl 0.16.0, dart_json_mapper >=1.3.3 is incompatible with flutter_localizations from sdk.```

**Comment by mohammadne** [comment]
if it possible , please upgrade intl to 16.0.1 version.
I am in hurry.
Thanks

**Comment by aissat** [comment]
Hi @mohammadne 
I think currently can't upgrade intl PKG , u can try downgrade dart_json_mapper PKG

**Comment by mohammadne** [comment]
why you can't ???
that version of ```dart_json_mapper PKG``` has some problems.

**Comment by mohammadne** [comment]
currently , I have to use ```flutter_translate 1.5.7```  instead of your plugin

**Comment by aissat** [comment]
@mohammadne okay bro as u like
When I upgraded intl PKG 
```
ERR: Because easy_localization depends on flutter_localizations any from sdk which depends on intl 0.16.0, intl 0.16.0 is required.
 So, because easy_localization depends on intl ^0.16.1, version solving failed.


```

Thanks 🙂 and I'm sorry for can't help u
