### ISSUE TITLE
easy_localization error in MaterialApp flutter New Version

### ISSUE THREAD

**Issue by Syed95github** [aissat/easy_localization#539]
After upgrading the flutter latest version,
I started to get the following error "type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast".

After removing the following configurations (below image) from Material the error is gone but the localization is not working.
Also I am using Flutter Flavorizer.
Kindly share if anyone face the issue.
Thanks

![image](https://user-images.githubusercontent.com/112315578/206448573-0fff39eb-7afd-45e1-9a9f-49e8ce4daad8.png)

**Comment by Syed95github** [comment]
solved

**Comment by DirtyNative** [comment]
@Syed95github And how did you resolve it?

**Comment by Mahaalosaimi** [comment]
> solved

how did you solve it?
i have the same issue

**Comment by Syed95github** [comment]
I was not giving the correct language json.
Now I am providing en and en-us as well.
