### ISSUE TITLE
Error translation key on TextFormField 

### ISSUE THREAD

**Issue by didierboka** [aissat/easy_localization#550]
Hello i have an error when try to had translation in textLabel for widget TextFormField.
Key for translation exist well.

<img width="529" alt="Screen Shot 2023-02-06 at 22 20 56" src="https://user-images.githubusercontent.com/96589365/217101055-5448f250-8e94-41d9-bd1f-493d7330b35f.png">

**Comment by yassinsameh** [comment]
Because you're using the InputDecoration() as a const, while .tr() changes the text so this value is not a constant.
