### ISSUE TITLE
let's update packages

### ISSUE THREAD

**Issue by guyluz11** [aissat/easy_localization#560]
I have version conflict with `intl` package version that exists in this package.

It is also decreasing the package score

```dart
Because network_tools >=3.1.0 depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, network_tools >=3.1.0 is incompatible with flutter_localizations from sdk.
And because easy_localization >=2.1.0+1 depends on flutter_localizations from sdk, network_tools >=3.1.0 is incompatible with easy_localization >=2.1.0+1.
So, because cybear_jinni depends on both easy_localization ^3.0.1 and network_tools ^3.1.0, version solving failed.
pub get failed
command: "/home/guyluz/snap/flutter/common/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/home/guyluz/snap/flutter/common/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/home/guyluz/.pub-cache",
}
exit code: 1
```

![Screenshot_20230309_083311_Firefox](https://user-images.githubusercontent.com/9304740/223939892-ca67aabb-c11e-4b4a-a461-ebb2d70789aa.jpg)

**Comment by Spiderbezno** [comment]
Any news about this, I have the same problem

**Comment by guyluz11** [comment]
It looks like `flutter_localizations` flutter package is not updated as well to intl 0.18.0 so I can't open pr with this change

> Because every version of flutter_localizations from sdk depends on intl 0.17.0 and easy_localization depends on intl ^0.18.0,
>   flutter_localizations from sdk is forbidden.
> So, because easy_localization depends on flutter_localizations from sdk, version solving failed.
> 

If someone open pr to flutter team about that please share a link to the issue so that we will be able to upvote it.

**Comment by societates-civis** [comment]
Same here - upgraded Xcode + Flutter for the April app store restrictions and now localisation 
tried also with easy_localization: ^3.0.2-dev.5

**Comment by guyluz11** [comment]
@societates-civis you have referenced the wrong `flutter_localization` package

I feel for it too in the past 😂

We are using `flutter_localizations` with s in the end in pubspec.yaml package that is part of flutter and is being developed by flutter team.

**Comment by ingmferrer** [comment]
https://github.com/flutter/flutter/issues/123103#issuecomment-1477750509

https://github.com/dart-lang/i18n/issues/458

**Comment by guyluz11** [comment]
If this issue affects you please upvote this issue https://github.com/dart-lang/i18n/issues/458 so that the Flutter team will put more focus on it.

**Comment by Alex-web0** [comment]
POSSIBLE WORKAROUND

for anyone facing this issue and maybe not able to use the package just add these to your YAML file

```
dependency_overrides:
  intl: ^0.17.0
```

**Comment by guyluz11** [comment]
Or the other way around which I think will be better for most uses cases

```dart
dependency_overrides:
  intl: ^0.18.1
```

**Comment by bw-flagship** [comment]
Maybe I did not understand the problem correctly, but we can just update the dependency, can't we?
I created a PR to update intl and dart, please review:
https://github.com/aissat/easy_localization/pull/581

**Comment by rakib205** [comment]
When the new update will be released? @aissat @bw-flagship

**Comment by bw-flagship** [comment]
I created #582 and waiting for a maintainer review. If I understand the pipeline correctly, it should then release automatically after it is merged with a [pub] in the commit message

**Comment by bw-flagship** [comment]
please check out Version 3.0.2
