### ISSUE TITLE
Cannot translate language in Flutter

### ISSUE THREAD

**Issue by tony123S** [aissat/easy_localization#565]
I have changed the language setting from English to Chinese, but app still displays English.

**main.dart**
```

 runApp(EasyLocalization(
      supportedLocales: const [Locale('en', 'US'), Locale('zh-CN', 'CN')],
      path: 'assets/translations',
      child: const App(),
    )
```
**zh-CN.json**

`"hello": "你好",`

**widget.dart**

`Text('hello'.tr());`

Is it because the languageCode and countryCode wrong?

**Comment by Handelika** [comment]
Have your tried startLocale property?

```
runApp(EasyLocalization(
      supportedLocales: const [Locale('en', 'US'), Locale('zh-CN', 'CN')],
      startLocale: Locale('zh-CN','CN'),
      path: 'assets/translations',
      child: const App(),
    )
```

**Comment by Muddassar087** [comment]
Chinese locale is not working any information why?

**Comment by derjohng** [comment]
try Locale('zh', 'CN'), not Locale('zh-CN', 'CN')
