### ISSUE TITLE
Release app is stuck after adding the localization delegates.

### ISSUE THREAD

**Issue by abinvs-2019** [aissat/easy_localization#575]
localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,

**Comment by bw-flagship** [comment]
@abinvs-2019 There is nothing we can reproduce/investigate here. If the problem still persists, please add some more details and a sample to reproduce

**Comment by abinvs-2019** [comment]
No, i found the issue,
this issue was because i have added the localization in pubspec.yaml file,
