### ISSUE TITLE
Not compatible with intl 0.18.0

### ISSUE THREAD

**Issue by Alex-web0** [aissat/easy_localization#577]
The plugin doesn't work with the newer versions of the Flutter SDK as it relies on intl package from the SDK with version 0.17.0 while the SDK provides 0.18.0

A workaround is to override dependencies by adding 
```
dependency_overrides:
  intl: ^0.17.0
```

I hope the plugin gets migrated to fit newer Flutter SDK dependencies soon

**Comment by thibaultzanini** [comment]
It appears to be a duplicated issue: https://github.com/aissat/easy_localization/issues/560

**Comment by bw-flagship** [comment]
please check out Version 3.0.2
