### ISSUE TITLE
pub.dev authentication is broken

### ISSUE THREAD

**Issue by bw-flagship** [aissat/easy_localization#584]
The release pipeline failed with the following text:

```
OAuth2 authorization failed (Bad Request).
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A41601&code_challenge=5cDWa23PnYCfadLCGjJHrsRy9Z9oWDBGY-4YwvZLoEE&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".
```

Pipeline run:
https://github.com/aissat/easy_localization/actions/runs/4971561355/jobs/8896196908

@aissat I think you have to renew the github secrets, only you can do it, thanks!

**Comment by aissat** [comment]
Can send me your mail I'll add you as publisher

**Comment by bw-flagship** [comment]
My mail is benjamin.weber@flagship-apps.de
In addition, I would need permissions to edit github secrets

**Comment by aissat** [comment]
> My mail is [benjamin.weber@flagship-apps.de](mailto:benjamin.weber@flagship-apps.de) In addition, I would need permissions to edit github secrets

check your mail

**Comment by aissat** [comment]
@bw-flagship, maybe we need to update this  
https://github.com/dart-lang/setup-dart/blob/08de7e0c9a57cb3229b052af11c7f8eae4a845bd/.github/workflows/publish.yml#L22-L44

```ymal
jobs:
  publish:
    name: 'Publish to pub.dev'
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
```

**Comment by aissat** [comment]
@bw-flagship, maybe we need to update this  

https://github.com/aissat/easy_localization/blob/3789480c92ae66371d36ef47086cc7d982281665/.github/workflows/main.yml#L42-L80

```ymal
jobs:
  publish:
    if: "(contains(github.event.head_commit.message, '[pub]') && 
             contains(' 
               refs/heads/master 
               refs/heads/develop 
               refs/tags 
               refs/tags/releases', 
               github.ref)) || 
             startsWith(' 
               refs/tags/ 
               refs/tags/releases/', 
               github.ref)
    name: 'Publish to pub.dev'
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
```
![Screenshot from 2023-05-14 17-32-16](https://github.com/aissat/easy_localization/assets/4768203/f82eaaba-c7f7-490f-83a2-e10cdab232a3)

**Comment by rolandtolnay** [comment]
Any updates on this?

I updated to Flutter 3.10.0 yesterday, and now this version conflict is blocking me from running pub get, unless I downgrade.

**Comment by bw-flagship** [comment]
@rolandtolnay Fixing the pipeline is still work in progress. If you need a quick fix, you can depend on the commit directly:

```
easy_localization:
    git:
      url: https://github.com/aissat/easy_localization.git
      ref: fa92405
```
