### ISSUE TITLE
Because easy_localization >=3.0.0-nullsafety depends on flutter_localizations from sdk which depends on intl 0.18.0, easy_localization >=3.0.0-nullsafety requires intl 0.18.0.

### ISSUE THREAD

**Issue by AmirMulla14** [aissat/easy_localization#589]

**Comment by AmirMulla14** [comment]
Because easy_localization >=3.0.0-nullsafety depends on flutter_localizations from sdk which depends on intl 0.18.0, easy_localization >=3.0.0-nullsafety requires intl 0.18.0.

**Comment by pascariandrei** [comment]
flutter downgrade solved my issue

**Comment by aissat** [comment]
@AmirMulla14  check new version `easy_localization: ^3.0.2`

**Comment by naranbat7** [comment]
dependency_overrides:
  intl: any
