### ISSUE TITLE
Adding Sentry: Zone mismatch

### ISSUE THREAD

**Issue by KundKMC** [aissat/easy_localization#596]
Hi guys,

I found a problem when using easy_localization together with the sentry_flutter package. Just extending the example app like:

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  await Sentry.init((options) {
    options.dsn =
        ('');
    options.tracesSampleRate = 0.5;
  },
      appRunner: () => runApp(EasyLocalization(
            supportedLocales: [
              Locale('en', 'US'),
              Locale('ar', 'DZ'),
              Locale('de', 'DE'),
              Locale('ru', 'RU')
            ],
            path: 'resources/langs',
            child: MyApp(),
      )));
}`

Returns a Zone mismatch.

This is not suppose to happen. Is this an easy or a sentry issue?

**Comment by bw-flagship** [comment]
The missing linebreaks make the code very hard to read. However, the flutter logs are quite helpful regarding that error:

```
════════ Exception caught by Flutter framework ════════════════════════════════════
The following assertion was thrown during runApp:
Zone mismatch.

The Flutter bindings were initialized in a different zone than is now being used.
This will likely cause confusion and bugs as any zone-specific configuration will
inconsistently use the configuration of the original binding initialization zone or
this zone based on hard-to-predict factors such as which zone was active when a
particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the
binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before
the bindings are initialized (i.e. as the first statement in `void main() { }`).
[...]
═══════════════════════════════════════════════════════════════════════════════════

```

So most likely the reason is your code, maybe it is Sentry, but it's not easy_localization, therefore closing this
