### ISSUE TITLE
after updating version 1.4.1 i cannot use GlobalMaterialLocalizations  

### ISSUE THREAD

**Issue by MuthuHere** [aissat/easy_localization#60]
![image](https://user-images.githubusercontent.com/18752533/75507960-87602d00-5a1d-11ea-8086-66cb035988b0.png)

**Comment by spiritinlife** [comment]
@MuthuHere Add this in your dependencies
flutter_localizations:
sdk: flutter

Take a look here for more information https://flutter.dev/docs/development/accessibility-and-localization/internationalization
