### ISSUE TITLE
Tests failing when JSON file size is > 52 kbs

### ISSUE THREAD

**Issue by Arjun544** [aissat/easy_localization#608]
We are in the process of developing a large-scale app with over 400 screens. To support multiple languages, we have implemented an easy localization package that utilizes JSON files for translations.

Currently, we have two languages available: English and Portuguese. Initially, everything was working smoothly until the JSON file sizes reached 52 KBs, containing around 1404 lines of data.

Unfortunately, we encountered a problem where all our unit tests started failing. As a Flutter developer, I spent two days diligently debugging the issue and eventually identified that the file size was the root cause.

It's important to note that this issue only manifests itself during the execution of Unit and Integration tests. When running the app in debug or release modes, there are no problems.

I gained confidence in my diagnosis by performing two specific tests:

1. I removed some translations from the JSON file and ran the Unit tests again, which resulted in all of them passing successfully.

2. Additionally, I tried compressing the JSON file using an online file compressor, reducing its size from 52 KBs to 36 KBs, and once again, all Unit tests passed without any issues.

The English translation file is here for reference: https://file.io/aVhOSKPheae5

Now, let me share the code for our Localization provider, which is responsible for fetching translations from the JSON files.

**Note**: All JSON files that are used in the following code are available in the Assets folder and correctly added in pubspec.yaml.

```
import 'package:easy_localization/easy_localization.dart';
import 'package:tiers_app/controllers/localization_controller.dart';
import 'package:tiers_app/core/resources/assets_manager.dart';

import '../flutter_imports.dart';
import '../packages_imports.dart';

class LocalizationProvider extends GetView<LocalizationController> {
  final Widget child;
  final Locale? startLocale;

  const LocalizationProvider(
      {super.key, required this.child, this.startLocale});

  @override
  Widget build(BuildContext context) {
    Get.put(LocalizationController());
    return Obx(
      () => controller.supportedLocales.isEmpty
          ?
          // TODO:  Replace Container with some kind of loader
          Container(
              color: context.theme.scaffoldBackgroundColor,
            )
          : EasyLocalization(
              startLocale:
                  controller.supportedLocales.contains(Get.deviceLocale) == true
                      ? startLocale ?? Get.deviceLocale
                      : controller.supportedLocales.first,
              supportedLocales: controller.supportedLocales,
              path: AssetsManager.translationsCommon,
              fallbackLocale: controller.supportedLocales.first,
              child: child,
            ),
    );
  }
}
```

Localization Controller code: 

```
import 'dart:convert';

import 'package:tiers_app/core/packages_imports.dart';
import 'package:tiers_app/core/resources/assets_manager.dart';
import 'package:tiers_app/core/resources/translation_loaders.dart';

import '../core/flutter_imports.dart';

class LocalizationController extends GetxController
    with WidgetsBindingObserver {
  final GlobalKey<NavigatorState> globalKey = GlobalKey<NavigatorState>();
  RxList<Locale> supportedLocales = <Locale>[].obs;

  @override
  void onInit() async {
    await getSupportedLocales();
    WidgetsBinding.instance.addObserver(this);
    super.onInit();
  }

  @override
  void didChangeLocales(List<Locale>? locales) {
    TranslationLoaders.changeLocale(
      globalKey.currentState!.context,
      locales![0].languageCode,
      locales[0].countryCode!,
    );
  }

  @override
  void dispose() {
    super.dispose();
    WidgetsBinding.instance.removeObserver(this);
  }

  Future getSupportedLocales() async {
    final response = await rootBundle.loadString(
      '${AssetsManager.translationsCommon}/supported_locales.json',
    );
    final Map<String, dynamic> locales = json.decode(response);

    for (final locale in locales['locales']) {
      supportedLocales.add(
        Locale(
          locale['languageCode'],
          locale['countryCode'],
        ),
      );
    }
    supportedLocales.refresh();
  }
}
```

**Comment by baraghiffari** [comment]
@Arjun544 Do you resolve the issue ? I'm planning to migrate to this plugin because i use other plugin and it hasn't been updated by its author for 2 year, i already had around 1K lines on my json file.
