### ISSUE TITLE
The library does not set Intl.defaultLocale on change

### ISSUE THREAD

**Issue by danilofuchs** [aissat/easy_localization#63]
Currently, the library caches the default locale via SessionManager. But, when retrieving this data, it does not overwrite the `Intl.defaultLocale` variable. Thus, native Intl formatting is broken

**Comment by danilofuchs** [comment]
What I did to solve this in my project is adding the following into the `MaterialApp` main component:
```dart
...
        builder: (context, child) {
          final newLocale = Localizations.localeOf(context).toLanguageTag().replaceAll("-", "_");
          if (newLocale != null && newLocale != Intl.defaultLocale) {
            Intl.defaultLocale = newLocale;
          }
          return child;
        },
...
```

**Comment by spiritinlife** [comment]
@danilofuchs So Intl.defaultLocale should be set when the locale is changed ?

**Comment by archie-sh** [comment]
@aissat I may be wrong but looking at the code I think your fix for this was lost when you moved from provider to bloc
