### ISSUE TITLE
How to specify the starting locale of app

### ISSUE THREAD

**Issue by mohammadne** [aissat/easy_localization#65]
suppose I have 4 locals.
I want if there is no any saved current local in sharePrefs , load one of them.
the behavior at now is to load en_US first.

Thanks.

**Comment by aissat** [comment]
For default locale load take it from your default phone localization , I like your point I thought I'll added this like options

**Comment by mohammadne** [comment]
if you added a property to take the starting locale is good for that purpose. 
And if it is null, then you can take it from phone default localization. 
And you should ignore this property if there is a local in share preference. 
Thanks
