### ISSUE TITLE
You are antisemitic

### ISSUE THREAD

**Issue by ItayBarFaye** [aissat/easy_localization#657]
You are antisemitic that number one issue! You should all fixed that before anything else!!!!

**Comment by Blacktaler** [comment]
You are fascist, rapist and baby killer!!!
Children of hitler!!!

**Comment by ItayBarFaye** [comment]
It seems there might be some confusion. The group you're referring to might be Hamas! 
If you are too ignorant do some research, stop spreading lies and hate!!! 
STOP SUPPORTING TERROR!!!!

**Comment by Blacktaler** [comment]
> It seems there might be some confusion. The group you're referring to might be Hamas! If you are too ignorant do some research, stop spreading lies and hate!!! STOP SUPPORTING TERROR!!!!

Hamas didn't kill 35.000 civilians though. Stop supporting terroristrael

**Comment by Blacktaler** [comment]
> Hamas is a terror organization, supporting them mean you are also a terrorist! And only move by hate.
If you had brain, you would do some research, and see who is the real evil. Brainless zombies are even worse than terrorist. So get  your brainless terrorist head  out of here.

**Comment by ItayBarFaye** [comment]
Dumbass ignorant! Take your head out of your ass and do some research, learn the truth. You are blindly following lies.
