### ISSUE TITLE
convert ensureInitialized() to internal func

### ISSUE THREAD

**Issue by aissat** [aissat/easy_localization#71]
@danilofuchs @spiritinlife I think would be best if we hiding `ensureInitialized()` from `main() ` and make `main()`  without `asycn` like a default 
[Good or Bad: Declaring main method async in Dart / Flutter](https://stackoverflow.com/questions/56129121/good-or-bad-declaring-main-method-async-in-dart-flutter)
```dart
void main() {
  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: [Locale('en', 'US'), Locale('ar', 'DZ')],
    path: 'resources/langs',
  ));
}
```

**Comment by spiritinlife** [comment]
How are we going to initialise the language to the previous used one ? if not in main.

**Comment by danilofuchs** [comment]
The link you sent says it doesn't introduce any bad behaviour. I think we should keep it there, as it makes sure the user does not see a _flick_ of the default language being changed to the saved language, which would be a bad experience.

@spiritinlife could we do this loading inside the delegate's load method? It is async and runs before the initial paint (I think it does, anyway). Or, we could call it on a static factory, hiding the constructor, as seen here: https://stackoverflow.com/questions/54549235/dart-await-on-constructor

**Comment by spiritinlife** [comment]
@danilofuchs delegate is interesting have to test this.
The static factory could be used i think to remove the need for `static Locale _savedLocale;`
