### ISSUE TITLE
Not able to load json file from backend

### ISSUE THREAD

**Issue by Ajaystefin** [aissat/easy_localization#72]
The plugin works good with json files as assets. But I am facing this error while I provide a http url in path and changed 'assetloader' to 'NetworkAssetLoader'. I need the json file to load from a HTTP url

```
runApp(EasyLocalization(
      child: MyApp(),
      supportedLocales: [Locale('en', 'US'), Locale('ar', 'DZ')],
      fallbackLocale: Locale('en', 'US'),
      path: 'https://url.com',
      useOnlyLangCode: true,
      // optional assetLoader default used is RootBundleAssetLoader which uses flutter's assetloader
      // assetLoader: RootBundleAssetLoader()
      assetLoader: NetworkAssetLoader()
      // assetLoader: TestsAssetLoader()
      // assetLoader: FileAssetLoader()
      // assetLoader: StringAssetLoader()
      ));
```
It is by default using the 'RootBundleAssetLoader'. How do I change this. Please help. Thanks.

**Comment by Ajaystefin** [comment]
problem is that it is not added as a parameter in _EasyLocalizationDelegate in easy_localization_app.dart

**Comment by spiritinlife** [comment]
@Ajaystefin  Thank you for reporting this issue. 
Keep in mind that this is not released yet and still under development. You should better import the package from pub and not from git.

**Comment by Ajaystefin** [comment]
Thanks :)
