### ISSUE TITLE
problems with plural

### ISSUE THREAD

**Issue by joanfortes** [aissat/easy_localization#73]
in this case String tittle = 'values.settings'.plural(2); it returns Two in tittle using this string, but when i use this form String tittle = 'values.settings'.plural(3); it returns the correct value for the tittle

Json path:

"values":{
"settings": {
      "one": "ajuste",
      "other": "ajustes",
      "zero": "ajuste"
    },
}

Images:
using counter 2 in plural:
![Captura de Tela_dde-desktop_20200305225720](https://user-images.githubusercontent.com/49821124/76042924-d41f9880-5f34-11ea-9f0f-458cbe5d8646.png)
using counter 3 in plural:
![Captura de Tela_Área de Seleção_20200305225654](https://user-images.githubusercontent.com/49821124/76042933-da157980-5f34-11ea-9777-6e2c30c38221.png)

**Comment by aissat** [comment]
@joanfortes 
just added 
```json
"values":{
"settings": {
"one": "ajuste",
"tow":"ajustes",
"other": "ajustes",
"zero": "ajuste"
},
}
```
