### ISSUE TITLE
Version 1.4.1 locale only return 'en'

### ISSUE THREAD

**Issue by gjrjf** [aissat/easy_localization#74]
hi

version 1.4.1

locale only return 'en'

but, 1.4.0 is ok

my code

![스크린샷 2020-03-06 오후 3 25 48](https://user-images.githubusercontent.com/19974022/76058103-cadb0e00-5fbe-11ea-8dd2-72f19cc39d9e.png)

![스크린샷 2020-03-06 오후 3 22 12](https://user-images.githubusercontent.com/19974022/76057992-7b94dd80-5fbe-11ea-83ae-fb8d640c34a4.png)

=> only return 'en', Phone lang is 'ko'

same issue link : 
https://github.com/flutter/flutter/issues/14128#issuecomment-578092739

**Comment by carlos-labrador** [comment]
I got same problem.

**Comment by Jbz797** [comment]
Same here

**Comment by aissat** [comment]
Thanks 
@carlos-labrador @Jbz797
I'm working to fix this, preparing to release version 2.0.0

**Comment by aissat** [comment]
try the new version
now can get selected locale by:
```dart
log(Intl.defaultLocale);
//or 
log(EasyLocalization.of(context).locale.toString());
```

**Comment by Overman775** [comment]
I got same problem in 2.0.0+1
When i delete fallbackLocale bug gone...

```
Intl.defaultLocale =
      ui.window.locale.languageCode + '_' + ui.window.locale.countryCode;

  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: [
      const Locale('ru'),
      const Locale('de'),
      const Locale('en'),
      const Locale('es'),
      const Locale('it'),
      const Locale('pl')
    ],
    path: 'assets/langs',
    useOnlyLangCode: true,
    fallbackLocale: Locale('en'),
  ));
}
```

```
print(Intl.defaultLocale);  /// ru_RU
print(EasyLocalization.of(context).locale.toString()); /// en
```
