### ISSUE TITLE
Allow simpler plural definition

### ISSUE THREAD

**Issue by wottpal** [aissat/easy_localization#75]
Hi! I know that defining all plural variations ("zero", "one", "two", "few", "many", "other") is the [official unicode-way](http://cldr.unicode.org/index/cldr-spec/plural-rules) but in most languages only three of them are relevant ("zero", "one", "other"). If I use the Dart Intl package it lets me define only those three values and I'm fine. But when I do the same with this package it prints the identifier for example the value 2. (`item.two` instead of using the value of `item.other` instead). I would like to use this shorthand with this package too as currently the files became very unreadable very quick.

Cheers, Dennis

**Comment by aissat** [comment]
#121
