### ISSUE TITLE
Is there a way to add language to tooltips?

### ISSUE THREAD

**Issue by Ajaystefin** [aissat/easy_localization#76]
thanks for the package. Is there a way to add localisation to tooltips?. Thanks

**Comment by aissat** [comment]
@Ajaystefin 
Can you explain more?

**Comment by Ajaystefin** [comment]
Sure, I meant for tooltip parameter in floating action buttons, etc. Also within the tooltip widget available with flutter

**Comment by aissat** [comment]
@Ajaystefin  can do this 
```dart
Tooltip(
                message: 'My Account'.tr(),
               )
// Or 
Tooltip(
                message: tr('My Account'),
                .....
                  ), 
```

**Comment by Ajaystefin** [comment]
didn't see that, thanks
