### ISSUE TITLE
Problem saving sharedPreferences locale value

### ISSUE THREAD

**Issue by hkndzdr** [aissat/easy_localization#78]
EasyLocalization.of(context).locale = Locale('en', 'US');

When this method used in v2.0.0, it writes incorrectly to the sharedPreferences file. You can see the details in the video in the link.

[https://www.youtube.com/watch?v=SVwjwuy3I9A](url)

**Comment by aissat** [comment]
@hkndzdr  don't worry about it this just msg 
this it saved value befor updated

**Comment by hkndzdr** [comment]
The problem is not message. Therefore, language changes are not possible when you close and open the application.

Inside the sharedpreferences file is also incorrect.

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="flutter.codeCa">TR</string>
    <string name="flutter.codeLa">en</string>
</map>
```

**Comment by hkndzdr** [comment]
@aissat This problem started again with the version 2.0.1

**Comment by aissat** [comment]
check #93
