### ISSUE TITLE
Language switcher

### ISSUE THREAD

**Issue by Dreamersoul** [aissat/easy_localization#82]
library version: 2.0.0+1
I am implementing a language switcher page when selecting a language like the following 
```dart
EasyLocalization.of(context).locale = Locale("ar");
Navigator.of(context).pushReplacementNamed("/OnBoarding");            
```
the first page loaded is in the previous locale, my workaround is

```dart
EasyLocalization.of(context).locale = Locale("ar");

Future.delayed(Duration(milliseconds: 300), (){
    Navigator.of(context).pushReplacementNamed("/OnBoarding");
});
```
is there is a way to await the switching so i can do something after it is completed?
proposed solution

```dart
EasyLocalization.of(context).locale(Locale("ar")).then(, (){
    Navigator.of(context).pushReplacementNamed("/OnBoarding");
});
```

**Comment by aissat** [comment]
@Dreamersoul plz need example

**Comment by Dreamersoul** [comment]
weird i tried replicating it and it didn't show up again, thank you for your time
