### ISSUE TITLE
changeLocale error

### ISSUE THREAD

**Issue by anas-aw** [aissat/easy_localization#84]
when i use 
data.changeLocale(Locale("en","US"));

get this error 
Class '_EasyLocalizationState' has no instance method 'changeLocale' with matching arguments.
Receiver: Instance of '_EasyLocalizationState'
Tried calling: changeLocale(Instance of 'Locale')
Found: changeLocale({Locale locale}) => void

**Comment by aissat** [comment]
@anas-aw please check example 
We removed this `data.changeLocale(Locale("en","US"));`
