### ISSUE TITLE
App only recognize en_US

### ISSUE THREAD

**Issue by jucaesmanhoto** [aissat/easy_localization#85]
I've trying to implement easy_localization without success. It keeps getting Locale('en', 'US') as Locale, independently on the device's selected language. 
The only way i found to make it work was to put the desired locale (Locale('pt', 'BR')) in the fallbackLocale field. But i think that this is not the desired funtionality, is it? 
I new to flutter so, i don't know exactly how can i help and contribute to improve the package. But i'll be glad to help, if i can.

**Comment by aissat** [comment]
@jucaesmanhoto plz need example

**Comment by jucaesmanhoto** [comment]
1st - I followed the instructions at the pub.dev;
2nd - I made 2 files (pt-BR.json and en-US.json);
3rd - run the app. It red the en-US.json, as expected;
4th - changed the language in the device's settings to brazilian portuguese;
5th - run the app once again. the app was still reading the en-US.json.

I went through the pub.dev exemple for many times and I'm prety sure that i'm following right.

*Also, I noticed that is missing in the documentation something about the right place and name for the .json files.  Could i help on that?

**Comment by Overman775** [comment]
easy_localization package save locale in SharedPreferences

try reset locale 
```
  var _prefrences = await SharedPreferences.getInstance();
  _prefrences.setString('codeLa', null);
  _prefrences.setString('codeCa', null);
```

**Comment by aissat** [comment]
@jucaesmanhoto check  #83

**Comment by jucaesmanhoto** [comment]
> easy_localization package save locale in SharedPreferences
> 
> try reset locale
> 
> ```
>   var _prefrences = await SharedPreferences.getInstance();
>   _prefrences.setString('codeLa', null);
>   _prefrences.setString('codeCa', null);
> ``

Still not working. I'm checking the 'codeLa' and 'codeCa' and they're null. 
But, even then, the language is always 'en-US'. It only changes if i set fallbackLangage to 'pt-BR'.
