### ISSUE TITLE
locale only return 'en' 2.0.0+1

### ISSUE THREAD

**Issue by Overman775** [aissat/easy_localization#86]
Hi!

I got problem in 2.0.0+1, locale alwais return 'en'
When i delete fallbackLocale bug gone...

```
Intl.defaultLocale =
      ui.window.locale.languageCode + '_' + ui.window.locale.countryCode;

  runApp(EasyLocalization(
    child: MyApp(),
    supportedLocales: [
      const Locale('ru'),
      const Locale('de'),
      const Locale('en'),
      const Locale('es'),
      const Locale('it'),
      const Locale('pl')
    ],
    path: 'assets/langs',
    useOnlyLangCode: true,
    fallbackLocale: Locale('en'),
  ));
}
```

```
print(Intl.defaultLocale);  /// ru_RU
print(EasyLocalization.of(context).locale.toString()); /// en
```
P.S.: i clean every time SharedPreferences for reset saved local

**Comment by aissat** [comment]
@Overman775 `fallbackLocale` to specify the starting locale of app #65
plz if possible explain more wat u want exatly

**Comment by Overman775** [comment]
I try get device locale (ui.window.locale.languageCode) an set as default.
But if language not suportet then get 'En' locale.

Maybe duplicate #85, but i don't see code 😃

**Comment by aissat** [comment]
@Overman775 u can get Device locale  by `Intl.systemLocale`  #83

**Comment by Overman775** [comment]
systemLocale is always return en_EN if you don't run [findSystemLocale()](https://api.flutter.dev/flutter/intl/Intl/systemLocale.html), i use ui.window.locale to get device locale and set manualy, its work fine.

I think the problem is in the concept of fallbackLocale
fallbackLocale != starting locale, its wrong...  fallbackLocale should set which language to use when there is no locale in supportedLocales.

**Comment by hkndzdr** [comment]
> @Overman775 u can get Device locale by `Intl.systemLocale` #83

@Overman775  is right about this. Unfortunately Intl.systemLocale which you recommend to me returns 'en_EN'. Need to use "ui.window.locale". I expect you to add this feature to the package.

**Comment by Overman775** [comment]
#89 fix fallbackLocale and now this package get locale from device 😃
