### ISSUE TITLE
Add named arguments

### ISSUE THREAD

**Issue by marinat** [aissat/easy_localization#88]
Some translates need swap arguments, but I can't do that without named arguments.

**Comment by aissat** [comment]
@marinat plz examlpe

**Comment by marinat** [comment]
For example translator using lokalise service do not understand what word I meant:
'{} lesson for student {} on {} will be deleted'
Phrase variant: weekly lesson for student Alex on 31 December will be deleted
For web front-end they use arguments like:
'{lesson_type} lesson for student {student_name} on {lesson_time} will be deleted'

**Comment by marinat** [comment]
One more example: in turkish words in sentence may be in different order than in english. So it's hard to save unnamed parameters order.

**Comment by vinnytwice** [comment]
@aissat I see that it now supports named arguments but I can't figure out how to use it. In the example code I don't see it being used right?

**Comment by aissat** [comment]
@vinnytwice today will be available dev version

**Comment by aissat** [comment]
@vinnytwice today will be available dev version

**Comment by aissat** [comment]
@vinnytwice @marinat try this

```yaml
dependencies:
  easy_localization: ^2.2.0-dev
```
example: 
```json
"msg_named": "{} are written in the {lang} language",
```

```dart
 Text(LocaleKeys.msg_named).tr(namedArgs: {'lang': 'Dart'}, args: ['Easy localization']),
```

**Comment by vinnytwice** [comment]
@aissat  I was having a look at the sample app trying to understand a bit everything and I saw it. For version ^2.2.0-dev then tr. method accepts named args? is it just one or a list of args?
Thank you very much for the repo!

**Comment by aissat** [comment]
@vinnytwice. It accepted tow type
Named argument with list argument

**Comment by AlaaEldeenYsr** [comment]
> "msg_named": "{} are written in the {lang} language",

How can i give the argument values specific style, for example the whole line is not bold except the argument value be bold.

**Comment by 3ace** [comment]
@AlaaEldeenYsr I think you should separate your string for now, and display them using [RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) widget.

other option, add a token inside the string and split it inside your code to be stylized before adding it to the RichText widget

**Comment by AlaaEldeenYsr** [comment]
Alright is the named arguments feature version is on the pub or on a specific branch here ?
@3ace

**Comment by 3ace** [comment]
@AlaaEldeenYsr please refer to [this reply](https://github.com/aissat/easy_localization/issues/88#issuecomment-615834671) by @aissat
