### ISSUE TITLE
Incorrect Device Locale

### ISSUE THREAD

**Issue by davidmokos** [aissat/easy_localization#94]
Hi, I'm using the latest version `easy_localization: ^2.0.1+1`.
The `findSystemLocale()` functions returns en_CZ on my physical iPhone.
```
flutter: en_CZ
[log] easy localization: Set locale en_US
[Instance of '_EasyLocalizationLocale'_saveLocale] en_US
```

However, as you can see, in my settings, I have correctly selected Czech language and region.
Any ideas where it might come from?

Thanks

![IMG_879C3434614F-1 2](https://user-images.githubusercontent.com/22908592/77075691-04663d00-69f3-11ea-8442-738fe580a774.jpeg)

**Comment by Overman775** [comment]
Same issue, i think error in latest commit #93

**Comment by aissat** [comment]
@davidmokos check flutter/flutter#14128

**Comment by aissat** [comment]
@davidmokos 
https://github.com/aissat/easy_localization/pull/95#issuecomment-601898629
