### ISSUE TITLE
Black screen problem when opening the app.

### ISSUE THREAD

**Issue by hkndzdr** [aissat/easy_localization#96]
Using the sample application in the repo, I recorded a video showing the error in both the emulator and the real device. You can see the obvious error in the emulator. It happens very fast on the real device. You can see 16,22 and 26 seconds in the video by watching at a speed of 0.25. Occurs when getting locale values from shared preferences. I have the same problem in my own applications where installed the this plugin. An extremely frustrating situation.

[https://www.youtube.com/watch?v=idAvuFG6BmI](url)

**Comment by aissat** [comment]
@hkndzdr u mean this #74  and  about black screen check this https://github.com/flutter/flutter/issues/47582

**Comment by hkndzdr** [comment]
There is no such problem in the flutter default sample application. There is no problem in any application where I don't integrate the Easy_localization plug-in. If I remove the plug-in from the application, the problem is resolved. Trying what is written here isn't a solution for me. I also tried all of them one by one.

**Comment by AlaaEldeenYsr** [comment]
Screenshot from the EasyLocalizationState class
![image](https://user-images.githubusercontent.com/52201392/77238968-2a036a00-6bde-11ea-8018-6198115a2f7e.png)

If you wrapped the EasyLocalization top level Widget with another Container Widget its color white you will see white screen instead of black screen, The problem as you see in the screenshot is that the FutureBuilder Widget returns a Container Widget represents the top level Widget of your app and that Container has a transparent background color as default so what appears until the easy localization FutureBuilder get completed is a transparent Container no thing above it and no thing in flutter means black.

Try what i have done here and your problem is solved.
![image](https://user-images.githubusercontent.com/52201392/77239220-ca5a8e00-6be0-11ea-9193-22bfdbd73f53.png)

**Comment by hkndzdr** [comment]
> Screenshot from the EasyLocalizationState class
> ![image](https://user-images.githubusercontent.com/52201392/77238968-2a036a00-6bde-11ea-8018-6198115a2f7e.png)
> 
> If you wrapped the EasyLocalization top level Widget with another Container Widget its color white you will see white screen instead of black screen, The problem as you see in the screenshot is that the FutureBuilder Widget returns a Container Widget represents the top level Widget of your app and that Container has a transparent background color as default so what appears until the easy localization FutureBuilder get completed is a transparent Container no thing above it and no thing in flutter means black.
> 
> Try what i have done here and your problem is solved.
> ![image](https://user-images.githubusercontent.com/52201392/77239220-ca5a8e00-6be0-11ea-9193-22bfdbd73f53.png)
> 
> So @aissat that Container in the FutureBuilder shouldn't be hard codded like that, It should be handled with a parameter like that.
> ![image](https://user-images.githubusercontent.com/52201392/77239456-9f256e00-6be3-11ea-9dcb-e921b8584e7b.png)

Thanks for your descriptive answer. An effective method as a workaround. I have not insisted in vain that this problem is not something special to me. In the issues that have already been closed ([#26](https://github.com/aissat/easy_localization/issues/26), [# 40](https://github.com/aissat/easy_localization/issues/40)), the same problem has been raised by different users.

Your suggestion for the solution is quite logical. Hopefully it will be fixed in a short time

**Comment by aissat** [comment]
@AlaaEldeenYsr thnx for this  details   
@hkndzdr i'm working on ...

**Comment by Overman775** [comment]
> @hkndzdr I'm working on ...

Do you need help?

**Comment by aissat** [comment]
@Overman775  yeah;)

**Comment by aissat** [comment]
https://github.com/aissat/easy_localization/issues/98#issuecomment-602260031

**Comment by Overman775** [comment]
@hkndzdr @AlaaEldeenYsr PR #99

**Comment by hkndzdr** [comment]
@aissat @Overman775 
Removing the container widget did not affect the background color. The black screen continues in the same way. I keep wrapping it with container widget in the main.dart page.

**Comment by aissat** [comment]
> @aissat @Overman775
> Removing the container widget did not affect the background color. The black screen continues in the same way. (ver. 2.0.2) I keep wrapping it with container widget in the main.dart page.

@moritzmorgenroth

**Comment by moritzmorgenroth** [comment]
@hkndzdr I cannot reproduct this. The EasyLocalization widget is not doing any blocking/asynchronous tasks any more. Can you share your sourcecode?

**Comment by hkndzdr** [comment]
> @hkndzdr I cannot reproduct this. The EasyLocalization widget is not doing any blocking/asynchronous tasks any more. Can you share your sourcecode?

I share videos instead of code. I used the Sample application in the repo.

[](https://www.youtube.com/watch?v=XpCKjeYuRjo)

**Comment by Overman775** [comment]
> @hkndzdr I cannot reproduct this. The EasyLocalization widget is not doing any blocking/asynchronous tasks any more. Can you share your sourcecode?

I have same bug,not always.... catch on 10 attempt

```
  runApp(Container(
    color: Colors.red,
    child: EasyLocalization(
      child: MyApp(),
```

**Comment by Overman775** [comment]
@moritzmorgenroth @aissat 

in 9/10 text flickering, 1/10 black screen
![ScreenRecorderProject10](https://user-images.githubusercontent.com/47769319/77558539-ddb97200-6edc-11ea-8c82-920bb8b5a057.gif)

**Comment by hkndzdr** [comment]
> > @hkndzdr I cannot reproduct this. The EasyLocalization widget is not doing any blocking/asynchronous tasks any more. Can you share your sourcecode?
> 
> I have same bug,not always.... catch on 10 attempt
> 
> ```
>   runApp(Container(
>     color: Colors.red,
>     child: EasyLocalization(
>       child: MyApp(),
> ```

Yes. The situation changes according to the current memory load of the device. I shared the image on the emulator so you can look clear.

**Comment by moritzmorgenroth** [comment]
Are you sure you updated the version in your

> in 9/10 text flickering, 1/10 black screen(red container)
> ![ScreenRecorderProject10](https://user-images.githubusercontent.com/47769319/77558539-ddb97200-6edc-11ea-8c82-920bb8b5a057.gif)

@Overman775 the flickering is due to the async/non blocking shared preference language loading. The red screen is a mistery to me. Maybe we need to separate the use cases for using the system locale and saving/loading a custom local at a higher level to avoid this kind of behavior...

**Comment by Overman775** [comment]
> Are you sure you updated the version in your

@moritzmorgenroth Yeap, latest 2.0.2

Text flickering cannot be deleted because we are use async loading from the asset

**Comment by moritzmorgenroth** [comment]
> @Overman775 the flickering is due to the async/non blocking shared preference language loading. The red screen is a mistery to me. Maybe we need to separate the use cases for using the system locale and saving/loading a custom local at a higher level to avoid this kind of behavior...

@aissat @Overman775 would you prefer a loader widget? We could go back to loader, but then we should make sure that async/blocking behavior is only happening if the `saveLocale` feature is used

**Comment by Overman775** [comment]
@aissat @moritzmorgenroth If we get back to FutureBuilder then need to track three parameters:

1. asset loader,
2. device locale if save locale null,
3. save locale if enabled

**Comment by aissat** [comment]
@moritzmorgenroth  @Overman775  

> > @Overman775 the flickering is due to the async/non blocking shared preference language loading. The red screen is a mistery to me. Maybe we need to separate the use cases for using the system locale and saving/loading a custom local at a higher level to avoid this kind of behavior...
> 
> @aissat @Overman775 would you prefer a loader widget? We could go back to loader, but then we should make sure that async/blocking behavior is only happening if the `saveLocale` feature is used
@moritzmorgenroth @Overman775 
i don't like it but need a solution

**Comment by Overman775** [comment]
> > i don't like it but need a solution

@aissat @moritzmorgenroth can try the idea catch widget.children #102

**Comment by moritzmorgenroth** [comment]
I think the most convenient / efficient solution would be to adjust the documentation, only setting `locale: EasyLocalization.of(context).locale,` on the material widget if you want to use the save locale. Then we can do a futurebuilder if savelocal is used and else the flutter system stuff will do its magic and we dont bloc anything with future builder.

**Comment by moritzmorgenroth** [comment]
I think the use cases are so inherently different that they need stronger distinction. I have a clear picture in my head, dont know if ill find time to implement it before the weekend though...

**Comment by aissat** [comment]
> @aissat @moritzmorgenroth If we get back to FutureBuilder then need to track three parameters:
> 
>     1. asset loader,
> 
>     2. device locale if save locale null,
> 
>     3. save locale if enabled

#103  coz  asset loader,

**Comment by AlaaEldeenYsr** [comment]
You updated the package and didn't provide any way for handling the loading operation ?!!!!!!!

**Comment by Overman775** [comment]
@hkndzdr Black screen is only in develop version, i test on 6 years old android phone, all fine ;)

**Comment by hkndzdr** [comment]
> @hkndzdr Black screen is only in develop version, i test on 6 years old android phone, all fine ;)

I'm glad to hear that..
